### ISSUE TITLE
Why use Angularjs/JSON API in Wordpress if we have Timber/JSON API

### ISSUE THREAD

**Issue by hainakus** [timber/timber#1063]
Hi,

i am using Timber and Json API for an expected wedding portal. My question is what are the draw backs of choosing MVC Timber with JSON API than Angularjs, expecting plenty of visitors...

Regards.

**Comment by connorjburton** [comment]
Hm, sorry if I misunderstood the question. Angular is used for more single page applications or larger apps with lots of two way data binding. Timber is completely different and is a static templating language. It really depends on what you are building and what it requires.

Timber would be a much simpler approach and easier to scale. What are your concerns with the project and what re you trying to achieve with either angular or timber.

**Comment by mrgrain** [comment]
Look up Serverside vs Client side application. That's the difference and the "drawbacks" for each way.

However using timber to query the JSON API seems a bit odd to me as you'll have to run through the wordpress stack to get the timber HTML and than again to get the contents.

**Comment by hainakus** [comment]
Hi,

in order to clarify. i am using simple functions to call the objects through API like for basic example Posts, In the controller single.php i call the API funtion and them in the view call the post object and loop it or do something else with it. I am thinking should be a quicker way than using angular.

I know the client side vs server side drawbacks but i am interested in a quicker away to develop and also to have quicker loading time an simpler code.

Personnally Angular in wordpress and in a theme is something strange to me. So i am using angular way but with timber and twig views.

Example of controller:

$context = Timber::get_context();
$context['foo'] = 'bar';
$context['blog'] = getPosts(); //API Function for calling posts expecting a quicker and bypass some php wordpress query functions and quicker data loading.

Regards and thanks.

**Comment by connorjburton** [comment]
If you are just concerned with using Wordpress as an API, ditch Timber and use WP Rest API instead, that'll hook up nicely with Angular.

I don't really know why you'd want to bypass wordpress to grab posts, otherwise why not just ditch wordpress all together?

Loading times should be quick due to Twig's caching anyway.

**Comment by hainakus** [comment]
Hi Connor,

the project is depending also on woocommerce yith vendors and other shunks of plugin codes. So why not use API and Timber? 
In your opinion as far i understood you say to use them separated. So you don't see it feasable?

**Comment by connorjburton** [comment]
In that case you'd just use Timber as described in the docs, with the standard `Timber::get_posts` function calls etc and using the php files as your controller.

I'm not sure what you mean by API

**Comment by hainakus** [comment]
API is the WP Rest Api or JSON API plugins.

**Comment by alenabdula** [comment]
@hainakus 

If you need to sprinkle some JavaScript in your templates that query WordPress API, I suggest using VueJS instead of Angular). It's lighter and faster two way data binding.

Here are some free resources for VueJS

- [VueCasts](https://laracasts.com/series/learning-vue-step-by-step)
- [FullStack Radio interview with created Evan You](http://www.fullstackradio.com/30)

You can look at my `germinate-spa` [repository](https://github.com/alenabdula/germinate-spa) to get some ideas. Look at the [GerminateApiRoutes.php](https://github.com/alenabdula/germinate-spa/blob/master/lib/GerminateApiRoutes.php) and set up some API routes that you can query with VueJS.

> I know the client side vs server side drawbacks but i am interested in a quicker away to develop and also to have quicker loading time an simpler code... Personnally Angular in wordpress and in a theme is something strange to me. So i am using angular way but with timber and twig views.

Angular, VueJS are Single Page JavaScript Application Frameworks. You can use it through your WordPress theme however you desire whether your using Timber, just PHP or whatever. It doesn't necessarily have to be a SPA. You can hook your JavaScript framework to DOM element, ex. `#module`, then the JS will act on that element alone and do any necessary querying and displaying of data.

> also to have quicker loading time an simpler code

Adding JS framework will certainly not make things faster or produce simpler code.

Can you expand on what you're trying to do specifically and we can point you in a reasonable direction?

Hope that helps, Best Alen.

**Comment by hainakus** [comment]
Hi Alen,

building a wedding website in order to client (wedding supliers and wedding brides) to join. Will have a marketplace (woocommerce built in) and Vendors. 

Dashboard for both client roles. And some special features like vendor-client private messaging.

Video library uploaded by clients and blog, etc.

Hope i could explain. Also thanks for sharing your knowledge.

Regards

**Comment by lmartins** [comment]
This is something I am also exploring now. I have a traditional WP site, where some components are rendered with Vue.js 
For those components, would be very useful to have Timber's queries return JSON data to be consumed by Vue. The new WP REST API would be my first approach, although Timber's methods have the advantage of already including meta fields and other data that would need to approached differently with the REST API.
