### ISSUE TITLE
Create new Pagination API

### ISSUE THREAD

**Issue by jarednova** [timber/timber#1118]
Relates to #816 

Create new pagination object that directly relates to a `PostsCollection` so that pagination more naturally relates to the collection of posts the user is handling

**Comment by RadoslavGeorgiev** [comment]
@jarednova why are you associating the pagination with a `PostsCollection`?

I think it would make more sense to associate it with `QueryIterator` and to use the native WordPress pagination.

This way, if you also include a `$query` element in `Timber::get_context()`, which wraps the main `$wp_query`, even in the default templates, like archives and posts page, you would be able to simply use `query.pagination` without any additional setup.

**Comment by lggorman** [comment]
@RadoslavGeorgiev I like pagination associated with the PostsCollection largely because it seems intuitive from an API perspective, e.g. `{% for page in posts.pagination.pages %}`.  But I can also see the logic in using the `QueryIterator`.  I'm not quite clear -- what would that look like on the php side, in terms of setting up the context?
