### ISSUE TITLE
Timber cannot resize images with Hebrew characters

### ISSUE THREAD

**Issue by chetzof** [timber/timber#1133]
Name any image `איתין-נוף-נוסף.jpg` , upload to wordpress and try to resize it 

```
{{ image|resize(100, 100) }}
```

The call returns original image, no resizing is done.
Not sure if the bug is OS-dependent, but is reproducible on any Linux OS.

**Comment by palmiak** [comment]
@chetzof did you tried to investigate it further? We had a similar problem with Ukrainian letters, but didn't had time to go further with it.

From what I see there is a plugin https://wordpress.org/plugins/cyrlitera/ (for russian) or https://wordpress.org/plugins/sanitize-spanish-filenames/ (many languages) that fixes those problem - maybe it would be worth a while to looke deeper into them and use their funcionality to fix the problem.

**Comment by danburzo** [comment]
It seems that by the time it reaches the WP image editor, the path to the image file has been transformed / sanitized, and the WP Image Editor can't find it (I'm getting 'Error loading <sanitized-name>' when enabling Timber logging). Following the code from resize() to the WP Image Editor should reveal where this happens, but I have not had the chance yet to look into it.

**Comment by danburzo** [comment]
Okay, looked into it further and the calls to the `pathinfo()` and `basename()` PHP functions mangle the source file name, since they depend on the locale set on the server. In my particular setup, these functions mostly work with the (default?) 'C' locale, except [when they start with a special char](https://bugs.php.net/bug.php?id=77239), which gets stripped :/

Any chance there's a small library that does not depend on the locale to extract path segments?

**Comment by danburzo** [comment]
Okay, I edited the ImageHelper class to use `wp_basename()` and copied over the implementation of `mb_pathinfo()` and the issues went away, so it's something worth considering I think!

**Comment by gchtr** [comment]
Resolved in #2072.
