### ISSUE TITLE
\Timber\Site\__construct breaks image srcset

### ISSUE THREAD

**Issue by lancemonotone** [timber/timber#1180]
### Expected behavior

Should get srcset image urls like "/files/image_name.jpg".
### Actual behavior

Instead srcset image url is "wp-content/blogs.dir/blog_id/files/<image_name>.jpg". This prevents scrset from displaying responsive images.
### Steps to reproduce behavior

Broken code 

**return switch_to_blog($blog_ids['old']);**

``` php
public function __construct( $site_name_or_id = null ) {
        if ( is_multisite() ) {
            $blog_ids = self::switch_to_blog($site_name_or_id);
            $this->init();
            $this->init_as_multisite($blog_ids['new']);
            return switch_to_blog($blog_ids['old']);
        } 
        $this->init();
        $this->init_as_singlesite();
}
```

Working code 

**return restore_current_blog();**

``` php
public function __construct( $site_name_or_id = null ) {
        if ( is_multisite() ) {
            $blog_ids = self::switch_to_blog($site_name_or_id);
            $this->init();
            $this->init_as_multisite($blog_ids['new']);
            return restore_current_blog();
        } 
        $this->init();
        $this->init_as_singlesite();
    }
```
### What version of WordPress, PHP and Timber are you using?

WordPress 4.4.2, Timber 1.1.2

---

This function could use some documentation. Why is switching blogs necessary at all and why switch back to using `switch_to_blog()` again, instead of `restore_current_blog()`? With the current code, `$GLOBALS['_wp_switched_stack']` is not emptied, thus `ms_is_switched()` returns true, and `wp_upload_dir()` returns the wrong baseurl for srcset.

**Comment by gchtr** [comment]
The issue with `restore_current_blog()` was fixed in https://github.com/timber/timber/pull/1244.

Regarding your other question:

> Why is switching blogs necessary at all?

I see that with the current logic, Timber always uses `switch_to_blog()` in a multisite environment, even if it wouldn’t have to. Even though `switch_to_blog()` doesn’t do all the hard work if we’re already on the same blog, it still sets `$GLOBALS['_wp_switched_stack']` and `$GLOBALS['switched']`. I think this could be improved:

- [x] Prevent using `switch_to_blog()` in `Timber\Site::__construct()` when not necessary.
