### ISSUE TITLE
Suggestion: Make a note about restoring original query in docs page about pagination

### ISSUE THREAD

**Issue by lithiumlab** [timber/timber#1200]
When using Timber to generate a custom shortcode for displaying posts with pagination i found if no `wp_reset_query();` is used after constructing the output leaves the original query altered when `query_posts();` is used.

I suggest to add a note in the code example here:
https://github.com/timber/timber/wiki/Pagination

Something like this should restore the normal query after manipulation:

```
function get_example_posts(){

$data = Timber::get_context();
 global $paged;
    if (!isset($paged) || !$paged){
        $paged = 1;
    }
    $context = Timber::get_context();
    $args = array(
        'post_type' => 'my-custom-type',
        'order' => 'DSC',
        'posts_per_page' => 8,
        'paged' => $paged
    );
    query_posts($args);

    $data['post'] = new TimberPost();
    $data['posts'] = Timber::get_posts();
    $data['pagination'] = Timber::get_pagination();
    $out = Timber::compile('featured.twig, $data);

    wp_reset_query();

    return $out;
}
add_shortcode('featured_posts', 'get_example_posts');
```

**Comment by gchtr** [comment]
As mentioned in the documentation for [`query_posts()`](https://developer.wordpress.org/reference/functions/query_posts/), this will affect the main query and should be avoided:

> … isn’t intended for use by plugins or themes. Its overly-simplistic approach to modifying the main query can be problematic and should be avoided wherever possible.

So when you use this function, you’d probably always have to call `wp_reset_query()`. The easiest solution here would probably be to not rely on `query_posts()`, but use a method that Timber provides:

```php
add_shortcode('featured_posts', function() {
    global $paged;

    if ( !isset($paged) || !$paged ){
        $paged = 1;
    }

    $data          = Timber::get_context();
    $data['post']  = new Timber\Post();
    $data['posts'] = new Timber\PostQuery( array(
        'post_type'      => 'my-custom-type',
        'order'          => 'DESC',
        'posts_per_page' => 8,
        'paged'          => $paged
    ) );

    return Timber::compile( 'featured.twig', $data );
} );
```

I guess the pagination was updated since you posted this issue. You can follow the [Pagination Guide](https://timber.github.io/docs/guides/pagination/) to see how works with `Timber\PostQuery`.
