### ISSUE TITLE
Showing an internal link or external link by toggling radio buttons with ACF

### ISSUE THREAD

**Issue by frazerf** [timber/timber#1248]
Hi there,

I have a repeater set up that loops over a list of events. Within those events they can link to an external or internal page. I've set this up in ACF but I'm having some trouble with conditional logic.

Basically in ACF I have two radio buttons. One that says "yes" that shows the internal page link and "no" which shows a URL field.

Could anyone help me out on where I'm going wrong?

`
{% for event in post.get_field('event') %}

              <div style="background: url({{Image(event.event_image).src}})"></div>
              {{event.event_title}}
              {{event.event_content}}

              {% if event.is_this_an_internal_link(option) == 'yes' %}
                <a href="{{event.event_link_internal}}">{{event.event_link_content}}</a>
              {% else %}
                <a href="{{event.event_link_external}}">{{event.event_link_content}}</a>
              {% endif %}
              

            {% endfor %}
`

**Comment by gchtr** [comment]
I guess this is not really an issue specific with Timber, but more of a question on how to implement ACF with Timber. A better place to ask these kind of questions would probably be [Stackoverflow](http://stackoverflow.com/questions/tagged/timber) or the [Gitter chat](https://gitter.im/timber/timber). But maybe I can help.

---

In your Twig file you have this line:

```twig
{% if event.is_this_an_internal_link(option) == 'yes' %}
```

Where does the `option` variable come from that you pass as a parameter? Is `is_this_an_internal_link` a method that you defined for event posts? If it’s just the name of the ACF field, try this:

```twig
{% if event.is_this_an_internal_link == 'yes' %}
```

Now the most standard way to achieve something like this would probably be to use a [**True / False** field](https://www.advancedcustomfields.com/resources/true-false/) instead of a Radio Button field with "yes" and "no" as possible options.

If your field is named `is_this_an_internal_link`, you could use:

```twig
{% if event.is_this_an_internal_link %}
```

**Comment by palmiak** [comment]
@frazerf Is this still something you're actively working on or need addressed? Please respond in two weeks or we'll close this thread
