### ISSUE TITLE
Multiple args in ACF Flexible content loop

### ISSUE THREAD

**Issue by benthek** [timber/timber#1262]
Hi,

I am trying to create a flexible content loop that includes an article row in which my client can select which posts are being displayed. Right now, I have two options: based on date and based on place (ACF relation field). It only works for one row, once there are more rows, the content of all rows is the same. How do I make sure the output of $context['flex_posts'] varies for two different rows?

single.php:
<pre>if( have_rows('custom_content_grid') ):
	while ( have_rows('custom_content_grid') ) : the_row();
		if( get_row_layout() == 'article_row' ):
			$article_row_type = get_sub_field('article_row_type');
			$article_row_places = get_sub_field('article_row_places');
			if ($article_row_type == 'date') {
				$args = array(
				    'post_type' => 'post'
				);
			} elseif ($article_row_type == 'places') {
				$args = array(
				    'post_type' => 'post',
				    'meta_key' => 'article_place',
				    'meta_value' => $article_row_places->ID,
				);
			}
			$context['flex_posts'] = Timber::get_posts($args);
		endif;
	endwhile;
endif;</pre>

single.twig:

<pre>
{% for content_row in post.get_field('custom_content_grid') %}
	{% if content_row.acf_fc_layout == 'article_row' %}
		{% for flex_post in flex_posts %}
			{{flex_post.title}}
		{% endfor %}
	{% endif %}
{% endfor %}
</pre>

**Comment by gchtr** [comment]
I guess this is not really an issue specific with Timber, but more of a question on how to implement ACF with Timber. A better place to ask these kind of questions would probably be [Stackoverflow](http://stackoverflow.com/questions/tagged/timber) or the [Gitter chat](https://gitter.im/timber/timber).

---

You write `$context['flex_posts'] = Timber::get_posts($args);` inside a while loop. This way, only the last post will be saved in your context, because `$context['flex_posts']` is overwritten on and on. Just making `$context['flex_posts']` an array probably won’t work either, because you’d end up with one big array of posts, where you can’t discern to which row the posts belong to.

I’d approach like this: Loop over the flexible content fields of a post, fill them with the additional content that you need (the posts based on date or place) and write the result back to a new property of your post (`$post->rows`).

Consider that in the following example, I didn’t use the functions advertised by ACF (`have_rows` etc.), but access field properties directly (e.g. `$row->acf_fc_layout`). This is a benefit of using Timber.

```php
<?php

// Introduce new property to post that will hold the flexible content fields with additional data added.
$post->rows = array();

/**
 * Loop over the single flexible content fields. This field is not accessible 
 * like the rest of the fields when using ACF and Timber, where you could go 
 * with $post->fieldname. You need to use the `get_field` method to actually 
 * get the content of repeaters and flexible content fields.
 */
foreach ( $post->get_field( 'custom_content_grid' ) as $row ) {
	if ( 'article_row' === $row['acf_fc_layout'] ) {
		if ( 'date' === $row['article_row_type'] ) {
			$args = array(
			    'post_type' => 'post',
			);

		} elseif ( 'places' === $row['article_row_type'] ) {
			$args = array(
			    'post_type' => 'post',
			    'meta_key' => 'article_place',
			    /**
			     * If $row['article_row_places'] is an array containing 
			     * multiple post objects simply accessing ID might not work.
			     */
			    'meta_value' => $row['article_row_places']->ID,
			);
		}

		// Save the posts in a new property of the row
		$row->posts = Timber::get_posts( $args );
	}
	
	// Write row back to rows array of the post
	$post->rows[] = $row;
}

// Everything you need is now in $post
$context['post'] = $post;
```

Your twig file would change to this:

```twig
{% for content_row in post.rows %}
	{% if content_row.acf_fc_layout == 'article_row' %}
		{% for post in content_row.posts %}
			{{ post.title }}
		{% endfor %}
	{% endif %}
{% endfor %}
```

I hope this works, because I didn’t test this, but rather put it together from checking code I used in similar use cases.

**Comment by benthek** [comment]
Hi Lukas,

Thanks for your suggestion! I think I'm getting closer with your code, but I'm getting this warning:

<pre>Attempt to assign property of non-object</pre>

Do you have any idea what is going wrong?

**Comment by gchtr** [comment]
It might be this line:

```php
// Save the posts in a new property of the row
$row->posts = Timber::get_posts( $args );
```
`$row` is actually an array and I tried to use it as an object. Please change it to the following to see if it works:

```php
// Save the posts in a new property of the row
$row['posts'] = Timber::get_posts( $args );
```

**Comment by benthek** [comment]
It works now, thank you very much Lukas! 👍 :-)

**Comment by gchtr** [comment]
Nice! Glad I could help.

**Comment by gchtr** [comment]
I guess this could be closed, then?
