### ISSUE TITLE
Fatal error when another plugin is installed that uses Twig and Timber version is >= 1.1.12

### ISSUE THREAD

**Issue by blocher** [timber/timber#1286]
### Expected behavior
A functioning website without a fatal error

### Actual behavior
Displays a fatal error: "The "Twig_Extension_Core" extension is not enabled."

See stack trace at: https://gist.github.com/blocher/71ec2e1322f88e30780b8e44b77d6063

### Steps to reproduce behavior
- Install and activate Timber >= version 1.1.12
- Install and activate another plugin that uses Twig, such as All in One Event Calendar (https://wordpress.org/plugins/all-in-one-event-calendar/)
- Activate theme that uses Timber
- Load public website in browser

See stack trace at: https://gist.github.com/blocher/71ec2e1322f88e30780b8e44b77d6063

### What version of WordPress, PHP and Timber are you using?
Wordpress 4.7, PHP 7.0.14, Timber 1.1.12 or 1.2 (no issue in earlier versions)

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Upgraded to newest version via plugin updater in WordPress dashboard
Also tried cloning from GitHub and manually unzipping file from WP.org

**Comment by mahagr** [comment]
The issue comes from the two plugins both including Twig library, but a different version of it. The newest version of Twig deprecated some code and provides a new 2.0 compatible way instead. This doesn't work in the older Twig version, thus causing the error.

There's really nothing you can do except for asking plugin developer to update his twig dependency to the latest version. Or you can make sure that the older version doesn't get loaded, either by updating the vendor library by yourself or removing it manually from the plugin.

**Comment by jarednova** [comment]
@mahagr @blocher good news! Timber now uses Twig 2.0! If I understand @mahagr correctly this _should_ resolve the issue; but please confirm with the latest master if you can.

**Comment by mahagr** [comment]
Don't use Twig 2.0, it's for PHP7 only. Use the latest 1.1 version which is mostly compatible with 2.0.

The issue here is that the another/conflicting plugin is using an old version of Twig and should be updated. Timber was just fine. :)

**Comment by blocher** [comment]
Thank you for the help!  Upgrading Twig on the other plugin to the latest 1.x does the trick.  Timber does in fact work great.
