### ISSUE TITLE
getting featured image from custom post type

### ISSUE THREAD

**Issue by alexadark** [timber/timber#1300]

**Comment by alexadark** [comment]
Hi,
i have a custom post type name people and need to get the feat image
i do that
` {% for person in people %}
<img src="{{ person.thumbnail.src }}"
         alt="">
{% endfor %}`
but it doesn't work, and don't understand why
is the syntax different for CPT than for posts
i have noticed that i need post_title instead of title

**Comment by corradomatt** [comment]
Hi @alexadark - You'll need to share the code you're using to create `people` so we can get a better idea of what you're doing. Does `{{ dump(person) }}` return all the same data as `{{ dump(post) }}` does within a blog page loop on an archive page?

**Comment by codemonkeynorth** [comment]
try 

```<img src="{{ TimberImage(person.thumbnail).src }}"```

generally I do something like this, so I don't need to keep calling TimberImage

```twig
{% for person in people %} 
{% set person_image = TimberImage(person.thumbnail) %}
<img src="{{ person_image.src|resize(640) }}" alt="{{ person_image.alt }}"> 
{% endfor %}
```

**Comment by leflis** [comment]
I know this is an old post but Im still trying to figure this out. 

<img src="{{ TimberImage(person.thumbnail).src }}" />

does not work.

**Comment by gchtr** [comment]
@leflis If you use `get_field( 'popular_articles' )`, you will get an array of post IDs or post arrays defined by ACF. For Timber to work correctly, you first need to convert these to Timber posts. Without it, you will just loop over the array that is returned by ACF and there will be no Timber functionality.

Here’s how I would do it:

**single.php**

```php
$context['populars'] = Timber::get_posts( get_field( 'popular_articles' ) );
```

It’s best if you select to return the post IDs only in the `popular_articles` field settings, because Timber will refetch the data already populated by ACF.

**single.twig**

```twig
{% for popular in populars %}
	{{ TimberImage(popular.thumbnail).src }}

	{{ popular.title }}
	{# instead of {{ popular.post_title }} #}
{% endfor %}
```
