### ISSUE TITLE
Breaking change to TimberTheme's uri for child themes

### ISSUE THREAD

**Issue by adamtomat** [timber/timber#1313]
### Expected behavior
We have a child theme on-top of our own core theme, built on Timber. Normally we load assets from the child theme (e.g. theme specific styles), and sometimes need to load assets from the parent theme (e.g. core styles).

In `1.2.0`, in Twig I can do: `{{ site.theme.uri }}`, which returns the absolute path to the child theme `http://<domain>/app/themes/<child-theme-name>`.

I am also able to get the parent theme's uri with:

```twig
{% set parentUri = site.theme.uri %}

{% if site.theme.parent.uri %}
    {% set parentUri = site.theme.parent.uri %}
{% endif %}
```

In `1.2.1` I would expect the same behaviour, as there's no breaking changes.

### Actual behavior

However, in `1.2.1` when I do `{{ site.theme.uri }}`, it returns the absolute path to the *parent* theme, not the child theme. e.g: `http://<domain>/app/themes/<parent-theme-name>`.

It looks like [this commit is the one that changed behavior](https://github.com/timber/timber/pull/1281/files?diff=unified#diff-920c5ce40c6e0c76e2af998a5acef94f).

Primarily, this:

`$this->uri = get_stylesheet_directory_uri();`

was changed to:

`$this->uri = $this->theme->get_template_directory_uri();`

### Thoughts

Is this change the expected/intended behaviour? Where the uri always references the parent theme? 

Now, it looks like `uri` [isn't documented](http://timber.github.io/timber/#timber-theme) and therefore this change is fine as we should be using `{{ site.theme.link }}` anyway. If that's the case, is there an argument to make the uri protected?

### Steps to reproduce behavior
Create a child theme, and activate it. In the parent theme, in any twig view add `{{ site.theme.uri }}`. You should see different urls between `1.2.0` and `1.2.1`.

### What version of WordPress, PHP and Timber are you using?
WordPress 4.7.2, PHP 5.6, Timber 1.2.0

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Composer

**Comment by xavivars** [comment]
I made the changes in the commit, so let me explain the reason why I did it. 

It turned out that the previous approach to get "parent" and "child" urls was not working when the theme was in a non standard location (by using `register_theme_directory`).

By trying to understand what each method or property was supposed to return, looking at the existing documentation (as you say, uri was not documented) and the existing unit tests, it seemed to me that the `link` method  was supposed to be the child theme uri (or the parent, in case the child didn't exist) while uri was always supposed to contain the parent theme uri. And that assumption didn't break any of the existing tests, so I thought I was covering all current functionality. Now it's clear it was not. 

I agree with you that the equivalent for `get_stylesheet_uri` should be `link` as it is document. But I'm not sure `uri` should be protected, as it's the equivalent to WordPress' `get_template_uri`. 

What probably should be done is to document properly each of the methods/properties, so nothing public is not documented.

**Comment by adamtomat** [comment]
I think updating the documentation to properly describe the intended behaviour would be the best outcome here too. 

As a public API, we currently have:

> - link (string) - the absolute path to the theme (ex: http://example.org/wp-content/themes/my-timber-theme)
> - name (string) - the human-friendly name of the theme (ex: My Timber Starter Theme)
> - parent (TimberTheme) - bool
> - parent_slug (string) - the slug of the parent theme (ex: _s)
> - path (string) - the relative path to the theme (ex: /wp-content/themes/my-timber-theme)
> - slug (string) - the slug of the theme (ex: my-super-theme)

The simple fix would be to update the description for `link` to something like this:

> the absolute path to the currently activated theme. In the case a child theme is being used, the absolute path to the **child** theme directory will be returned. (ex: http://example.org/wp-content/themes/my-timber-theme)

And to add an entry for `uri`:

> - uri (string) - the absolute path to the directory of the current theme. In the case a child theme is being used, the absolute path to the **parent** theme directory will be returned. (ex: http://example.org/wp-content/themes/my-timber-theme).

I think it would be worth clarifying what happens when using a child theme for some of the other fields too, for example `path`.
