### ISSUE TITLE
Filter function working on WP not working on Timber

### ISSUE THREAD

**Issue by mariosmaselli** [timber/timber#1390]
I have this function, I have used it and it works fine without Timber. 

```
function filter_ptags_on_images($content) {
    $content = preg_replace('/<p>\s*(<a .*>)?\s*(<img .* \/>)\s*(<\/a>)?\s*<\/p>/iU', '\1\2\3', $content);
    return preg_replace('/<p>\s*(<iframe .*>*.<\/iframe>)\s*<\/p>/iU', '\1', $content);
}
add_filter('acf_the_content', 'filter_ptags_on_images', 9999);
add_filter('the_content', 'filter_ptags_on_images', 9999);
```

I use it to remove p tags on WYSIWYG that have an image. For both normal WP content and ACF content.

Current behaviour: 
```
<p>Text</p>
<p><img src="myimage.jpg" /></p>
<p>Text</p>
```

Expected behaviour 
```
<p>Text</p>
<img src="myimage.jpg" />
<p>Text</p>
```

I have tried the following with no success.

```
add_filter( 'get_twig', array( $this, 'add_to_twig' ) );

function add_to_twig( $twig ) {		
        $twig->addFilter('acf_the_content', new Twig_Filter_Function('filter_ptags_on_images'));
	$twig->addFilter('the_content', new Twig_Filter_Function('filter_ptags_on_images'));
	return $twig;
}

function filter_ptags_on_images($content) {
    $content = preg_replace('/<p>\s*(<a .*>)?\s*(<img .* \/>)\s*(<\/a>)?\s*<\/p>/iU', '\1\2\3', $content);
    return preg_replace('/<p>\s*(<iframe .*>*.<\/iframe>)\s*<\/p>/iU', '\1', $content);
}

```

I will appreciate some help thanks!

WP 4.7.3, Timber 1.2.4,  PHP 7, ACF Pro  5.3.9.2.

**Comment by gchtr** [comment]
Hey @mariosmaselli 

I tested your code, the filter looks fine. I looked at what Timber does exactly do in the background, and I just learned something essential myself.

Timber automatically populates your meta fields as properties of your post object. Say you use the field name `richtext` for your WYSIWYG field, you can access it like this in Twig:

```twig
{{ post.richtext }}
```

**However** (and here comes the gist 🥁), **this only returns the value that’s in the database**. No filtering is applied. If you want ACF filters included, you have to do

```twig
{{ post.get_field( 'richtext' ) }}
```

I assume that because Timber doesn’t know which meta fields are actual ACF fields and which fields might come from other plugins, it doesn’t use `get_field` for all custom fields, which is very reasonable.

---

However, your solution where you tried adding custom Twig filters should also work. Where did you put this code?

```php
add_filter( 'get_twig', array( $this, 'add_to_twig' ) );

function add_to_twig( $twig ) {		
        $twig->addFilter('acf_the_content', new Twig_Filter_Function('filter_ptags_on_images'));
	$twig->addFilter('the_content', new Twig_Filter_Function('filter_ptags_on_images'));
	return $twig;
}

function filter_ptags_on_images($content) {
    $content = preg_replace('/<p>\s*(<a .*>)?\s*(<img .* \/>)\s*(<\/a>)?\s*<\/p>/iU', '\1\2\3', $content);
    return preg_replace('/<p>\s*(<iframe .*>*.<\/iframe>)\s*<\/p>/iU', '\1', $content);
}
```

Is it in `functions.php`? And is it wrapped in a class? Because when you do `add_filter( 'get_twig', array( $this, 'add_to_twig' ) );`, then `$this` refers to the current class. That’s why you’d have to use it in a class.

If you don’t want to wrap it in a class, you can use

```php
add_filter( 'get_twig', 'add_to_twig' );
```

And then you can use it like this:

```twig
{{ post.your_acf_field|acf_the_content }}
```

---

Maybe this is all not very well documented. I’ll have a look at what’s missing and what needs to be changed, because it’s a question that comes up quite often.

**Comment by gchtr** [comment]
Looks like this issue has become stale. Using `{{ post.meta() }}` will be the recommended way to access meta values in Timber 2.0, including ACF support. I’m closing this.
