### ISSUE TITLE
Official 1.3.0 Release to Wordpress Plugins

### ISSUE THREAD

**Issue by skynet** [timber/timber#1401]
When should we expect to see this in the Wordpress Plugins repository?

**Comment by skynet** [comment]
I was able to find 1.3.0 in the plugins Downloads list

![image](https://cloud.githubusercontent.com/assets/139233/25558886/eab33a5a-2cfd-11e7-8550-f6e266ea8cd9.png)

**Comment by jarednova** [comment]
@skynet Because this is a significant update, I like to wait one week to deploy to WP.org after releasing. This way more savvy users on GH/Packagist are more likely to flag regressions. As you can see it's already there, but I'm holding on updating the readme to point to it until Tuesday

**Comment by jarednova** [comment]
@skynet because of some possible image issues I've had reported [#1303](https://github.com/timber/timber/issues/1303#issuecomment-299122877) and #1404 — I want to get things in a better place before deploying to some 25k WP.org users. Obviously you're welcome to still use it, but I want to wait for these image issues to shake out before pushing to a wide audience

**Comment by skynet** [comment]
Thank you for the update!
