### ISSUE TITLE
[question][feature-request] Get ACF repeater field with dot notation.

### ISSUE THREAD

**Issue by wujekbogdan** [timber/timber#1416]
### Expected behavior
I'd like to get top-level ACF repeater field with:
`{% for item in post.my_repeater_field %}`
Like I would do with any array.

### Actual behavior
I have to call a `get_field()` function:
`{% for item in post.get_field('my_repeater_field') %}`

---
Why there's a need to call the `.get_field()` function in order to access a top-level repeater fields?
- One of the main reasons to use Timber is to decouple templates code from the backend, but `get_field()` calls make twig templates coupled with the backend again, and what's worse, templates are becoming dependent on a specific plugin (ACF of course)
- It's inconsistent. In order to get top level fields, one have to call the `.get_field()` function, but in order to get nested fields, there's no need to call it. We can access nested fields with dot notation. It's i but confusing.

I guess that there must be some reason behind it.  Otherwise, you would probably implement it differently. Am I right?

PS
Yes, I know that I can call `get_field()` in PHP and pass a result to the `render` method.

**Comment by gchtr** [comment]
I like the idea.

But it’s probably not that easy. As most of us know, Timber populates the post object with all meta values as properties, so that you can use it directly:

```twig
{{ post.my_acf_field }}
```

However, ACF filters are not applied by default (I also only realized this today). Timber reads the values directly from the database. If you want to have filters included, you need to do `{{ post.get_field('my_acf_field') }}`. That’s why for most fields that are only text based, accessing the field through simple dot notation works well. If we have more complex fields like repeater and flexible content fields, it doesn’t. The `get_field()` function populates the whole field, included nested fields inside repeaters. Same for flexible contents.

So actually, the most proper way to go would be to access all the field values through `get_field()` (or you could also use `meta()`).

I assume the reason why Timber doesn’t run `get_field` on all the meta fields is because not all meta fields are ACF fields. There are a lot of other fields written by WordPress core or other plugins.

**Could we identify ACF fields?**

To prepare all ACF fields, we would have to identify which meta fields are ACF fields. ACF writes two fields into the database:

- The field name with the value, e.g. `repeater`
- The field name with an underscore as a prefix together with the field identifier, e.g. `_repeater`

Now one could think that we could easily detect an ACF field if we could check…

- If the field doesn’t start with an underscore
- If a field exists that has the same name, prefixed with an underscore and where the value starts with `field_`

It starts to become a little harder if you look at how ACF saves a repeater field (with field name `rep`:

![](https://cloud.githubusercontent.com/assets/2084481/26313778/3859e0f4-3f0c-11e7-9b78-7205738fe141.png)

And now consider that some people use namespaced fields, e.g. `front_topics_title`, `front_topics_image`, `front_topics_repeater`. How could we know which fields we need to include for `get_field` and which not? Do we know if and how people use numbers in their field names?

And now consider a nested repeater:

![](https://cloud.githubusercontent.com/assets/2084481/26313826/5e44077c-3f0c-11e7-953f-ee4c6a5574b2.png)

A naming convention would work better here, but would you then want field names prefixed with `acf` in your template files? And doesn’t everybody already have a pretty opinionated naming convention for their fields?

**Tell Timber which fields to populate**

A solution I could think of would be to provide Timber with a list of meta field names that it should populate through `get_field`, maybe through a new method on the Post class?

```php
$post = Timber::get_post();
$post->populate_fields( array( 'list', 'of', 'field', 'names' ) );

$context['post'] = $post;
```

**Comment by gchtr** [comment]
Looks like this issue has become stale. Using `{{ post.meta() }}` will be the recommended way to access meta values in Timber 2.0, including ACF support. I’m closing this.

**Comment by Google-api-js-client** [comment]
Nailed it https://pinemarcos.github.io/leuan/
