### ISSUE TITLE
TimberSite class missing

### ISSUE THREAD

**Issue by szepeviktor** [timber/timber#1419]
Could it be that `TimberSite` is missing?

There is only `lib/Site`.

**Comment by gchtr** [comment]
Short answer: No.

In Timber 1.0.0-rc3, namespaced classes were introduced. `Site` sits in the namespace `Timber`, so that you can do

```php
<?php

use Timber\Site;

$site = new Site();
```

instead of

```php
$site = new TimberSite();
```

For backwards compatibility, `TimberSite` acts as an alias for the `Site` class. See the `backwards_compatibility` method, which adds aliases for all other classes, too: https://github.com/timber/timber/blob/master/lib/Timber.php#L83.

**Comment by szepeviktor** [comment]
Thank you!

I was not aware of that change.
