### ISSUE TITLE
arguments from index.php on antoher sites ex: front-page

### ISSUE THREAD

**Issue by lupik2** [timber/timber#1424]
hi! i have big problem with arguments on my site.
i made this on my index.php
```
$twigcontent['header_widget_1'] = Timber::get_widgets('header-widget-1');
$twigcontent['header_widget_2'] = Timber::get_widgets('header-widget-2');
$twigcontent['header_widget_3'] = Timber::get_widgets('header-widget-3');
```
my problem is with **range**

problem is : i cant use them on front-page.
but i using block like this:

```
    {% extends "index.twig" %}

    {% block main %}
     //front page content
    {% endblock %}

```

what can i do in this situation?

**Comment by lupik2** [comment]
help

**Comment by gchtr** [comment]
Hey @lupik2 

Next time it would be better to ask a question like this in the [Gitter chat](https://gitter.im/timber/timber) or on [Stackoverflow, tagged with `timber`](https://stackoverflow.com/questions/tagged/timber). You normally get a quicker answer 😊.

Could you give us some more information?

- What do you mean with: My problem is with **range**?
- What do you want to do exactly? Do you want to display your widgets on the front page?
- Can you show us how your complete `index.php` looks like?
- Which version of Timber are you using?

**Comment by lupik2** [comment]
my index.php : http://wklej.org/hash/eeab46a2547/

in index.twig i made for loop to write styles and on index page everything is fine but for example in post page styles doesnt work, single.twig:
```    {% extends "index.twig" %}

    {% block main %}
     //post content
    {% endblock %}
```

**Comment by corygibbons** [comment]
@lupik2 It's likely because you have a `single.php`, `front-page.php`, or similar file that's taking priority over your `index.php` ([template hierarchy docs](https://developer.wordpress.org/themes/basics/template-hierarchy/)).

`index.twig` rendering does not necessarily mean that it went through `index.php`.

For conditionally loading scripts/style you should look into `wp_enqueue_style()`([docs](https://developer.wordpress.org/reference/functions/wp_enqueue_style/)) and `wp_enqueue_script()`([docs](https://developer.wordpress.org/reference/functions/wp_enqueue_script/))
