### ISSUE TITLE
Timber\Menu() returns default menu when using non-existent menu slug as parameter

### ISSUE THREAD

**Issue by onnimonni** [timber/timber#1440]
### Expected behavior
If I try to create a menu item with non-existent menu slug like here:
```php
<?php
// Get non-existent menu item
// Real menu slug was 'mobile'
$context['mobilemenu'] = new Timber\Menu("mobilemenu");
```

I would want to see error or no menu or a notice in the error log.

Relevant lines are here:
https://github.com/timber/timber/blob/4d19fa9bba16412bb012280cac714bdfb6be550d/lib/Menu.php#L82-L100

### Actual behavior
Current implementation just silently returns the default menu which makes debugging menu errors harder.

### What version of WordPress, PHP and Timber are you using?
php7.1, WP 4.7.5

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Composer

**Comment by chrisgherbert** [comment]
I think this is expected behavior (to match WordPress standard behavior), but I absolutely hate it.

**Comment by shaneoliver** [comment]
Conditionally add to context when the menu exists
```php
if( has_nav_menu( 'mobilemenu' ) ) {
    $context['mobilemenu'] = new Timber\Menu("mobilemenu");
}
```
Check the menu exists on the context before rendering
```twig
{% if mobilemenu%} 
   {% include "path/to/menu.twig" with {'menu': mobilemenu.get_items} %}
{% endif %}
```

**Comment by ozanyolyapar** [comment]
Anti-pattern like behavior. Documentation says the following:

> Or pass nothing. This is good if you have only one menu. In that case Timber will just grab what you got.

Well, this is not okay. I got 8 contextual menus on a complex site. There is possibilities like @shaneoliver pointed out, but it is neither documented if the slug doesn't exist, nor it behaves like expected from an API as a dev.

**Comment by nakashu** [comment]
I am willing to make an PR, if it will be clarified if the core team wants to add this change.
Personally I think current behavior is incorrect and can make bug in production if a needed menu is deleted - suddenly showing first default one.

Possible solutions
- add another option to constuctor `new Menu('slug', ['strict' => true])` or `mustExist`
- change current behavior to return Menu without items / empty

**Comment by jarednova** [comment]
@nakashu — thank you so much for running that by before diving into a PR (nothing pains me more than saying "no thank you" to an otherwise well-meaning PR). 

The pattern you describe is 👍 — the only caveat I'd add is that as much as possible we try to use existing WP names or patterns (so `mustExist` => `must_exist`). We can always quibble over the exact words once the basics are down, but the overall architecture you describe (with an options array instead of an infinite chain of arguments) is exactly what we're transitioning to more and more so it gets my vote. 

Thanks for chiming in and taking that on!
