### ISSUE TITLE
[feature request] Symfony VarDumper

### ISSUE THREAD

**Issue by nlemoine** [timber/timber#1443]
### Actual behavior

Timber is using the default Twig dumper to print variables. Basically PHP `var_dump`. It does the job but is really lacking some visual enhancements. 
![capture d ecran 2017-06-08 a 18 08 18](https://user-images.githubusercontent.com/2526939/26938809-a241a86e-4c75-11e7-9de5-7dfb2854b0bd.png)

You can get something a little better by [adding some `pre` tags or viewing source](https://github.com/timber/timber/issues/1353) but this is not very handy. 

### Expected behavior

Would you consider adding Symfony VarDumper component?
![capture d ecran 2017-06-08 a 18 07 43](https://user-images.githubusercontent.com/2526939/26939090-76617868-4c76-11e7-8c34-d857c7fa13f8.png)

It could be as a default or to be enabled option. 

Last version requires PHP 7+ but 2.8 (which still does a pretty decent job) only requires PHP 5.3.9+.

What do you think?

**Comment by dseidl** [comment]
dont think this should be included by default. this is a dev dependency, you can always require it in your projects.

**Comment by gchtr** [comment]
Very good idea to make debugging easier! I checked it out, it doesn’t require a lot of work to add this to your stack.

**Add Symfony VarDumper as a Composer dependency**

```
composer require symfony/var-dumper
```

**functions.php**

Register `dump` function in Twig:

```php
/**
 * Customize Twig
 * 
 * @param Twig_Environment $twig
 * @return $twig
 */
add_filter( 'timber/twig', function( \Twig_Environment $twig ) {
    $twig->addFunction( new \Twig_SimpleFunction(
        'dump',
        [ 'Symfony\Component\VarDumper\VarDumper', 'dump' ]
    ) );
} );
```

You can give the function a name you want. For example, you could name it `debug`:

```php
$twig->addFunction( new \Twig_SimpleFunction(
    'debug',
    [ 'Symfony\Component\VarDumper\VarDumper', 'dump' ]
) );
```

I agree with @dseidl that this shouldn’t be included by default. But I’ll add it to the **Debugging Guide** in the documentation.

**Comment by nlemoine** [comment]
Thanks for the feedback @gchtr 

I should have mentioned I already developed the extension (basically copied from [here](https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Twig/Extension/DumpExtension.php)). I'm using it in all my WP/Timber projects. 

Just wanted to know people feeling about this, I believe this could be a tiny but useful improvement. I still think VarDumper extension should be included by default because you can't seriously debug something with `var_dump`. 

But it's ok if you don't feel that way 😉  

I'll add my vardumper extension to packagist within the next weeks. I'll post it here if some people are interested or if you want to add it in the docs.

**Comment by gchtr** [comment]
I agree with you that with `var_dump` only, it’s impossible to debug anything seriously. However, VarDumper is not the only option that people can use for debugging.

In our development setup, we have xDebug enabled, which makes `var_dump()` much nicer to read. Here’s an example:

![](https://user-images.githubusercontent.com/2084481/28522724-7b6320d8-7079-11e7-939d-b3f3748af034.png)

If you’re wondering why some values are hidden behind `…`: xDebug also comes with options for how many array children and object properties you’ll want to display.

For in-depth debugging, we use xDebug in combination with the [Debugging features provided in PHPStorm](https://www.jetbrains.com/phpstorm/features/debugging_testing_profiling.html). It basically has the same feature included inside the IDE that VarDumper provides. We can set breakpoints and walk through the code step by step, etc.

So in the end, I think it’s more a question of preference of what tool you’ll want to use for debugging.

I think the best solution would be if Timber provides the compatibility for VarDumper, so that people who want to use it only have to run `composer require symfony/var-dumper` (or your package) and everything else will work. In that light, I think your class might be a very valuable addition and I’d love to see how you solve it!

**Comment by nlemoine** [comment]
@gchtr Sorry for the late answer, just came back from holidays a few days ago. 

Thanks a lot for the detailed xdebug description. I'm using Sublime Text but will definitely have a look at your setup. 

In the meantime, you can check the vardumper extension for Timber here: https://github.com/nlemoine/timber-vardumper-extension

As I said above, it's basically a copy the dump extension from Symfony minus the tokens parsers (they are useless IMO). 

I did not publish anything yet to packagist so you'll have to "manually" declare the repository. Any feedback are welcome.

**Comment by gchtr** [comment]
@nlemoine Never be sorry for a late answer because of holidays 😎.

I checked out your extension, very nice! It’s really just plug-in and go and definitely easier than to set up xDebug. I like that it’s only hooked when `WP_DEBUG` is true. If you add this to packagist, I’ll add this to the Debugging guide of the documentation. And of course to the [Related Projects](https://github.com/timber/timber#related-projects) section of the Readme.

**Comment by nlemoine** [comment]
@gchtr The extension is finally available on Packagist: https://github.com/nlemoine/timber-dump-extension

```
composer require hellonico/timber-dump-extension
```
I extracted the Twig dump extension in another repository/package.

**Comment by gchtr** [comment]
Very nice! It works out of the box, like magic 🎉!

I just created the pull request to add it to the documentation and the related projects section in the Readme.

**Comment by nlemoine** [comment]
Great, thanks for adding this to the docs! 👍
