### ISSUE TITLE
Timber resize path incorrect when using roots/soil relative urls

### ISSUE THREAD

**Issue by Drooooopy** [timber/timber#1480]
The resize filter returns incorrect paths with our setup. This worsened since 1.3.2. We use the relative URL option from roots/soil. 

Our setup looks like this:

- wp (contains the WordPress core files)
- wp-content
- index.php
- wp-config.php

Timber >= 1.3.0 && < 1.3.2 always returned the path to the full image. The result was the same with or without the resize filter. 

Since 1.3.2 when visiting http://domain.tld/cases/ the resize filter returns:

http://domain.tld/cases/-content/uploads/case_featured-1920x1080-c-default.png

I notice 2 things: 

- The current URL is used instead of the site URL
- wp is removed from wp-content.

The expected URL would be:

http://domain.tld/wp-content/uploads/case_featured-1920x1080-c-default.png

The paths are set using the WP_CONTENT_DIR and WP_CONTENT_URL constants in wp-config.php. We do not have other issues with this setup and the resize filter works perfectly when we downgrade Timber to 1.2.* or 1.1.* with the relative URL option enabled in Soil.

Turning off relative URLs fixes the paths in 1.3.2+.

### What version of WordPress, PHP and Timber are you using?
WordPress 4.8, PHP 7.0, Timber 1.3.3

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Composer

**Comment by grantcodes** [comment]
Digging this one up again because I managed to work around this with a couple of filters:

```php
add_filter( 'timber/image/new_url', function ( $url ) {
  if ( strpos( $url, '-content/uploads' ) === 0 ) {
    $url = str_replace( '-content/uploads', '/wp-content/uploads', $url );
  }
  return $url;
} );
add_filter( 'timber/URLHelper/url_to_file_system/path', function( $path ) {
  if ( strpos( $path, '/wp-content/uploads' ) === 0 ) {
    $path = str_replace( '/wp-content/uploads', '/../wp-content/uploads', $path );
  }
  return $path;
} );
```

Not ideal, but works for me.

**Comment by twentyfortysix** [comment]
I don't know how the soil works exactly, but hit similar problem on roots/bedrock (I guess it has similar roots)
since Timber ^2.0 the images where not found with errors in log like
`[11-Apr-2022 17:00:44 UTC] [ Timber ] Error loading /app/uploads/2022/03/BN....`
My guess was that the path is constructed wrongly therefore Timber cannot find them (looks like it searches in the folder root not in web root).

My solution to that was to set the
`Config::define('UPLOADS', '../app/uploads' );`
in bedrock/config/application.php.
Then I realized that the path is taken from the wp>media settings.. and sure enough changing the /app/uploads to ../app/uploads does the same trick like the forced config definition.

Since then the images are located right and the resize works again!

**Comment by Levdbas** [comment]
Third party related. Going to close since there are multiple workaround noted.
