### ISSUE TITLE
Default CPT classmap for resolving

### ISSUE THREAD

**Issue by dseidl** [timber/timber#1481]
**Feature Request:**

A filter, where i can set a default classmap for the `$PostClass` for all get_posts would be awesome.
Furthermore, when acf relationship fields are fetched the classmap is used too.

As it is now, i have for any cpt a custom Class wich extends the timber post class. I have to manually build up the posts for relationship fields etc. all the time, because i cant set a classmap - then all posts are instances of timber post instead of my own.

**Comment by corradomatt** [comment]
I do something of a class map in my own project. We have a Class that is basically a wrapper for Timber. Basically we call ```Lumber::getSingle();``` or ```Lumber::getArchive();``` which does a bunch of setup for us (like pulling theme options among other things) and then checks the post type to map the post object to one created which extends ```Timber\Post```.

These child classes do all of the object extension for us. It works very well and our ```Lumber``` class is very small. It's basically just syntactic sugar. I have wondered if it made sense for Timber to offer a map for Class -> Post_Type sort of interface.

**Comment by dseidl** [comment]
@corradomatt sounds neat!
Can you make a gist out of the class? or show the code somehow?
I understand that helper functions, but (if you work with acf) how are you handling the relationship fields etc. There you get the default TimberPost. For that a filter would be awesome. Timber already has a classmap functionality.

**Comment by corradomatt** [comment]
ahh...didn't realize I could pass a class map instead of a class name as a string @dseidl -- that will help me streamline my class.

There's really not much to my class. We're not using ACF much and haven't used relationship fields or anything more advanced than a standard text field...but I would assume that if there is login built into TimberPost for ACF support, it should still work for us.

The key is that our custom post objects are extending TimberPost. In our case, we have a class called `PostContract` that is an abstract class. This class extends TimberPost and provides some logic that all of our custom Post Objects should share. Then each custom Post object extends our `PostContract` like so....

```php
<?php

namespace hji\blvd\abstracts;

use Timber\Post;

abstract class PostContract extends Post
{
    public $schema;

    public function __construct($pid = null)
    {
        parent::__construct($pid);
    }

    // some custom stuff....
}
```

```php
class Something extends PostContract
{
    public $PostClass = 'our\namespace\Something';

    public function __construct($pid = null)
    {
        parent::__construct($pid);
    }
}
```

The whole thing works very well. We are able to add custom methods and properties to our data models in this way. The one tricky part is that we sometimes have data we don't want exposed on archive pages...only for single post pages. Since we want to use the same data model for both archive pages and single pages, we have some conditionals to exclude certain properties from the archive page version of the model.

**Comment by dseidl** [comment]
just to recap: the filter i was searching for already exists.
it is named `Timber\PostClassMap`.

it would be awesome to have all filters documentated. maybe if i have some time i could start writing that down.

this ticket can be closed
