### ISSUE TITLE
ACF dot notation unavailable. "custom" array works instead

### ISSUE THREAD

**Issue by alevroub** [timber/timber#1549]
According to the documentation, data saved by ACF is available via dot notation: `{{ post.custom_field }}`. Is it implied that this only works for plain text fields?  From what I've seen, a custom field that returns another simple value, like an integer, is not accessible through `{{ post.custom_field }}` but rather `{{ post.custom.custom_field }}` where the value is converted to string format. Am I missing something? This array could very well be part of the same TimberPost object allowing to return a (parsed) integer using the same syntax. My main issue is that it adds a third method to get ACF values:

```
{{ post.custom_field }}
{{ post.custom.custom_field }}
{{ post.get_field('custom_field') }}
```

**Comment by gchtr** [comment]
Hey @alevroub 

Totally agree with you that it can be confusing and that it can be improved in the docs. I’ve already marked this on my list of things to clarify in the docs.

Timber saves **all the meta fields it can find** in the database for a post as **properties of the `Timber\Post` object**.

Additionally, it saves all of these custom values under the `custom` property of the post object. This was introduced in https://github.com/timber/timber/commit/cdb33d0ff0332fbb00a18024354a6046ba2698e6#diff-fee7335b9faad042bcea4c974bc941ebR248. I don’t know the exact reason behind this, maybe @jarednova knows more. If I had to guess, I’d say it’s because Jared wanted to make it as easy as possible to access custom values in Twig while still having a reference of which values are custom field values.

All of these values are directly taken from the database, so if you have values that come from ACF fields, this might be raw data that’s hard to work with. E.g. for Repeater and Flexible Content fields, you get a bunch of fields that are indexed, but not in an array format to work with ((`flexibles_3_text`, `flexibles_4_image` and so on). Same if you have a relation field where you select a post in the backend. In that case you’d only get the post ID instead of the whole post object.

And that’s why the `get_field()` method exists in `Timber\Post`. When you get field values through that method, all relevant ACF filters are applied and you will get the values as you would expect them. What this means for you:

- If you have simple text fields, you can access the property directly through `{{ post.custom_field }}`.
- If you have more complex fields that need to be processed first (e.g. WYSIWYG fields that need `the_content` filter to be applied, Repeater fields, Flexible Content fields), you should use `{{ post.get_field('custom_field') }}`.

Because Timber doesn’t know which meta fields are actual ACF fields and which fields might come from other plugins, it doesn’t use `get_field()` for all custom fields, which is very reasonable. That’s why you have to call `get_field` manually.

I hope this clears things up.

> From what I've seen, a custom field that returns another simple value, like an integer, is not accessible through {{ post.custom_field }} but rather {{ post.custom.custom_field }} where the value is converted to string format.

What is the name of your custom field where this happens? It seems strange to me that an integer would be converted to a string when it’s added to the `custom` property.

**Comment by alevroub** [comment]
That makes complete sense. I think the difference and use of the dot notation and get_field method is clear, it's only the custom property that seems inconsistent somehow. The ACF field in question is an image field, `preview`, that returns an `Image ID` with the value `388`

```
{{ dump(page.preview) }}
{{ dump(page.custom.preview) }}
{{ dump(page.get_field('preview')) }}
```
returns
```
NULL
string(3) "388"
int(388)
```
A `number` field with the value `12345` is more consistent however, and will return

```
string(5) "12345" 
string(5) "12345" 
string(5) "12345"
```
for all three methods.

**Comment by gchtr** [comment]
Okay, in that case it’s clear why this happens:

There’s a method [`preview`](https://timber.github.io/docs/reference/timber-post/#preview) on `Timber\Post`. The value `NULL` that you get is probably the output of that method. Because in Twig, there’s no difference between `$page->preview` and `$page->preview()`, it’s probably the method that gets executed first. So you don’t actually get the expected field value.

And that’s actually another problem that is not documented yet and that I’ve also run into myself: **You shouldn’t name a custom field the same as an already existing method or property of `Timber\Post`.** This is actually quite a big problem, because it leads to unexpected results like your. I think you shouldn’t always have to check if the custom field name you want to use is a reserved name. For the future, I’d say it would be better to not import all properties directly to a post but have them in a `custom` or `c` property only.

There are workarounds:

- Use `get_field()` or use the value inside the `custom` property.
- Prefix your custom field names. E.g. `c_preview`. You’d have to do this only for first level fields. Nested field names inside Repeaters or Flexible Contents could work without a prefix.

**Comment by alevroub** [comment]
Personally I think it would be more feasible to have all ACF fields put under the `custom` property to avoid issues based on pure naming conventions. In any case, that was simpler than I thought. Thanks for clearing that up!

**Comment by drzraf** [comment]
Wow that `post.custom.*` saved my day!
A -dev had named a field `date`, and `get_field()` would only return the formatted value (that I could not change).
Without `post.custom.date` returning the raw ACF value I would have been locked!

This should be documented in https://timber.github.io/docs/guides/acf-cookbook/.
