### ISSUE TITLE
new TimberPost() - post status definition

### ISSUE THREAD

**Issue by twentyfortysix** [timber/timber#1551]
Is this a support or usage question? Please post to [StackOverflow](http://stackoverflow.com/questions/tagged/timber) using the Timber tag

### Expected behavior
When I call: 
`new TimberPost()`

I expect to have a chance to control the post status, or else the post should be visible only if it has status "publish" by default.

I Also tried 
`new TimberPost(4830, 'publish');`

as that is what I understand should be available by the spec on https://timber.github.io/docs/reference/timber-post/#overview

### Actual behavior
...unlike now, when the post is returned no matter if it is draft or in trash.

### What version of WordPress, PHP and Timber are you using?
WP 4.8.1 , Timber 1.4.1

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
manual ftp upload

**Comment by gchtr** [comment]
Hi

The properties that you see when in the reference are values that you can access on a `Timber\Post` object.

![bildschirmfoto 2017-09-13 um 17 18 58](https://user-images.githubusercontent.com/2084481/30385545-cac8b7f4-98a7-11e7-9f09-0a9ccb0d630d.png)

When you instantiate a new `Timber\Post` object with `new Timber\Post()`, you can pass [only one argument](https://timber.github.io/docs/reference/timber-post/#construct) and you’ll get a post object with all the data in return.

> I expect to have a chance to control the post status, or else the post should be visible only if it has status "publish" by default.

You can’t really control a post like you’d expect here. But you can check the properties after you’ve instantiated an object. So if you want to check if a post is public through the `post_status` property, it could work like this:

```php
<?php
$post = new Timber\Post( 4830 );

// Will display the status of your post
echo $post->post_status;

// You can check the post status in a conditional
if ( 'publish' === $post->post_status ) {
    // Do something here
}
```

For this, you could also use [`get_post_status`](https://codex.wordpress.org/Function_Reference/get_post_status) directly:

```php
<?php

if ( 'publish' === get_post_status( 4830 ) ) {
     // Do something
}
```

If you first get an array of posts through `Timber::get_posts()`, you can always pass the `post_status` argument, so that you only get posts with the desired post status:

```php
<?php
$args = array(
    'post_type' => 'your_post_type',
    'posts_per_page' => -1,
    'post_status' => 'publish',
);

$posts = Timber::get_posts( $args );
```

Like this, you can control the post status, kind of.

In which template file do you use `new TimberPost( 4830 );`. Is it a template file that displays a single post or an archive page? Do you use this inside a loop?

**Comment by twentyfortysix** [comment]
The post I want to get is an extra post outside the current post scope. 
In my case it is a banner. And so I was simply puzzled why I see the post/banner no matter its post status. It is just weird to get post of any status like hidden or deleted by default.

If that is desired behaviour, than I can live with it and go around by get_posts with arguments.

**Comment by gchtr** [comment]
Yeah, this is the default behaviour in WordPress.

**Comment by marciojc** [comment]
Hey, @twentyfortysix, if you are happy to the feedback please close the issue.

**Comment by twentyfortysix** [comment]
not happy .) , but you can close it, as it the problem is in Wordpress not in Timber. As it seams.
