### ISSUE TITLE
Sticky posts count - posts_per_page

### ISSUE THREAD

**Issue by gritdigital-mibu** [timber/timber#1558]
Hi all,

So TIL WordPress has https://codex.wordpress.org/Sticky_Posts ...only a few years behind!

```
$args = [
    'post_type' => 'post',
    'posts_per_page' => 6
];
$timber_posts = \Timber\Timber::get_posts($args);
var_dump(count($timber_posts), count(get_posts($args)));
die();
```

```
int(7) int(6)
```

You'll notice the count is different despite the `$args` being the same.

WordPress 4.8.2
timber/timber 1.5.0

Cheers

**Comment by iign** [comment]
I can reproduce this issue. 
I'd submit a PR but sniffing through the code didn't get me anywhere :/

**Comment by hugw** [comment]
The behavior is correct, sticky posts don't enter the count.
If you have 3 sticky posts and had set up 10 posts per page, it will return 13 a total.

The reason why `get_posts` return the exact number set on `posts_per_page` its because it ignores sticky posts by default.

Take a look here https://core.trac.wordpress.org/browser/tags/4.8/src/wp-includes/post.php#L1685.

**Comment by gritdigital-mibu** [comment]
@hugw Cheers. Surely they should have the exact same behaviour and return the same results given that they have the same arguments?

**Comment by hugw** [comment]
Arguments are the same, but despite the method's names are `equal`, their functionality is different.

If you really which to compare behavior, this is the right way: 

```
$args = [
  'post_type' => 'post',
  'posts_per_page' => 6
];

$posts = new WP_Query;
$timber_posts = \Timber\Timber::get_posts($args);

var_dump(count($timber_posts), count($posts->query($args)));
```

Return is `int(7) int(7)`

**Comment by gritdigital-mibu** [comment]
@hugw Understood, cheers.
