### ISSUE TITLE
Pass variable from template.twig to base.twig to include.twig

### ISSUE THREAD

**Issue by adamwright32** [timber/timber#1564]
I have a navigation that requires a different class depending on the template. I want to be able to set this in the template or page.twig and then pass it back down to and include.twig that is included in base.twig.

Can this be done?

**Comment by marciojc** [comment]
Why don't you create the variable at `add_to_context`?  This way the variable is accessible in all twig files.

**Comment by adamwright32** [comment]
@marciojc i'm new to twig and php, could you show me an example please of how and where to do this?

**Comment by adamwright32** [comment]
@marciojc i've tried that way and it doesn't work, here is my setup

functions.php

```
function add_to_context( $context ) {
		$context['navColorClass'] = "c-navbar--light";

		return $context;
	}
```

base.twig

```
{% block html_head_container %}

{% include 'html-header.twig' %}
	{% block head %}
	{% endblock %}
	</head>
{% endblock %}
	

<body>
    {% include 'navigation.twig' %}
    <div id="js-scrollbar">
        <main id="main-content">
            <article>
        	    {% block content %}

        		{% endblock %}
        		</article>
            </main>
            <footer id="footer">
                {% include 'footer.twig' %}
            </footer>
        </div>

         {% include 'globaljs.twig' %}
        {% block javascript %}{% endblock %}
        {{ function('wp_footer') }}
        
	</body>
</html>

```

navigation.twig 

`<nav class="c-navbar {{ navColorClass }}" id="js-navbar">`

Insights.php which is custom page

```
<?php

/*
* Template Name: Insights
 * Description: List of article, ebooks, and quickviews
*/


$context['navColorClass'] = "sauce";
$context = Timber::get_context();
$context['post'] = new TimberPost();

$args = array(
    'paged' => 1,
    'post_status' => 'publish',
    'posts_per_page' => 11,
    'post_type' => array(
        'article',
        'ebook',
        'quickviews'
    ),
    'orderby' => 'date',
    'order' => 'DESC'
);

$totalargs = array(
    'post_status' => 'publish',
    'posts_per_page' => -1,
    'post_type' => array(
        'article',
        'ebook',
        'quickviews'
    ),
    'orderby' => 'date',
    'order' => 'DESC'
);

$context['articles'] = Timber::get_posts($args);
$context['total'] = Timber::get_posts($totalargs);


// get values from ACF options page
$context['options'] = get_fields('options');

Timber::render('insights.twig', $context);



?>

```

I want to be able to set navColorClass in insights.php and that update the value in the navigation.twig

**Comment by marciojc** [comment]
Hi @adamwright32, since this is a support question I'd recommend posting your question to StackOverflow:

[https://stackoverflow.com/questions/tagged/timber(https://stackoverflow.com/questions/tagged/timber)

but Insights you are overwriting the context variable, change the order.

`$context = Timber::get_context();
$context['navColorClass'] = "sauce";`

**Comment by adamwright32** [comment]
@marciojc yes i am, i want to change the value in insights and want that value to show in navigation.twig

**Comment by marciojc** [comment]
@adamwright32 if you want to change the value, change the order as my example.

**Comment by gchtr** [comment]
Alright, let’s break this down. You have a function like this, where you add the `navColorClass` to the context:

```php
function add_to_context( $context ) {
    $context['navColorClass'] = "c-navbar--light";

    return $context;
}
```

But you also need to use `add_filter`, so that the function will be called at the right time:

```php
add_filter( 'timber/context', 'add_to_context' );
```

Be aware, that when you use this filter, you will set `navColorClass` for all your template files where you call `Timber::get_context()` before rendering it through a Twig file.

You say that you want to set `navColorClass` in **insights.php** only, so the `timber/context` filter might not be what you’re looking for.

You also tried it a different way, by setting `navColorClass` in **insights.php**. This doesn’t work because when you first do 

```php
$context['navColorClass'] = "sauce";
```

and then right after that you’ll do

```php
$context = Timber::get_context();
```

then `$context` will always be the default context. Your value `navColorclass`will be overwritten. Before you do anything to context in a template file, you should always initialize it with `Timber::get_context()`.

I know, getting the concept of a "Context" might be a little confusing at first. Basically it’s an array of values that you pass to your Twig files to display. `Timber::get_context()` sets a lot of useful variables for you, so you don’t have to set them all by yourself.

I hope this clears things up. Good luck!

**Comment by adamwright32** [comment]
Thanks. got it working. in the navigation controller i was calling` Timber::get_context() ` in the navigation.php which was overriding my navColorClass from my template files.

**Comment by gchtr** [comment]
Great that you figured it out. I’m going to close this then.
