### ISSUE TITLE
Timber\MenuItem->thumbnail() not working with "real" nav menu items

### ISSUE THREAD

**Issue by gchtr** [timber/timber#1572]
In `Timber\MenuItem`, there’s a `thumbnail` method, which can get the featured image of a post associated with a menu item.

The method can retrieve featured images for menu items that were initialized in page menus. This means when `Timber\Menu` is initialized without any parameters. However, when initializing a menu with a parameter so that Timber gets the menu items from a registered nav menu, then it won’t work, because the `thumbnail` method always uses the `ID` property of the post:

https://github.com/timber/timber/blob/b8d8649d21b15fbd8f29b6aed56eaed4f2b5013f/lib/Post.php#L1331

For posts of post type `page` and others, this works fine, but for posts of post type `nav_menu_item`, the `ID` will be the ID of the menu item post, not the associated post. The associated post is saved in the `object_id` property instead.

### Steps to reproduce behavior

The current unit test works, because the menu is initialized as a page menu:

https://github.com/timber/timber/blob/b8d8649d21b15fbd8f29b6aed56eaed4f2b5013f/tests/test-timber-menu.php#L55

Here’s an additional test that fails:

**test-timber-menu.php**

```php
function testNavMenuThumbnails() {
	require_once( 'test-timber-image.php' );

	add_theme_support( 'thumbnails' );
	self::setPermalinkStructure();

	$menu_term = self::_createTestMenu();
	$menu_items = wp_get_nav_menu_items( $menu_term['term_id'] );

	// Add attachment to post
	$pid = $menu_items[0]->object_id;
	$iid = TestTimberImage::get_image_attachment( $pid );
	add_post_meta( $pid, '_thumbnail_id', $iid, true );

	// Get menu
	$nav_menu = new Timber\Menu( $menu_term['term_id'] );

	$str    = '{{ menu.items[0].ID }} - {{ menu.items[0].thumbnail.src }}';
	$result = Timber::compile_string( $str, array( 'menu' => $nav_menu ) );

	$this->assertEquals( $menu_items[0]->ID . ' - http://example.org/wp-content/uploads/' . date( 'Y/m' ) . '/arch.jpg', $result );
}
```

### Possible solutions

I see different approaches to this:

- Add a parameter to the `Timber\Post->thumbnail()` method that can overwrite the default post ID and call it with the right ID from `Timber\MenuItem->thumbnail()`.
- Check for the existence of an `object_id` inside the `Timber\Post->thumbnail()` function. However, this could lead to unexpected behavior when a custom field named `object_id` exists.
- Deprecate the function? Is it maybe an edge case, because it didn’t work for normally registered menus anyways?

### What version of WordPress, PHP and Timber are you using?

WordPress 4.8.2, PHP 7, Timber@master

**Comment by jarednova** [comment]
Thanks @gchtr — this is next up in my queue!

**Comment by jarednova** [comment]
Alright I did some digging and here's what I found. The fix was slightly different than expected. The test you posted relied on the order from `wp_get_nav_menu_items`

```php
$menu_items = wp_get_nav_menu_items( $menu_term['term_id'] );
```

... however, this function just returns an ordered menu items and doesn't order for nesting. After resolving that, things ... still didn't work. That's because this function in `MenuItem`...

https://github.com/timber/timber/blob/master/lib/MenuItem.php#L437-L443

... relies on `master_object` which isn't set in the `wp_postmeta` table. Instead, for those we need to retrieve from the `get_master_object` method...

https://github.com/timber/timber/blob/master/lib/MenuItem.php#L156-L160

... which breaks the Page menu test. Still awake? Then moving some stuff from the (old) thumbnail function into `get_master_object` allows us to reliably retrieve the master object. So now, all tests pass!

That said, it's fucking stupid. As you note:

> Deprecate the function? Is it maybe an edge case, because it didn’t work for normally registered menus anyways?

The fact that this has been "broken" for years tells me that it's not used and shouldn't add to function bloat. I think a reliable method to retrieve the master object that a `menu_item` relates to is sufficient to get whatever meta data a dev wants. Further work to "simplify" actually adds complexity as we see here. I vote in #1577 to deprecate `thumbnail` and remove in 2.0, what say you?

**Comment by gchtr** [comment]
Oh, alright! I didn’t even realize what `get_master_object()` is used for. Because it’s marked as internal, I didn’t look at it more closely yet. I too think that with that method, it shouldn’t be very hard to get the featured image of the linked post.

So, I’m very much in favor of deprecating the the `thumbnail()` method. And I propose that we make the `get_master_object()` method public in the docs and add the thumbnail use case as a code example (with `@example`).

**Comment by jarednova** [comment]
sounds good, do you have any ideas for the name? is `master_object` clear enough or can you think of something that'd be more self-evident? 

`{{ item.master_object.thumbnail.src }}`

Open to @gchtr or anyone else's ideas for the best name
