### ISSUE TITLE
Version 2.0 Running List

### ISSUE THREAD

**Issue by jarednova** [timber/timber#1580]
A bunch of things are popping in my head to do for version 2.0. I'm opening this thread as a running list

x Consider default escaping strategy
x Remove deprecated functions
x Remove routes
x Remove import vs. on-demand meta

### General
- [x] Remove Routes @jarednova
- [ ] remove deprecated functions 
- [x] Streamline filter names for `timber/filter_name` @gchtr 
- [x] Deprecate `old_filter_names` @gchtr 
- [x] Remove context argument when calling {% do action %} (#1528). @gchtr
- [ ] Apply Timber Coding Standards
- [x] Deprecate custom debugging methods @jarednova
- [x] Add new Timber\Attachment class for easier handling of attachments (which can also be PDFs or other non-image file types) with methods for getting the filesize or the path/URL. Timber\Image could just be extending this class, adding all the functionality required for image files. @gchtr 
- [x] Replace instances of Timber::get_posts() with PostQuery and Timber::get_post() with Timber\PostQuery(), 
  - [x] In the code base @gchtr
  - [x] documentation @gchtr
  - [x] and starter theme @jarednova 

### Post
- [x] remove import of custom fields; on-demand meta @jarednova
- [x] remove public `get_` methods @jarednova
- [x] escape data by default @jarednova
- [x] remove deprecated functions  @jarednova
- [x] Streamline filter names for `timber/filter_name` @gchtr 
- [x] Deprecate `old_filter_names` @gchtr 

### Term
- [x] remove import of custom fields; on-demand meta
- [x] remove public `get_` methods
- [x] remove deprecated functions
- [x] Streamline filter names for `timber/filter_name` @gchtr 
- [x] Deprecate `old_filter_names` @gchtr 

### User
- [x] remove import of custom fields; on-demand meta
- [x] remove public `get_` methods
- [x] remove deprecated functions
- [x] Streamline filter names for `timber/filter_name` @gchtr 
- [x] Deprecate `old_filter_names` @gchtr

**Comment by gchtr** [comment]
Some more ideas:

- Streamline filter names used in Timber with `/` as separators instead of `_`. Use [`apply_filters_deprecated()`](https://developer.wordpress.org/reference/functions/apply_filters_deprecated/) for deprecated filters.
- Remove context argument when calling `{% do action %}` (https://github.com/timber/timber/issues/1528).
- Apply Timber Coding Standards, which will be as close to WordPress Coding Standards as possible.

What do you mean with the following item?

> - Remove import vs. on-demand meta

Is it that meta field values are directly imported on an object, which sometimes leads to unexpected behavior, when e.g. a method has the same name as a custom field (https://github.com/timber/timber/issues/1549#issuecomment-329109511)?

**Comment by gchtr** [comment]
Some more things to consider for 2.0:

- Deprecate debugging filters in Twig: https://github.com/timber/timber/blob/e7a2701be4f6d895ae5784787799a5b8f0e40cdb/lib/Twig.php#L208-L213
- Add new `Timber\Attachment` class for easier handling of attachments (which can also be PDFs or other non-image file types) with methods for getting the filesize or the path/URL. `Timber\Image` could just be extending this class, adding all the functionality required for image files.
- Replace instances of `Timber::get_posts()` with `PostQuery` and `Timber::get_post()` with `Timber\Post()`, both in the code base and in the documentation.
- Make it possible to pass the post class that should be used to the constructor `Timber\Post`. For [Timber::get_post()](https://timber.github.io/docs/reference/timber/#get-post), this is possible, but not when using `new Timber\Post()`.

**Comment by jarednova** [comment]
Thanks for these notes @gchtr. I compiled everything in a checklist in the [first comment](https://github.com/timber/timber/issues/1580#issue-265025662). I had a question on the last one...

> Make it possible to pass the post class that should be used to the constructor Timber\Post. For Timber::get_post(), this is possible, but not when using new Timber\Post().

To use a custom post class the way I've always done/recommended is `$post = new My_Custom_Post()` — is this what you're talking about?

**Comment by gchtr** [comment]
> To use a custom post class the way I've always done/recommended is $post = new My_Custom_Post() — is this what you're talking about?

Well, of course! How silly of me 🙈. Must have been a long day when I wrote that on my list initially. But maybe this is a good point to cover in the upgrade guide then.

**Comment by gchtr** [comment]
Alright, while working on some features, I found other things that could be changed/improved:

- Add warnings for all deprecated functions.
- Replace `Timber::get_terms()` and `Timber::get_term()` with `Timber\TermQuery` etc?
- Return something meaningful when no post could be found (https://github.com/timber/timber/issues/1467).
- Deprecate `Timber::fetch()` and its filter `timber_compile_result`.
- Deprecate `Timber::get_pagination` in favor of using the solution provided here: <https://timber.github.io/docs/guides/pagination/>.
- If the `Timber\Term::update()` is deprecated, should `Timber\Post::udpate()` and `Timber\Site::update()` be deprecated as well?
- If `Timber\Term::udpate()` is being deprecated, should `Timber\Integrations\ACF::term_set_meta()` be deprecated as well?
- Move `class_alias` calls in `PostCollection.php` to `Timber::backwards_compatibility()`.

https://github.com/timber/timber/blob/5c3bf78c6249449d09965bb6e3326bed5d1b9af5/lib/PostCollection.php#L103-L104

- Is this a good function name? Could we use `get_comment_count()` or `comment_count()`.
 
https://github.com/timber/timber/blob/5c3bf78c6249449d09965bb6e3326bed5d1b9af5/lib/CommentThread.php#L42-L47

## Create new objects instead of using functions for that

Throughout code and documentation:

- Replace `TimberPost()` with `new Timber\Post()`
- Replace `TimberTerm()` with `new Timber\Term()`
- Replace `TimberUser()` with `new Timber\User()`
- Replace `TimberImage()` with `new Timber\Image()`
- Replace `TimberMenu()` with `new Timber\Menu()`
- Replace `TimberComment()` with `new Timber\Comment()`
- Replace `TimberHelper()` with `new Timber\Helper()`
- Replace `TimberSite()` with `new Timber\Site()`
- Replace `TimberArchives()` with `new Timber\Archives()`
- Replace `TimberURLHelper()` with `new Timber\URLHelper()`

## Streamline custom field methods

There are are currently different method names to retrieve custom meta data for objects. I suggest to use a `meta()` method to retrieve custom meta data for an object and also have the `__get()` method do the same. For this, the following changes would have to be introduced:

- For `Timber\Term`, `Timber\User` and `Timber\MenuItem`, make `__get()` available in documentation. The `__get()` is set in `Timber\Core()`, which is not available in the Reference. Maybe we could also the [`@method` tag](http://manual.phpdoc.org/HTMLSmartyConverter/HandS/phpDocumentor/tutorial_tags.method.pkg.html) for this.
- Rename `get_post_custom()` method to `meta()` for `Timber\Image`.
- Rename `get_meta_fields()` method to `meta()` for `Timber\Comment`.

And maybe, for the special case of `Timber\Site`:

- Add `option()` method for `Timber\Site` to retrieve site options as an alias for `__get()`.

## Use $args for PostPreview

As much as I like the chaining of parameters, it’s a pattern that is currently only used for the post preview (?) and that I fear many people don’t understand, if it’s only used for post previews. A very common pattern for WordPress would be to use an `$args` array in combination with [`wp_parse_args()`](https://codex.wordpress.org/Function_Reference/wp_parse_args). This would make it more WP_Query-like.

```php
function get_preview( $args ) {
    $args = wp_parse_args( $args, array(
        'end'          => '&hellip;',
        'force'        => false,
        'length'       => 50,
        'char_length'  => false,
        'readmore'     => 'Read More',
        'strip'        => true,
        'destroy_tags' => array( 'script', 'style' ),
    ) );

    // …
}
```

I know, a lot of work went into this and I don’t know the complete backstory of how it came to be. I’m just raising this topic with a thought for consistency. Maybe I’m missing something more complex here, though.

Anyways, we need better documentation for this.

**Comment by jarednova** [comment]
@gchtr thanks for these follow-ups. I converted your most recent comment into a checklist and claimed a few that I wanted to work on — please label which you want to claim and then we can work through the others.

To the PostPreview Q: I totally agree w your assessment. I love the chaining, but that might be because I wrote it. Rather than change around `get_preview` (which already has an order for those things), we modify `{{ post.preview }}` to accept arguments:

```twig
Here's my post: {{ post.preview({length:80}) }}
```

This seems to accomplish everything the chaining did, but in a more familiar way

**Comment by gchtr** [comment]
More suggestions for cleaning up:

## Non-namespaced functions in Twig

- [ ] Deprecate "old non-namespaced functions" in Twig @gchtr

In Twig, the following functions still exist: `TimberPost`, `TimberImage`, `TimberTerm`, `TimberUser`. For PHP, we replaced all those instances of non-namespaced functions. To make it more consistent, I’d deprecated these in Twig as well. The shorter versions that work perfectly fine (even without `Timber\` as a prefix) already exist: `Post`, `Image`, `Term`, `User`.

Documentation also needs to be checked for usages of the older functions.

## Timber::backwards_compatibility

- [ ] Remove `Timber::backwards_compatibility()`

I propose to remove class aliases for non-namespaced functions. We’re already trying to promote the namespaced classes and I think 2.0 would be a good moment to completely say goodbye to non-namespaced classes.

I’m still thinking about leaving one alias though: `Timber` as an alias for `Timber\Timber`. Should it be `Timber::render()` or `Timber\Timber::render()`? With a `use Timber\Timber;` statement at the beginning of a PHP file, it would still be possible to write `Timber::render()`. On the other hand, I’ve found the concept of namespaces in PHP a little hard to grasp at first and I see that it could be a barrier to use Timber. Shouldn’t Timber be very easy to use, even for developers who are just starting out with PHP?

**Comment by jarednova** [comment]
@gchtr I completely agree on ditching `Timber::backwards_compatability()` — now's the perfect time to cut the cord. Leaving `Timber` as an alias of `Timber\Timber` feels like the right amount of "user friendliness" (even for experienced users) `Timber\Timber::render()...` etc. just looks kinda .... stupid. 

Happy to take care of this, but I see you already self-assigned removing the non-namespaced functions so maybe it makes sense to take these as a pair

**Comment by jarednova** [comment]
All of these checkboxes have been brought over into the 2.x project:

https://github.com/timber/timber/projects/4

**Comment by jarednova** [comment]
I'm closing now that child issues have been spawned
