### ISSUE TITLE
Timber - WP Offload S3 plugin conflict

### ISSUE THREAD

**Issue by Ben764** [timber/timber#1591]
### Expected behavior
I have setup a custom loop (for a custom post type) to be inserted in the content of a post, through a shortcode. The result is that a limited number items of the required custom post type are inserted in a page or post. Each item contains a thumbnail, title, excerpt and custom field that are being displayed.

### Actual behavior
 Titles, thumbnails and custom fields are displayed correctly, but post_content  is taken from the main query (page or post where the custom loop is inserted).
The problem occurs when the WP Offload S3 Pro plugin is activated and use of {{ item.post_content }} in the loop item template. Using {{ item.content }} results in a internal server error (500 or 503) when loading a post or page with the shortcode. {{ item.post_excerpt }} shows correct excerpts.
Workaround is to use this code: {{ function('get_post_field', 'post_content', item.ID) }} in the loop item template.

WP Offload S3 Pro plugin applies filters, hooking into the_content filter. 
### Steps to reproduce behavior

I have written a custom wordpress plugin to setup $args variable. I use the code below to setup Timber for rendering the results:

	$data = Timber::get_context();
	$data['items'] = Timber::get_posts($args);
	$data['limit'] = $limit;
	$data['tz_template'] = 'tz-' . $custom_post_type . '.twig';
	
	return Timber::compile( $display . '.twig', $data);

### What version of WordPress, PHP and Timber are you using?
 WordPress 4.8.3, PHP 7.0, Timber 1.5.2

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Installed and upgraded to newest version via plugin updater in WordPress dashboard

**Comment by gchtr** [comment]
This sounds a lot like [the issue with `the_post` filter](https://github.com/timber/timber/issues/1639). WP Offload S3 seems to be using this filter too. The workarounds for this seem to be different depending on the use case.

I cannot garantuee it, but this issue will probably be fixed with Timber 2.x.

**Comment by rimager** [comment]
Just curious about the status of this. I too use WP Offload Media with Timber 1.19.1. WP Offload Media for S3 and the post.content isn't working in some instances. Is there a workaround for those of us on Timber 1?

**Comment by Levdbas** [comment]
Hi @gchtr , do you know a workaround for @rimager for the v1 version? Lets close this ticket after you took a look at this since this is probably fixed in 2.x

**Comment by gchtr** [comment]
The problem could be that somewhere before or in the loop, the `the_post` is called (maybe even by the WP Offload Media plugin).  Usually, in the `the_post` action, the `$post` global is overwritten.

My workaround was usually to call `setup_postdata()` again before the post data is accessed. I’d try using something like this:

```twig
{% do fn('setup_postdata', item') %}
{{ item.content }}
```

The workaround using `{{ function('get_post_field', 'post_content', item.ID) }}` probably works because then the `the_post` action isn’t called.

If that issue should be there again in 2.x, let’s work through it in a new issue.
