### ISSUE TITLE
Conflict when using Advanced Custom Fields and Static property on Timber class with ACF Field name Representation or Representative

### ISSUE THREAD

**Issue by AlexanderBMAS** [timber/timber#1687]
I noted that there is a notice thrown when using either **representative** or **representation** as field name in acf with timber. Not site breaking and just a notice but took some time trying to work out the conflict - maybe a list of reserved names would be useful (if there isnt't already one.)

### Expected behavior
Created an ACF Repeater Field called Representative and/or Representation, page loads normally no warnings or notices

### Actual behavior
Receive a warning notice - Notice: Accessing static property Timber\Post::$representation as non static.

### Steps to reproduce behavior
1. ACF and Timber Installed - WP_Debug True
2. Create a page
3. Create a field group with a repeater field named representative or representation
4. Load page see warning notice

### What version of WordPress, PHP and Timber are you using?
 WordPress 4.9.4, PHP 7.1.7, Timber 1.7.0, ACF 5.6.9

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
WP Add Plugin

**Comment by gchtr** [comment]
Hey @AlexanderBMAS 

This is an issue that has come up quite often in different variations. You’ve figured out yourself that `$representation` is a property of `Timber\Post`.

We also thought about this problem and will slightly change the behavior of retrieving custom field values in the upcoming version 2.0 (https://github.com/timber/timber/pull/1618). There’s a list with properties and methods that you shouldn’t use in https://timber.github.io/docs/reference/timber-post/, but unfortunately that list isn’t complete, because properties that are only used internally are not listed there. Instead of a list with reserved names, we think that proper warnings might be better.

In the meantime, to prevent the warning, you can alway access the value of your field through:

```php
$value = $post->meta( 'representation' );
```

Or in Twig:

```twig
{{ post.meta( 'representation' ) }}
```

(You could also use `get_field()`, but we will deprecate that as well. Only `meta()` will be used in the future.)

**Comment by AlexanderBMAS** [comment]
@gchtr Thank you I will use meta moving forward.
