### ISSUE TITLE
Provide proper upgrade guidance in admin depending on installation method

### ISSUE THREAD

**Issue by jarednova** [timber/timber#1688]
This is a todo based on @gsalkin's comments in #1673 — basically we should properly message upgrade procedure in WP Admin based on how Timber was installed (Composer vs. WP.org)

**Comment by gsalkin** [comment]
I would modify requirements for `timber-library` 2.0 to also require Twig 2.x. Currently `timber-library` still calls for the deprecated version of Twig. Now that most installations support PHP 7.x, I would move users to have that installed.

Creates better parity between the Github version and WordPress plugin.

**Comment by gchtr** [comment]
A quick note: Bumping the minimum Twig version to 2.x would probably break compatibility with WPML. WPML still uses Twig 1.32.0 (for compatibility with PHP5) and also loads Twig through Composer. Currently, the only solution I found to make WPML work with Timber is to install Timber as a plugin (related: #1064). But then, WPML’s Twig version will be used instead of Timber’s, which is not future-proof either.

I’m all for parity. I’m not saying we shouldn’t upgrade the minimum requirements (I’m not a big fan of WPML myself 🙊), but if we do it, we probably need to mark Timber as incompatible with WPML.

**Comment by jarednova** [comment]
Gahhhhhh!!!!!! Twig!!!!!

**Comment by gchtr** [comment]
I guess this can be closed. We won’t release 2.x as a plugin, but only as a Composer package. See #2005.
