### ISSUE TITLE
Feature Request: UserQuery class

### ISSUE THREAD

**Issue by acobster** [timber/timber#1689]
I would love to be able to do something like:

```php
$users = new Timber\UserQuery([
  'role' => 'my-custom-role'
]);
```

...and iterate over a collection of `Timber\User` objects. I believe the closest I can get to this currently is by executing a raw `WP_User_Query` and mapping each object to a `Timber\User`, but it would be really nice to be able to do this directly.

I'd love to get started on a PR for this, as this would be valuable for a number of projects I'm working on. But I could see this being a non-trivial undertaking so wanted to get your thoughts first.

Thanks!

**Comment by jarednova** [comment]
@acobster I'd love to do that as well! @gchtr is working on a similar `TermQuery` as we speak. `UserQuery` would be the piece that completes the puzzle.

In terms of guidelines, we want to follow [`WP_User_Query`](https://codex.wordpress.org/Class_Reference/WP_User_Query) as much as possible so we (or users) don't have to re-invent the wheel. Is this something you can start chipping away on?

**Comment by acobster** [comment]
Absolutely! Totally agree about `WP_User_Query`; the API should be as transparent as possible.

**Comment by gchtr** [comment]
I’ve looked into creating a new `TermQuery`. This actually goes much deeper than I initially thought and as @acobster has mentioned, is probably a «non-trivial undertaking». I think what we’d really want is to have parity not only for [`WP_Term_Query`](https://make.wordpress.org/core/2016/07/06/wp_term_query-in-wordpress-4-6/) and `WP_User_Query`, but also for `WP_Comment_Query`.

Currently, a PostQuery is built up from different objects, that I try to describe here:

- **PostQuery** – the public class to use that handles all the other classes behind the scenes.
- **PostGetter** – handles how posts are fetched from the database, depending on the object that is passed to `PostQuery`. It `PostQuery` is constructed with an array of posts, it will return a `PostCollection`. Otherwise it will return a `QueryIterator` object.
- **PostCollection** – a wrapper for an array posts that will automatically convert all posts to `Timber\Posts` (or custom objects, when requested).
- **QueryIterator** – handles queries defined as strings or arrays and will also return a `PostCollection` as soon as posts are requested.
- **PostsIterator** – handles what happens on each iteration when looping through a `PostCollection`. Basically, this sets up the `$post` global to make Timber compatible with (most) plugins.
- **Pagination** – handles pagination of posts for a `QueryIterator`.

Now, to make this work for terms, users and comments as well, we’d probably have to abstract things and work with interfaces and/or abstract classes for the following:

- Query
- QueryIterator
- Getter
- Collection
- Pagination

I guess that we wouldn’t need an abstraction for `PostsIterator`, because the difference of term, user and comment queries to a post query seems to be that in WordPress, only post queries rely on a global when looping through items. There’s the `$post` global, but no equivalent for terms, users and comments, right? 

Now, my questions are (pinging @jarednova):

- Am I on the right track here?
- Is this too big for version 2.0?
- How does this relate to #1218, #659 and #468? Do we need consider any concepts from these pull requests or did we already take a very different direction, with the support for pagination etc? This also directly relates to #1630 and the question of how to extend and hook into all of the functionality above.

**Comment by acobster** [comment]
@gchtr - Would love to hear from @jarednova as well on those questions, but that is my understanding of the `$post` global and the need for `PostsIterator`.

I'll let Jared comment on the timeline stuff for 2.0, but maybe we can at least roll out a refactored `PostQuery` to use some of these new-fangled abstractions in a first release? It might be a good idea to phase in such a big change across multiples releases anyway.... In any case, yeah, the abstractions you list above are exactly what I was thinking of when I said "non-trivial." :)

**Comment by jarednova** [comment]
> - Am I on the right track here?
> - Is this too big for version 2.0?

Yes and yes. It's almost always the case that as soon as you start pulling on yarn, the problem turns out to be bigger than anticipated. If at the outset you're already seeing a `«non-trivial undertaking»` up ahead, I think we hold on this. 2.0 is already big (w plenty left to go) — I think it's wise to slate this for `2.1` 

In terms of those old PRs, they show just how big major like work like this should get. In those cases, there wasn't anything _wrong_ with the code. The issue was adapting to such a large change all at once. If we're going to do big stuff I think it requires thorough documentation of the solution/risks (something you're always good at) before doing an extensive re-write.

These thoughts that you've layed out are valuable for hopefully a few months from now. But for now, it strikes me as a "later"

**Comment by jarednova** [comment]
@gchtr let me know if you agree with holding. I want to create a "2.x future" label, but will wait to get your 👍 / 👎

**Comment by gchtr** [comment]
@jarednova 👍 I very much agree on holding this back. We could always find more to improve for 2.x, but we also need to make a cut somewhere. I’d say that we could start tackling this with a high priority after releasing 2.0.

**Comment by acobster** [comment]
@gchtr @jarednova now that we have `Timber::get_users()`, I feel like the main use-case for this proposal is addressed. We could still benefit from a `UserQuery` class in terms of performance, if we did something similar to `PostQuery` with its own custom, lazy iterator.

**Comment by gchtr** [comment]
I too feel like this is covered well enough with `Timber::get_users()`. Let’s see how the new `PostQuery` works out and maybe add it to other object types in the future.
