### ISSUE TITLE
Front-end new post form

### ISSUE THREAD

**Issue by mi5ty** [timber/timber#1693]
#Hey all, I need to display a new post form in the archive page, I am able to set it up like this:

```
$new_post = array(
	'post_id' => 'new_post',
	'post_title' => true,
	'post_content' => true,
	'field_groups' => array(1349),
	'form' => true,
	'return' => '%post_url%',
	'html_before_fields' => '<div class="initiatives_form">',
	'html_after_fields' => '</div>',
	'new_post' => array(
	    'post_status' => 'draft',
	    'post_type' => 'initiatives'
	),
	'submit_value' => 'Create Initiative'
	);

$data['initiatives_form'] = acf_form($new_post);
```
My problem is that the form shows up on top of everything and I can't choose were to place it.

`{{initiatives_form}} `does not display anything. Any idea?

**Comment by gchtr** [comment]
The form shows up at the top of everything, because when you call `acf_form()`, the form already renders. And it doesn’t return any value that could be assigned to `$data['initiatives_form']`, so `{{ initiatives_form }}` is empty. Unfortunately, there’s no argument to define whether `acf_form()` should return its output or echo it.

I’d say you’d have to pass the arguments array only to Twig and then call `acf_form()` from your Twig file:

**PHP**

```php
<?php

$new_post = array(
    // Your form arguments
);

$data['initiatives_form_args'] = $new_post;
```

**Twig**

```twig
{{ fn('acf_form', initiatives_form_args) }}
```

**Comment by palmiak** [comment]
@mi5ty is @gchtr solution working for you?
