### ISSUE TITLE
How to get posts on a custom page template?

### ISSUE THREAD

**Issue by rehat101** [timber/timber#1702]
How can I see all posts on a custom page template? I have a page template called `updates` 

**updates.php**
```
$context = Timber::get_context();
$context['posts'] = Timber::get_posts();
Timber::render('updates.twig', $context );
```

**updates.twig**
```{% extends "base.twig" %}

{% set body_class = 'home' %}

{% block content %}
<div class="container">
  <h1 class="main-title">Latest updates</h1>
  {% for post in posts %}
    <div class="col-md-4">
      <article class="tease tease-{{post.post_type}}" id="tease-{{post.ID}}">
        <h2 class="h2"><a href="{{post.link}}">{{post.title}}</a></h2>
      </article>
    </div>
  {% endfor %}
</div>
{% endblock %}
```

I can't seem to be getting any posts. When I dump the variable "posts" I get one post which is the title of the template "Updates" — When I get the posts in `index.php` I can retrieve all kinds posts.

**Comment by acobster** [comment]
This isn't a Timber issue. Calling `Timber::get_posts()` without arguments is best used in the context of an _archive_ template, and that's why `index.php` retrieves multiple posts automatically. WordPress knows what kind of template you're on, so when Timber internally calls WordPress's native `get_posts()` function, it generates a query based on that template type. This logic is hard-coded in the WP core and adheres to the [WP Template Hierarchy](https://wphierarchy.com/).

To tell WordPress/Timber you want something more specific (in this case more than one post), pass some arguments to `Timber::get_posts()`

```
Timber::get_posts(array(
  'numberposts' => 5,
  'post_type' => 'my_post_type', // or whatever params you need
));
```

If you're working with a custom post type, you can instead rename your template to reflect that it's an archive template within the WP Template Hierarchy. For example, say your CPT is called `update`: you can rename the file to `archive-update.php`.

**Comment by rehat101** [comment]
@acobster Fair enough. Thanks!
