### ISSUE TITLE
Delete / Clone / Duplicate / etc a post or CPT from frontend 

### ISSUE THREAD

**Issue by stromi** [timber/timber#1718]
Hi there, I know that my question won't be a typical "separate logic from the template" one, but I am a bit stuck right now.

I'm developing a job listing site, and it's actually 90% done, except for some small but quite important functionalities, like: 
- logged-in users should be able to delete their own job listings
- logged-in users should be able to duplicate/clone their own job listings
- logged-in users should be able to edit their own job listings

Now, I know, that somehow I could write a custom function in functions.php, and then just use it with the current post's ID (or on the listings page, with the current item's ID in the for loop) to do it, but I can't really figure it out how. 

Had anyone done anything like this before? I really like Timber, so I don't want to start over with regular PHP :) 

@jarednova, or anyone who's an expert on these custom functions? 

Thanks in advance!

**Comment by gchtr** [comment]
Hey @stromi 

I hate to say this, but your question is probably too much out of scope for an issue in this repository and that’s why I have to close this. In my experience, what you’ll want to do is something that you wouldn’t need Timber for, but – as you might have guessed so far – regular PHP.

You’ll probably find more help if you post your question on [WordPress Development Stack Exchange](https://wordpress.stackexchange.com/).

I can only give you some pointers on where you could start:

If your logged-in users have access to the backend, it’s all about setting the proper [`Roles and Capabilities`](https://codex.wordpress.org/Roles_and_Capabilities). If you’ve registered your own Custom Post Type and registered it through [`register_post_type()`](https://developer.wordpress.org/reference/functions/register_post_type/), there are `cabability_type` and `capabilities` parameters you can look out for. A good plugin for managing Roles and Capabilites is [Members](https://wordpress.org/plugins/members/). There are plugins that add functionality for duplicating/cloning posts.

If your logged-in users shouldn’t have access to the backend, but should be able complete tasks in the frontend, there’s probably some more programming involved. If you use Advanced Custom Fields, you could use the [`acf_form()`](https://www.advancedcustomfields.com/resources/acf_form/) function to make job listings editable in the frontend. This would probably require the least amount of work. Otherwise, for editing, deleting and duplicating posts, I’d use the [REST API](https://developer.wordpress.org/rest-api/), which I guess is the state of the art for manipulating data in WordPress from «outside». Possibly there are also plugins that could help you with that.

**Comment by stromi** [comment]
Hey @gchtr, thanks a lot for the answer :) What you wrote is true, and since yesterday I've started to use the REST API for this, but of course it'll need some more work :) 

But thanks anyways and sorry for this out-of-scope question
