### ISSUE TITLE
PDF can also be an image type?

### ISSUE THREAD

**Issue by mgussekloo** [timber/timber#1720]
I think as of WP 4.7, PDF's can also be considered an image (Wordpress generates a preview thumbnail, which I can see in the WP-Admin, but front-end Timber returns the PDF file.).

Since we're dealing with TimberImage I think it's safe to assume people want the thumbnail image instead of the PDF file?

https://github.com/timber/timber/blob/7a73a5d11ffd6f05358aed9e0138752512a8399c/lib/Image.php#L461

**Comment by jarednova** [comment]
Yes, I agree @mgussekloo — as part of #1726 and #1736 we should consider all the possible media types, wether they qualify as an "image" in this context and are resize-able (thus, diff't behavior for PNGs vs PDFs and SVGs)

**Comment by Levdbas** [comment]
With the removal of the `is_image()` method in https://github.com/timber/timber/pull/2669, this change, if we want it, must be done in the PostFactory. Is this still something we would want to support? @nlemoine , @gchtr? For me personally, PDF's don't really feel as images and not sure what kind of extra issues we might run into down the line.

**Comment by gchtr** [comment]
I’m sure we’ll run into unexpected issues if we start considering PDF files as images, only because they can have an image preview.

But I understand that there’s a need to get the preview image for a PDF file. I’m not sure how to solve that yet. Maybe a method in the `Timber\Attachment` class that can return the proper preview image for an attachment, if one can be generated? Suggestions to solve this are welcome.

As for the original question, "Can PDF also be an image type?", I’d say no. That’s why I’m going to close this.
