### ISSUE TITLE
(feature request) More hierarchical menu properties: Timber\MenuItem::$parent and Timber\Menu::$flat_items

### ISSUE THREAD

**Issue by Langmans** [timber/timber#1768]
### Expected behavior
1. The MenuItem class should have a parent field so you can traverse up the hierarchy.
2. The Menu class could also implement a `$flat_items` array so people can loop over all the menuitems in a menu without having to use recursion or a stack array.

### Actual behavior
1. The `MenuItem` class does not have a `parent` property.
2. The `Menu` class does not provide `flat_items` property, a list of all the menu items it contains, only the direct children.

**Comment by rubenvincenten** [comment]
I'm using the following: https://gist.github.com/rubenvincenten/ac9ccf53861a06721c26e88b3b855924

I need this because when you have a page 5 levels deep, and a menu only has two levels, then you might want to select one of the ancestors. The code in the gist does that dynamicly but the step to get all the items is just obnoxious if you ask me...

**Comment by rubenvincenten** [comment]
One could also decide to use `MenuItem::$menu` that refers to the actual `Timber\Menu` object. Although, $menu is not maybe not descriptive enough...

**Comment by pascalknecht** [comment]
@rubenvincenten Sounds like a good idea. Would you be up to creating a pull request for this?

**Comment by Levdbas** [comment]
Good suggestion but it was never followed up upon. Closing this for now, but if you still want to open a PR, please do!
