### ISSUE TITLE
next() and previous() to accept post type?

### ISSUE THREAD

**Issue by parkerwebteam** [timber/timber#1847]
Currently the `next()` and `previous()` methods on the TimberPost object do not fetch the adjacent posts, and it only works for post types of `post`. 

A nice solution would be to extend both of the methods `next()` and `previous()` so that it could accept parameter of `$post_type` such as:

`post.next('my-custom-post-type')`.

**Comment by gchtr** [comment]
I know this is an older issue, but I’m currently documenting this feature a little better and stumbled over this.

> and it only works for post types of `post`.

It should work for all `Timber\Post` objects. To find out why it doesn’t work for you, you would have to provide a code example so that we can reproduce it – in case that’s still an issue for you.

> A nice solution would be to extend both of the methods `next()` and `previous()` so that it could accept parameter of `$post_type` such as:
> 
> `post.next('my-custom-post-type')`.

I guess this is going to be hard to solve with the current implementation. In the back, we’re using the `get_adjacent_post()` function. To allow querying for other or multiple post types, we would have to use the `get_next_post_where` and `get_previous_post_where` filters. But to add them in `Timber\Post::next()` and `Timber\Post::prev()` is probably not very elegant, because we would make sure they only run once.

I would suggest to use these two filters directly. Here’s a solution that seems to be doing exactly what you need: [Previous Next Post Navigation for Multiple Post Types at once](https://rudrastyh.com/wordpress/previous-next-multiple-post-types.html).
