### ISSUE TITLE
Issue with TimberImage caption and WPML

### ISSUE THREAD

**Issue by langhenet** [timber/timber#1896]
Hello,
I'm facing an issue with the caption retrieved from timber using TimberImage and the new way WPML handles the translation of image's metadata.

### Expected behavior
When in secondary language, when I use {{ Image( image ).caption }}, I'd expect to see the translated caption.

### Actual behavior
The caption returned is the one in the main language.

### Steps to reproduce behavior
1. In single.twig print the featured image caption of the post using {{ Image( image ).caption }}.
2. Upload an image, write down a caption, and set it as featured image of a post
3. Go to WPML -> Media Translation and translate the caption of the image you just uploaded.
4. Create a translation of the previously created post
5. The caption used is the one in the original language, not the one translated

### What version of WordPress, PHP and Timber are you using?
Wordpress 4.9.8
Timber 1.8.3
WPML 4.1.3 
WPML media translation 2.4.1

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
wp.org

**Comment by langhenet** [comment]
Hello :-)
Anybody experiencing this issue as well?

**Comment by Levdbas** [comment]
This issue might still need our attention.

**Comment by Levdbas** [comment]
I took a deeper dive @langhenet  and found out that this will be fixed in 2.0 of Timber. See the following commit: https://github.com/timber/timber/commit/5a2771d5d1bf97dc8e086a606ba539129fb1f621

WPML hooks into wp_get_attachment_caption as well to update the translation. Since we are not going to patch this in the v1 version anymore, I am going to close this here.
