### ISSUE TITLE
twig(error): strtr expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by muuvmuuv** [timber/timber#1897]
### Expected behavior

No error

### Actual behavior

Prints: `Warning: strtr() expects parameter 1 to be string, array given in /Users/marvinheilemann/Documents/Friends/Isabella Gensch/Website/wordpress/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/Extension/Core.php on line 486`

### Steps to reproduce behavior

I don't really know, I have just updated Wordpress and Timber and then it appears.

### What version of WordPress, PHP and Timber are you using?

Wordpress: 5.0.3
Timber: 1.8.4
PHP: 7.2

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

Wordpress plugin

**Comment by jarednova** [comment]
Hi @muuvmuuv we need to be able to reproduce the error in order to investigate. Can you post the relevant PHP and Twig code that's triggering the error?

**Comment by muuvmuuv** [comment]
Hey @jarednova sorry, until now I haven't found the line that caused the error. In my functions.php:

```php
add_filter('timber_context', array($this, 'timber_acf_global_options'));
...
  public function timber_acf_global_options($context)
  {
    // The current post/page
    $context['page'] = new Timber\Post(); // <- error producer

    return $context;
  }
....
```

Do I need to add parameters to `Post()`? I thought it would just grab the current post/page, I need that context for some other variables I pass to context (haven't included it to keep it simple).

**Comment by jarednova** [comment]
@muuvmuuv awesome, thanks! Without testing, I'd have to guess that because that line is coming in a filter, Timber might be unable to get the current post number from `global $post` (versus in `single.php`

The data that you're looking for is actually already available in `$context`. Look at `$context['post']`

**Comment by muuvmuuv** [comment]
@jarednova @gchtr okay I tested both and none fit in my case. I will show you the rest of the code:

```php
    $context['options'] = get_fields('option');
    $context['menu'] = new Timber\Menu('main-menu');
    $context['page'] = new TimberPost();
    $context['acf'] = get_field_objects($context['post']->ID);
```

What I was intending to do, was to get the ACF fields globally so I don't need to add it in every file. I can remember that I hadn't this issue in prior versions (but can't remember which). And I'm using the page variable to access things like `page._wp_page_template`.

**Comment by gchtr** [comment]
As I said, when you use `new Timber\Post()`, it might work in singular templates (like single.php), but not in archive templates (like archive.php).

Let’s look at your code:

```php
$context['page'] = new TimberPost();
$context['acf'] = get_field_objects($context['post']->ID);
```

Here, you first set `page` in `$context`. When you’re in an archive and `new TimberPost()` is run, I don’t know that happens, because normally, on an archive page, you wouldn’t access a post, but a list (or array) of posts.

```php
$context['acf'] = get_field_objects($context['post']->ID);
```

Here you take the variable `$context['post']` as the parameter for `get_field_objects()`. But where does `$context['post']` come from? I only see that you set `$context['page']`. This might be a first error.

The second error is that `$context['post']` or `$context['page']` might not have a valid `ID` property on an archive page. Because when you run `new TimberPost()`, Timber probably won’t return something meaningful on an archive page, and when you access the ID, nothing meaningful happens.

> What I was intending to do, was to get the ACF fields globally so I don't need to add it in every file.

You can do that, but like I said, I would add the check with `is_singular()`, because otherwise you might run into errors like the ones you see.

**Comment by Ascendant-localstack** [comment]
> [@muuvmuuv](https://github.com/muuvmuuv) awesome, thanks! Without testing, I'd have to guess that because that line is coming in a filter, Timber might be unable to get the current post number from `global $post` (versus in `single.php`
> 
> The data that you're looking for is actually already available in `$context`. Look at `$context['post']`





https://preprocessor.space/questions/php-string-manipulation-and-substitution-techniques
