### ISSUE TITLE
Multisite Timber::get_sites() in admin with same locale

### ISSUE THREAD

**Issue by jhhazelaar** [timber/timber#1908]
We have a WP multisite installation with Multilingualpress plugin for multi language support. We now want to extend a custom plugin that gets all sites and add some ACF fields per site with the locale as part of the key.

### Expected behavior
`Timber::get_sites()` get two site. One with 'en-US' en second with 'nl-NL'. In the theme we get this result. 

### Actual behavior
In the admin we get two site with different ids with the same locale 'en-US'

### What version of WordPress, PHP and Timber are you using?
Wordpress: 5.0.3, PHP: 7.2.13, Timber: 1.8.4

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Composer/Packages

**Comment by highbelt** [comment]
Experienced the same issue, as 

https://github.com/timber/timber/blob/53cfc653d21c5d9a4b819040e9493c6699449154/lib/Site.php#L178

seems to return the initial site language (ignores `switch_to_blog(...)`).

Maybe use `$this->language = get_locale();`instead, as it seems to return the right value.

WP: 5.5.3, Timber 1.18.2 & Multilingualpress 3.5.0

**Comment by gchtr** [comment]
Using `get_locale()` sounds like a good approach to this! When using `get_bloginfo( 'language' )`, then `determine_locale()` is used, which considers the language set in the user profile. This could lead to all the sites returning the same language when a user overwrites it in their profile on all sites. Using `get_locale()` is way more predictable, because it always uses the language setting used for a site.

@highbelt Do you feel comfortable enough to create a pull request for this?

**Comment by gchtr** [comment]
That was a quick! With #2369 already being merged, we can close this one. The solution will be included in the next release.
