### ISSUE TITLE
Handle image generation from remote sources and AWS storage. sideload_image function not compatible with non-local storage systems.

### ISSUE THREAD

**Issue by petertwise** [timber/timber#1929]
Our site pulls in images from a JSON feed and processes them with timber. So the originating URL is a non-local URL from the parent company's CDN. We are also using WPEngine for hosting and are using their proprietary LargeFS system, which pushes images older than 10 days to an S3 bucket.

* Images URLs are produced via Timber/Twig using usually either the ImageHelper::resize or ImageHelper::letterbox functions.
* Both functions call ImageHelper _operate to generate the image
* _operate checks if the image is external, which it will always be for images from the JSON feed / API. If it is external it will run ImageHelper::sideload_image on the URL.
* sideload_image will check if the file exists using the get_sideloaded_file_loc function. But this function uses wp_upload_dir() 'path' which will always return the server path , not a URL.
* Conclusion: Any image with an original URL being pulled from the Workman API will constantly be going around in a circle where it is regenerated when the page is visited, then 10 days later moved to AWS/LargeFS and then when the page is visited again, Timber sees it is missing from the server and regenerates it on the server again.
* Additional suspicion that I have not confirmed: Because of the /year/month/file URL structure in WordPress I think a huge amount of the storage on AWS is unused duplicate files. Each circular go around where images are needlessly regenerated puts the new image in the current year/month directory and then eventually pushes it to AWS and then starts over again.

Example page: https://www.storey.com/books/the-pesto-cookbook/

Twig image code:
```
<img src="{{book.cover_image | default('/wp-content/themes/storey/static/img/placeholders/placeholder_tease.jpg') | resize(600) }}" alt="">
```

**Describe the solution you'd like**

It would be great to have some option or modification to the sideload_image function to force it to check for the existence of the existing absolute file URL instead of only checking the server path to see if an image exists before recreating it.

It would also be great to get some advice regarding the /year/month/file URL structure and how to avoid creating a lot of duplicate images in different year/month directories.

**Describe alternatives you've considered**

Modifying the custom theme to bypass Timber image functions and just use core WP image resizing.

**Additional context**

Related but not identical issues:

* https://github.com/timber/timber/issues/510
* https://github.com/timber/timber/issues/1156

**Comment by squarecandy** [comment]
https://github.com/timber/timber/blob/master/lib/ImageHelper.php#L577
This always returns true for us because the images URLs being passed in are on an external CDN.

https://github.com/timber/timber/blob/master/lib/ImageHelper.php#L368
https://github.com/timber/timber/blob/master/lib/ImageHelper.php#L346
This always forces an image to be generated again once it is moved to S3 because `get_sideloaded_file_loc` checks if this file exists at the server path, not the URL.

**Comment by tristanbes** [comment]
Hello @squarecandy,

I'm not a maintainer, but I want to understand your issue. Are you saying that since you host your image on a remote location (Amazon S3 for example), `timber` will try to re-create images locally each time because due to the actual code, it doesn't "see" the images on the filesystem ? Does it only applies when using the `resize` filter ?

I'm asking because we have immutable infrastructure (= all files that are not commited are lost upon re-deploying application), so all our images are stored on a S3 compliant system (and we use https://github.com/humanmade/S3-Uploads).

**Comment by squarecandy** [comment]
Our system is setup using WPEngine. They have a proprietary file system similar to https://github.com/humanmade/S3-Uploads called [LargeFS](https://wpengine.com/support/configuring-largefs-store-transfer-unlimited-data/). The files live on the server for 10 days, and then are automatically migrated to S3.

We seem to be having issues because the sideload_image() and get_sideloaded_file_loc() functions are checking for the existance of a file at the server path, not the absolute URL. https://github.com/timber/timber/blob/master/lib/ImageHelper.php#L368 

I think we're going to solve it by just bypassing timber's image functions entirely and using core WP functions instead....
but I'm still curious why it's setup like this.

**Comment by gchtr** [comment]
We’re still trying to fully understand CDN issues. In #1925 and #1944 I have been trying to take notes about what works and what doesn’t. From reading your issue, this seems to be yet another issue in relation to Pull CDNs.

> I think we're going to solve it by just bypassing timber's image functions entirely and using core WP functions instead...

This seems to be the "workaround" currently.

> but I'm still curious why it's setup like this.

I’d say Timber Images were not thought to be used with CDNs in the beginning. Making Timber images work with CDNs is a goal, but currently we don’t have lots of resources to work on this. Contributions and pull requests for solving this are very welcome. Your detailed list certainly helps as well!

**Comment by squarecandy** [comment]
Ok, I think the solution for my exact situation is a very small change that should make a big difference. I submitted a pull request: https://github.com/squarecandy/timber/pull/1 

Please let me know your thoughts on this...

**Comment by Levdbas** [comment]
Hi @petertwise , thank you for your work on this. Your PR didn't get much traction because you've submitted the PR on your own fork unfortunately. Since this is such an old issue now I will close it, but if you still run into this, please let me know!
