### ISSUE TITLE
Use namespaced classes for Twig

### ISSUE THREAD

**Issue by gchtr** [timber/timber#1941]
According to [this announcement](https://symfony.com/blog/new-in-twig-namespaced-classes), non-namespaced Twig classes **will be deprecated with the next 2.x version of Twig**, and **will be removed** in Twig 3.x.

This means that in [`Timber\Twig`](https://github.com/timber/timber/blob/master/lib/Twig.php), we should probably use namespaced Twig classes. Instead of:

```php
namespace Timber;

class Twig {
    public function __construct() {
        add_action( 'timber/twig/filters', array( $this, 'add_timber_filters' ) );
    }

    public function add_timber_filters( $twig ) {
        $twig->addFilter( new \Twig_SimpleFilter(
            'resize',
            array( 'Timber\ImageHelper', 'resize' )
        ) );
    }
}
```

We should probably use:

```php
namespace Timber;

use Twig\TwigFilter;

class Twig {
    public function __construct() {
        add_action( 'timber/twig/filters', array( $this, 'add_timber_filters' ) );
    }

    public function add_timber_filters( $twig ) {
        $twig->addFilter( new TwigFilter(
            'resize',
            array( 'Timber\ImageHelper', 'resize' )
        ) );
    }
}
```

## Questions

- Will this work with Twig 1.x?
- What kind of backwards-compatibility should we keep? What should be the minimum version required for Twig in Timber 2.x? Should we bump it to Twig 2.x?
- How does [Twig_Function.php](https://github.com/timber/timber/blob/master/lib/Twig_Function.php) play into this? Do we need to use `Timber\Twig_Function` in `Timber\Twig` as well? Do we need the same checks for `Twig\TwigFilter` to keep backwards compatibility?

## Todo

- [ ] Update to namespaced classes in code while providing backwards compatibility.
- [ ] Update to namespaced classes in documentation and examples.

**Comment by jenkoian** [comment]
Do you think Timber should mirror the versions of Twig? Similar to what Elastica does with ElasticSearch https://github.com/ruflin/Elastica#versions--dependencies if so it might help answer some of the questions. 

As someone waiting eagerly for the release of `2.x` I'd vote for whatever doesn't delay that any further :)

**Comment by jarednova** [comment]
**Will this work with Twig 1.x?**
I'm guessing not. But even if it does, I think for 2.x, we shouldn't let that worry us ...

**What kind of backwards-compatibility should we keep? What should be the minimum version required for Twig in Timber 2.x? Should we bump it to Twig 2.x?**
I think so. The reason to keep support for Twig 1.0 is because of wp.org users and the PHP needs ([where >50% is still on PHP 5.x](https://wordpress.org/about/stats/)) — with 2.0 we don't have that same constraint since it won't be released through wp.org

**How does Twig_Function.php play into this? Do we need to use Timber\Twig_Function in Timber\Twig as well? Do we need the same checks for Twig\TwigFilter to keep backwards compatibility?**
Yep! We could totally remove `Twig_Function.php` same with other 1.x ==> 2.x hacks
