### ISSUE TITLE
ACF Text Fields Returned As Arrays

### ISSUE THREAD

**Issue by AtlantaJones** [timber/timber#1952]
I'm having problems with ACF text fields being returned intermittently as arrays and not strings.

## Expected behavior
Expecting Timber to return any data from an ACF text field as a string.

## Actual behavior
Sometimes, the output will be an array, sometimes as a string. 

## Steps to reproduce behavior
I created two text fields in ACF the exact same way and attached them to page post types. I created a page and entered text into both fields. 

On a page, I pulled all the page data with:

```php
$context = Timber::get_context();
$post = new TimberPost();
$context['post'] = $post;
```

...and output in the template as `{{ post.hero_heading }}` and `{{ post.hero_subhead }}`. 

The first one output an array, the second a string. 

## What version of WordPress, PHP and Timber are you using?
Wordpress: 5.5.1
Timber: 1.9.1
ACF Pro: 5.7.13

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Installed manually by copying to plugins folder.

## Notes
At first I thought this might be an ACF issue, but if I do `get_field('hero_heading', 4193);` the output is a string, not an array. Just looking for some ideas as to what may be happening.

**Comment by palmiak** [comment]
Could you post your acf fields config?

śr., 20 mar 2019, 03:25 użytkownik Andrew Jones <notifications@github.com>
napisał:

**Comment by AtlantaJones** [comment]
Here is the export for the group containing the two text fields

```JSON
[
    {
        "key": "group_5c919b6dc326c",
        "title": "Page Options",
        "fields": [
            {
                "key": "field_5c919b7c12ec0",
                "label": "Hero Heading",
                "name": "hero_heading",
                "type": "text",
                "instructions": "",
                "required": 0,
                "conditional_logic": 0,
                "wrapper": {
                    "width": "",
                    "class": "",
                    "id": ""
                },
                "default_value": "",
                "placeholder": "",
                "prepend": "",
                "append": "",
                "maxlength": ""
            },
            {
                "key": "field_5c919b9912ec1",
                "label": "Hero Subhead",
                "name": "hero_subhead",
                "type": "text",
                "instructions": "",
                "required": 0,
                "conditional_logic": 0,
                "wrapper": {
                    "width": "",
                    "class": "",
                    "id": ""
                },
                "default_value": "",
                "placeholder": "",
                "prepend": "",
                "append": "",
                "maxlength": ""
            }
        ],
        "location": [
            [
                {
                    "param": "post_type",
                    "operator": "==",
                    "value": "page"
                }
            ]
        ],
        "menu_order": 0,
        "position": "normal",
        "style": "default",
        "label_placement": "top",
        "instruction_placement": "label",
        "hide_on_screen": "",
        "active": true,
        "description": ""
    }
]
```

**Comment by AtlantaJones** [comment]
Also, if I do a `print_r($context['post']);` here is what those fields look like:

```
[hero_heading] => Array
    (
        [0] => Our Mission
        [1] => Our Mission
    )
[_hero_heading] => Array
    (
        [0] => field_5c919b7c12ec0
        [1] => field_5c919b7c12ec0
    )
[hero_subhead] => To be a community partner...
[_hero_subhead] => field_5c919b9912ec1
```

**Comment by gchtr** [comment]
Do you get the same result if you try `{{ post.meta('hero_heading') }}` and `{{ post.meta('hero_subhead') }}`?

**Comment by AtlantaJones** [comment]
No, actually that results in it properly returning strings in both cases.

**Comment by gchtr** [comment]
I assume that for some reason, you have duplicate values in your database for the `hero_heading` meta key. You could check that out in the `wp_postmeta` database table directly or try out a plugin like [Cleanup Duplicate Meta](https://de.wordpress.org/plugins/cleanup-duplicate-meta/).

However, for future versions of Timber it’s better to access meta values through `{{ post.meta() }}` anyways, because there, you get values filtered by ACF. With `{{ post.hero_heading }}` and `{{ post.hero_subhead }}` you’ll get values straight from the database, which might not always be the result you’d expect.

**Comment by AtlantaJones** [comment]
Oh, cool. I had no idea. Will start doing that instead, thanks!

**Comment by AtlantaJones** [comment]
One last question. Should this be something brought up to the ACF folks, or is it just something that happens?

**Comment by gchtr** [comment]
In case you really have duplicate values in your database, then it’s something that’s supposed to happen. It’s probably related to the third parameter `$single` of the [`get_post_meta()`](https://developer.wordpress.org/reference/functions/get_post_meta/) function, which is used by Timber behind the curtains. If `$single` is false, you will get an array with all the values for that meta key for a post. That’s maybe why you would see your value twice in `hero_heading`.

I’d say there’s no need to bring this up to the ACF folks, especially if it also works fine if you use `get_field()`.

**Comment by AtlantaJones** [comment]
Great, thanks again. Closing :)

**Comment by FynnZW** [comment]
Could you elaborate when to use `post.meta(my_variable)` instead of just `post.my_variable`?
I thought meta (or before get_field) was only necessary for complex fields likes gallerys or editor-fields:
https://timber.github.io/docs/guides/acf-cookbook/#getting-acf-info
Is it now recommended to always work with post.meta() ?

**Comment by jarednova** [comment]
@FynnZW we found it easier to just say "always use the `.meta` method instead of the "sometimes" approach. It also dramatically simplifies the Timber code and helps prevent future collisions (ie. a reserved method or WP var that shares the same name as a meta field someone has created).

Just make sure you're using quotes, i.e.: `post.meta("my_variable")`

**Comment by oxyc** [comment]
Just mentioning I just ran into this when using ACF Multilingual from WPML.

**Comment by TheMangoTrain** [comment]
I had this issue too... ACF meta fields rendering on page as "array", even though previously they were rendering fine... meanwhile all regular Twig functionality seemed to be working fine.

Ultimately the issue came down to this important line being temporarily commented-out in my functions.php (for different reasons):
`$timber = new Timber\Timber();`

Commenting such a line is obvious going to cause problems, however I was tricked for awhile as some Timber functionality worked without it. So this is a reminder to check all aspects of your project!
