### ISSUE TITLE
Should we really deprecate Timber::get_posts in 2.0?

### ISSUE THREAD

**Issue by palmiak** [timber/timber#1957]
While reviewing https://github.com/timber/timber/pull/1813 there is a small difference between `get_posts()` and `WP_Query()`. `get_posts()` always gets three extra params:
- ignore_sticky_posts
- no_found_rows
- suppress filters

I see that `Timber::get_posts()` is deprecated in 2.0, but shouldn't we keep `get_posts()` in some way to keep better compatibility with WP? @gchtr what do you think? Or maybe I'm missing something - I don't know 2.0 to good yet :)

**Comment by gchtr** [comment]
I totally missed what was going on in that pull request. Good question!

For 2.0, @jarednova and I decided to remove a lot of functionality that practically does the same thing, like `Timber::query_posts()`. The same goes for `Timber::get_posts()`.

Keeping `Timber::get_posts()` would mean that we would have to explain the differences between that function and `Timber\PostQuery` and I fear it would lead to more confusion. We would have to answer the following questions:

- **Should you use `get_posts()` or `WP_Query` when working with WordPress?** 
- **When should you use `get_posts()` and when should you use `WP_Query`?** What’s the benefit of using `get_posts()` over `WP_Query`?

An it boils down to this one: **Do we use modern WordPress functionality or do we want to keep all the backwards compatibility that’s also baked into WordPress?**

It seems to me that `get_posts()` is a rather old function and that `WP_Query` is the preferred method to get posts. Are the defaults for the three mentioned parameters the only difference? If yes, I think it would make even more sense to drop `Timber::get_posts()` in order to prevent the confusion that could come with it. The documentation for the query parameters is way more detailed for [WP_Query](https://developer.wordpress.org/reference/classes/wp_query/) than for [get_posts()](https://developer.wordpress.org/reference/functions/get_posts/). I would prefer only a single way to fetch posts through Timber. How fetching posts works exactly can be answered better when we figure out how Object Factories work. They decide how the final API in 2.0 will look like.

**Comment by palmiak** [comment]
> Should you use get_posts() or WP_Query when working with WordPress?
> When should you use get_posts() and when should you use WP_Query? What’s the benefit of using 
> get_posts() over WP_Query?

Like mentioned before - `get_posts` is `WP_Query` with some default arguments. From programming point of view `get_posts()` is useless. But on the other hand most people don't use `suppress_filters ` or `no_found_rows` on daily basic, but use `get_posts()` when pagination in not needed (without any deeper understanding). 

So the only benefit of `get_posts` for people who knows the difference is 3 lines less code.

For rest of them `get_posts` is faster in situations when no pagination is needed. https://kinsta.com/blog/wp-query/

So I think we should keep some way of `get_posts` - it may be some variation of `Timber\PostQuery` with default arguments passed as filter or something like that (I'm just guessing).

**Comment by jarednova** [comment]
@gchtr @palmiak I think I'm right there between you. I think where we've come to is to _match_ WP's functionality, but not necessarily _mirror_. 

In other words we should *match* the various arguments and defaults WP uses. If WP says `sticky_posts=true` here — Timber should too.

But not necessarily *mirror* every detail. WP has to essentially duplicative functions for a bunch of backwards compatibility and other complicated reasons. Timber is a bit more free here. A lot of 2.0 is about cutting a number of duplicative functions or aliases into a single "do it this way". `PostQuery` vs `Timber::get_Posts` feels like a great example of this. Sure, it's only a little bit of overhead, but it's the same darn thing. 

So yes, I think we should proceed with deprecation — but keep in mind it's deprecation and not removal. Since this is also such a common function, we should be sure to include in the upgrade guide, etc.

**Comment by newkind** [comment]
Hmmm I'm wondering about calling the new syntax from inside of the twig files ie. using `function()`. Right now we could do `function('Timber::get_posts', args)` but how this will work with the new syntax like `new Timber\PostQuery()` ?

**Comment by gchtr** [comment]
> For rest of them `get_posts` is faster in situations when no pagination is needed.

@palmiak Good point! Performance is surely a thing we always have to keep in mind! However, in 2.0, the context will handle the population of `posts`. So there’s no need to call `$context['posts'] = new PostQuery()` in *most* cases. You can read more about how this will look like in https://github.com/timber/timber/blob/2.x/docs/guides/context.md#archive-templates. For performance, there’s [another section](https://github.com/timber/timber/blob/2.x/docs/guides/context.md#performance). For archive pages, to really affect performance, you’d have to use the `pre_get_posts` action anyway.

> But on the other hand most people don't use `suppress_filters ` or `no_found_rows` on daily basis.

Right! And I wonder how many people really know the difference between `get_posts()` and `WP_Query`. For example, I assume that using `get_posts()` will break plugins that allow reordering posts via Drag'n'Drop. Does everybody consider that when they use `Timber::get_posts()`? Or do they keep wondering why the menu order isn’t considered or why sticky posts don’t work with their query?

Because of this, I think it’s better to be explicit with query parameters and avoid shortcuts that might be unclear or require you to look at the code to see what they’re doing. Here again, a little less magic might help.

> So I think we should keep some way of `get_posts` - it may be some variation of `Timber\PostQuery` with default arguments passed as filter or something like that (I'm just guessing).

For `PostQuery`, there’s a new syntax with an array of parameters:

https://github.com/timber/timber/blob/0a2b610c6d907bf5a5fd7c397ff03e2e1dbe5aac/lib/PostQuery.php#L97-L101

Currently, there’s three parameters: `query`, `merge_default` and `post_class`. We could add another parameter, but how would it be called? Is there a word that tells us what `get_posts()` is doing differently?

If we wanted to create an easy flag to not include or exclude pagination, we could add a new `pagination` parameter that could be set to false:

```php
$posts = new PostQuery( array(
    'query' => array(
        'posts_per_page' => -1,
        'post_type' => 'book',
    ),
    'pagination' => false,
) );
```

But then again, this would be the same as :

```php
$posts = new PostQuery( array(
    'query' => array(
        'posts_per_page' => -1,
        'post_type' => 'book',
        'no_found_rows' => true,
    ),
) );
```

And I’m wondering whether we should hide the knowledge about `no_found_rows` behind another parameter or mention the performance impact of `no_found_rows` in the documentation instead. Instead of saying: «Use `get_posts()` if you don’t use pagination», I think we should be saying: «If you care about performance and don’t use pagination, set `no_found_rows` to `true`».

**Comment by gchtr** [comment]
@newkind Good question! In general, I would suggest to not put query parameters in Twig. You could instead use another function that performs your query:

```twig
{% for post in function('my_posts') %}
```

```php
function my_posts() {
    // Returns your query.
}
```

But it’s also possible to use `PostQuery` in Twig. We’ve considered this in https://github.com/timber/timber/pull/1624. You could write your query like this:

```twig
{# Hash notation #}
{% for post in PostQuery({
    post_type: 'post',
    posts_per_page: 10
}) %}
	<a href="{{ post.link }}">{{ post.title }}</a>
{% endfor %}
```

**Comment by newkind** [comment]
@gchtr Thanks for the answer. That looks great. I agree that it's best to do it outside of the Twig but in our Gantry5 environment and 'Particles' based on YAML configuration, we kinda have to do it from the Twig itself, hence me asking ;)

**Comment by gchtr** [comment]
We decided to keep `Timber::get_posts()` as the official API for getting posts instead of `new Timber\PostQuery()`. In #2073, we document how `Timber::get_posts()` will be used in the future.

To get posts in Twig, instead of using `PostQuery`, you will have to use `get_posts()`:

```twig
{# Hash notation #}
{% for post in get_posts({
    post_type: 'post',
    posts_per_page: 10
}) %}
	<a href="{{ post.link }}">{{ post.title }}</a>
{% endfor %}
```

I’ll leave this issue open to remind myself to get back to the documentation about the difference to WordPress’s `get_posts()`.

**Comment by gchtr** [comment]
> I’ll leave this issue open to remind myself to get back to the documentation about the difference to WordPress’s `get_posts()`.

This is documented in https://github.com/timber/timber/blob/2.x-docs-api/docs/v2/guides/posts.md#differences-from-wp-cores-get_posts (#2073).
