### ISSUE TITLE
'nav_menu_css_class' filter $args param empty array

### ISSUE THREAD

**Issue by benedict-w** [timber/timber#1959]
## Expected behavior
When applying the filter _nav_menu_css_class_, the third param $args should be an array of wp_nav_menu args https://developer.wordpress.org/reference/functions/wp_nav_menu/ - see: https://codex.wordpress.org/Plugin_API/Filter_Reference/nav_menu_css_class

## Actual behavior
Empty array passed instead.

See MenuItem.php, function `import_classes`, line 236 (Timber v1.9.3)

`$this->classes = apply_filters('nav_menu_css_class', $this->classes, $this, array(), 0);`

This means that when applying my own filter to nav_menu_css_class I can not identify the theme_location from the $args param to add my own CSS class.

There's an example of how you would do this in the WordPress docs on this page: https://codex.wordpress.org/Plugin_API/Filter_Reference/nav_menu_css_class

```
function my_secondary_menu_classes( $classes, $item, $args ) {
    // Only affect the menu placed in the 'secondary' wp_nav_bar() theme location
    if ( 'secondary' === $args->theme_location ) {
        // Make these items 3-columns wide in Bootstrap
        $classes[] = 'col-md-3';
    }

    return $classes;
}

add_filter( 'nav_menu_css_class', 'my_secondary_menu_classes', 10, 3 ); 
```

Adding a function like this doesn't work for TimberMenu because the $args param is set to an empty array.

**Comment by gchtr** [comment]
You’re right, Timber deviates in the filter arguments for `nav_menu_css_class`. These are the default args that are used for `wp_nav_menu()`:

```php
$defaults = array(
	'menu'            => '',
	'container'       => 'div',
	'container_class' => '',
	'container_id'    => '',
	'menu_class'      => 'menu',
	'menu_id'         => '',
	'echo'            => true,
	'fallback_cb'     => 'wp_page_menu',
	'before'          => '',
	'after'           => '',
	'link_before'     => '',
	'link_after'      => '',
	'items_wrap'      => '<ul id="%1$s" class="%2$s">%3$s</ul>',
	'item_spacing'    => 'preserve',
	'depth'           => 0,
	'walker'          => '',
	'theme_location'  => '',
);
```

Out of these, only the following would be applicable to a Timber Menu, because all others relate to the menu walker, which we don’t have in Timber:

```php
$defaults = array(
	'menu'            => '',
	'depth'           => 0,
	'theme_location'  => '',
);
```

This would mean that we can only add support for these args. As I understand it (correct me if I’m wrong), the `menu` and `theme_location` args would probably be the same: the slug of the menu (`secondary` in your case). We already have an `$options` parameter for `Timber\Menu`:

https://github.com/timber/timber/blob/65c7ea09a595840c1bd1a972fd969ee95d46e533/lib/Menu.php#L63-L71

That `$options` array would probably be what we have to pass into the `nav_menu_css_class` filter.

Instead of passing the theme location in the args, we could also save the menu slug / theme location on each menu item, so that you could access it through the `$item` variable:

```php
function my_secondary_menu_classes( $classes, $item, $args ) {
    // Only affect the menu placed in the 'secondary' wp_nav_bar() theme location.
    if ( 'secondary' === $item->theme_location ) {
        // Make these items 3-columns wide in Bootstrap
        $classes[] = 'col-md-3';
    }

    return $classes;
}
```

Or we could make the menu item know about the menu it sits in and make the slug accessible through that. Maybe something like this:

```php
if ( 'secondary' === $item->menu->slug ) {

}
```

Thoughts, @jarednova and @palmiak?

**Comment by jarednova** [comment]
@gchtr I think you're on the right track. It also ties into the larger project of utilizing more args arrays for parameter setting.

The format you suggest feels right...
```php
if ( 'secondary' === $item->menu->slug ) {

}
```

... but even if they are redundant, I think we should preserve the WP names to make things more universal to code samples that people might rely on. So that way, @benedict-w could also use:

```php
if ( 'secondary' === $item->menu->theme_location ) {

}
```

... perhaps these are not the preferred/documented variable names — but it would make it easy for people trying to hack compatibility between what they're working with (esp. a plugin) and Timber.

**Comment by gchtr** [comment]
@benedict-w The pull request #2018 is now merged. You will be able to access the theme location from a menu item with the next release of Timber.
