### ISSUE TITLE
Pagination does not work with new Timber\Post()

### ISSUE THREAD

**Issue by ttsuru** [timber/timber#1992]
## Expected behavior

`{{ paged_content }}` works with `new Timber\Post()`

## Actual behavior

`{{ paged_content }}` with `new Timber\Post()` shows the full text of the article.

## Steps to reproduce behavior

Don't work

```php
// single.php
$context = Timber::context();
$context['post'] = new Timber\Post();
Timber::render('single.twig', $context);
```

```twig
{# single.twig #}
<article>
    <h1 class="headline">{{post.title}}</h1>
    <div class="body">
        {{post.paged_content}}
    </div>
</article>
```

Work

```php
// single.php
$context = Timber::context();
$context['post'] = Timber::query_post();
Timber::render('single.twig', $context);
```

```twig
{# single.twig #}
<article>
    <h1 class="headline">{{post.title}}</h1>
    <div class="body">
        {{post.paged_content}}
    </div>
</article>
```

## What version of WordPress, PHP and Timber are you using?

Timber 1.9.4

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

Composer/Packagist

**Comment by ttsuru** [comment]
I think `global $page` is not set with call `new Timber\Post()`.

```php
	/**
	 * @return string
	 */
	public function paged_content() {
		global $page;
		return $this->content($page, -1);
	}
```

**Comment by aj-adl** [comment]
@ttsuru the pagination of content in the built-in WordPress way relies heavily on globals and `
WP_Query::setup_postdata()`. For the 2.x branches (where `get_post` et al. will no longer exist), this is fixed with `Timber\Post::setup()`, but in this case, the easiest out is probably to continue using `\Timber::query_post()` for now on a 1.9.x project as this returns a `QueryIterator` that will handle all this for you automatically.

@gchtr / @jarednova  / @palmiak Possibly a todo for the 2.x . docs? Paginated content works provided the users uses the 'magic' $context['post'], but the docs should probably mention that it calls `Post::setup` and that a developer should call this if they want parity in function.

**Comment by gchtr** [comment]
@aj-adl The only place where `Timber\Post::setup()` is mentioned now is in https://github.com/timber/timber/blob/2.x/docs/guides/context.md#using-a-custom-post-class.
