### ISSUE TITLE
Dynamically adding items to TimberMenu

### ISSUE THREAD

**Issue by miguelrs** [timber/timber#200]
Let's say I have this nav menu in WP:
- Top Menu
  - Films
    - My Favourite Films
    - Last film I watched
  - More ...

The item _My Favourite Films_ goes to a page, so that's clear. 
But the item _Last film I watched_ is a link to a concrete Post (of custom post type "Films"), which I want to dinamically add to the menu. I mean, I don't want to go the menu editor and select a different film each time I watch a new one, but I want to use always the last added post...

I have a working approach where I created my own classes Film, NavigationMenu, Link, etc... but now I added Timber and I'd like to use the functionality to create menus...

Any ideas? I guess I need to get the ID of the film I want to add, and with that ID I can retrieve the WP_Post object, which I can use to create a TimberMenuItem object... But I don't know how to append it to the TimberMenu in the correct position...

**Comment by JeyKeu** [comment]
Where should this function be added?

**Comment by extravaganza47** [comment]
How do I call the wordpress optional menu fields, like CSS Class and Menu Description?
Thanks.

**Comment by joethuoo** [comment]
I don't follow your question.

**Comment by JeyKeu** [comment]
There is a property named `class` which returns all the classes associated with this menu or menu item

If you want to add additional attributes to your menu change the html as you like it
```php
<nav id="main-navigation"  role="navigation">
    <ul>
        {% for item in menu.items %}
            <li id="menu-item-{{item.ID}}" class=" {{item.class}} ">
                <a href="{{item.link}}">{{item.title}}</a>
            </li>
        {% endfor %}
    </ul>
</nav>
```

**Comment by MelanieMenard** [comment]
Hello,

I'm trying to use this code to dynamically add all my blog post as hidden children (that is, present in the TimberMenu object but not rendered in the html) of my top 'news' page, so that I can put an active state on my 'news' link when the user is visiting a news item (using the timber properties: current_item_parent and current_item_ancestor).

If I add all the blog posts manually to the menu in the WP CMS, it works fine, however I don't want the content editors to have to update the menu every time they write a new post.

Using the above code, I managed to add blog posts to the Timber menu, however current_item_parent and current_item_ancestor does not work for them.

Basically, while I debug, I have 1 blog post X that I set manually as child of PageA in the CMS menu editor, and dynamically as child of PageB using the code above. The dynamically added item is present but when I'm viewing post X, PageA nav item is active but pageB is not.

The code above only sets the properties necessary to display the items in the html, title and url, so I guess whatever property Timber uses to test for current_item_parent and current_item_ancestor is not set.

I searched the Timber plugin codebase for 'current_item_parent' in order to find where and how it was set, to see what it needs form the menu item, but the search did not return anything.

What do I need to add to the code above to get current_item_parent to work?

Many thanks in advance for your help.

Disclaimer: I'm really a JS developer and a total PHP newbie.
