### ISSUE TITLE
Consider removing `filter`/`pluck` filters

### ISSUE THREAD

**Issue by nlemoine** [timber/timber#2010]
Twig recently introduced some useful array methods like `column` (since 2.8.0), `filter`, `map` and `reduce` (since 1.41/2.10.0).

https://github.com/twigphp/Twig/blob/2.x/CHANGELOG

https://twig.symfony.com/doc/2.x/filters/column.html
https://twig.symfony.com/doc/2.x/filters/filter.html
https://twig.symfony.com/doc/2.x/filters/map.html
https://twig.symfony.com/doc/2.x/filters/reduce.html

Timber has its own filters `pluck` and `filter`. The second one makes native Twig `filter` unusable. 

This would probably introduce a BC break. But would you consider this for 2.0+?

**Comment by nlemoine** [comment]
For those who want to use these new filters right now, you can still add them with another name:

```php
add_filter('timber/twig', function($twig) {
    $twig->addFilter(new \Twig_SimpleFilter('array_column', 'twig_array_column'));
    $twig->addFilter(new \Twig_SimpleFilter('array_filter', 'twig_array_filter'));
    $twig->addFilter(new \Twig_SimpleFilter('array_map', 'twig_array_map'));
    $twig->addFilter(new \Twig_SimpleFilter('array_reduce', 'twig_array_reduce'));
    return $twig;
});
```

**Comment by jarednova** [comment]
@nlemoine thanks for the heads-up on those! I think it makes sense to clean those up for 2.0 to match the native abilities in Twig. Overall we're trying to reduce our "custom" layer and pass-along the features of Twig to the end-user

**Comment by rubas** [comment]
> ```
> add_filter('timber/twig', function($twig) {
>     $twig->addFilter(new \Twig_SimpleFilter('array_column', 'twig_array_column'));
>     $twig->addFilter(new \Twig_SimpleFilter('array_filter', 'twig_array_filter'));
>     $twig->addFilter(new \Twig_SimpleFilter('array_map', 'twig_array_map'));
>     $twig->addFilter(new \Twig_SimpleFilter('array_reduce', 'twig_array_reduce'));
>     return $twig;
> });
> ```

FYI: `\Twig_SimpleFilter` is deprecated. You should use `\Twig\TwigFilter` instead.

**Comment by nlemoine** [comment]
@rubas Thanks pointing that out, I know, i just copied/pasted code from [Timber](https://github.com/timber/timber/blob/1.9.4/lib/Twig.php#L208) and didn't pay attention 😉

**Comment by gchtr** [comment]
I think we should keep the `filter` functionality, but rename it. It was introduced in https://github.com/timber/timber/pull/1594 and is basically [`wp_list_filter()`](https://developer.wordpress.org/reference/functions/wp_list_filter/), but as a Twig filter. 

What would be a good name for this instead of `filter`?

- `wp_list_filter`?
- `list_filter`?

**Comment by nlemoine** [comment]
I guess `wp_list_filter` would make more sense as it clearly links that filter to WordPress function. But other filters would have to follow that logic in order to provide consistency.

**Comment by gchtr** [comment]
@nlemoine Which other filters do you mean? I can see that we could make filter naming more consistent with what they do behind the curtains. For example, there’s a filter `sanitize` that calls `sanitize_title()`. So `sanitize_title` would probably be a better filter name.

**Comment by nlemoine** [comment]
Sorry, you're absolutely right, I thought more filters were inherited from WP functions (`pluck` could eventually directly use `wp_list_pluck`). 

I just noticed `action`/`do_action`.

**Comment by gchtr** [comment]
@nlemoine Thanks for mentioning this! For 2.0, our goal is to make the naming of functions and hooks more streamlined. But we didn’t think about Twig filters yet. They definitely deserve some thinking.

I’ll definitely look at `wp_list_pluck()`. If we could use more native WordPress functions instead of writing our own functionality, that would be great.

**Comment by aj-adl** [comment]
@gchtr happy to look at this, here's my thoughts on a starting point

1. add `wp_list_filter` and `twig_array_filter` to Twig, so both are available.
2. change Timber's `filter` to use `twig_array_filter` by default (as this is the new behaviour) while maintaining backwards compatibility.

If the 2nd argument to `filter` is an array, then we call `wp_list_filter` and throw a deprecation notice, if it's a callable then we pass in on to `twig_array_filter`.

Docs should be updated so that `filter` references `twig_array_filter`, and users are encouraged to use `wp_list_filter` to call the associated WordPress function.

This strategy could be used across other filters, such as using `sanitize` to call `sanitize_title` while throwing a deprecation notice.

**Comment by gchtr** [comment]
@aj-adl This seems like a very reasonable plan! Having deprecations will definitely help with the transition. I can’t assign you directly to this issue, but I’d be happy if you could come up with a pull request for this 👍.

**Comment by palmiak** [comment]
@gchtr @aj-adl I started to work on this and before I'll do a PR could just say do you think this is the way to go:
Twig.php
```php
$twig->addFilter(new Twig_Filter('filter', array('Timber\Helper', 'filter_array')));
$twig->addFilter(new Twig_Filter('wp_list_filter', array('Timber\Helper', 'wp_filter_array')));
```

Helper.php
```php
/**
* Filters a list of objects, based on a set of key => value arguments. Uses native Twig Filter.
*
* @since x.x.x
* @param array        $list to filter.
* @param callback|array $arrow function callback used for filtering or array for backward compatibility.
* @param string       $operator to use (AND, NOT, OR). For backward compatibility.
* @return array
*/
public static function filter_array( $list, $arrow, $operator = 'AND' ) {
    if( !is_callable($arrow) ) {
        // Deprecation info.
        return Helper::wp_filter_array( $list, $arrow, $operator );
    }

    return twig_array_filter( $list, $arrow );
}

/**
* Filters a list of objects, based on a set of key => value arguments. Use WordPress WP_List_Util's filter.
*
* @since 1.5.3
* @ticket #1594
* @param array        $list to filter.
* @param string|array $args to search for.
* @param string       $operator to use (AND, NOT, OR).
* @return array
*/
public static function wp_filter_array( $list, $args, $operator = 'AND' ) {
    if ( ! is_array($args) ) {
        $args = array( 'slug' => $args );
    }

    if ( ! is_array( $list ) && ! is_a( $list, 'Traversable' ) ) {
        return array();
    }

    $util = new \WP_List_Util( $list );
    return $util->filter( $args, $operator );

}
```

**Comment by gchtr** [comment]
@palmiak That looks good to me! That’s indeed very elegant with the `is_callable()` check! We can look at all the details in the pull request.

Thanks for working on this!
