### ISSUE TITLE
post.preview causes infinite loops

### ISSUE THREAD

**Issue by pascalknecht** [timber/timber#2041]
## Expected behavior
Twig Template loaded via ServerSideRender renders as wanted.

## Actual behavior
The backend is stuck in an infinite loop. It never reaches to the end of the request until it crashes.

## Steps to reproduce behavior
Create a React component with <ServerSideRender>. Create a block and render any Twig template with {{ post.preview }} in it.

Removing the filter `do_blocks` around the the_content filter solves it. https://github.com/timber/timber/blob/master/lib/PostPreview.php#L290
```
remove_filter('the_content', 'do_blocks', 9);
$text = $this->post->content();
add_filter('the_content', 'do_blocks', 9);
```

@jarednova Any ideas how we could solve this? Should the post preview even apply the_content filter? I think it shouldn't as I had many troubles with that in the past.

## What version of WordPress, PHP and Timber are you using?
WordPress 5.2.2
PHP 7.2
Timber 1.10.1

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
composer

**Comment by gchtr** [comment]
I see different ways to go here:

- Don’t call `$post->content()` from inside `$post->preview()`, but still apply certain required filters. Maybe `wp_texturize` and `wpautop`?
- Make it possible to pass a flag to `$post->content()` so that it doesn’t apply filters. But then again, what would be the benefit compared to directly using `$post->post_content` instead?

This is only the most obvious solution. I guess we need to look at the bigger question: How does fetching a part of the content and building a preview work in the era of Gutenberg, where there’s suddenly blocks in the content that have lots of HTML in them? To be able to get only a part of the content, we would still have to parse blocks. Should we only parse parse paragraph and heading blocks by default and ignore all the rest? Or is getting a preview from Gutenberg a bad idea anyhow and a post excerpt is the way to go?

My gut tells me that the best way would be to decouple the preview from `$post->content()` and the `the_content` filter and only apply what we know works well.

**Comment by jarednova** [comment]
> My gut tells me that the best way would be to decouple the preview from $post->content() and the the_content filter and only apply what we know works well.

... I think this is the right approach. This probably how `{{ post.excerpt }}` (which would be a more WP-familiar way of naming it) should probably work. This would allow us to model against the current way that WP does this, not take on the infinite loop risks, and also not break backwards compatibility

**Comment by corentin-gautier** [comment]
@jarednova I stumbled upon this issue recently : I have a ACF block which uses the relation field to show the title and preview of a list of pages. If two pages reference each other with this block, then the preview will loop forever making the use of .preview really risky. Could the preview function ignore subsequent call to preview ? (make preview aware that it's called inside a preview, and do nothing in that case)

**Comment by herrschuessler** [comment]
@jarednova Maybe running the post content through [excerpt_remove_blocks()](https://developer.wordpress.org/reference/functions/excerpt_remove_blocks/) before generating the excerpt solves this issue?

**Comment by gchtr** [comment]
Thanks @herrschuessler!

I think the `excerpt_remove_blocks()` would be the right function to solve this, since it also allows to control which core or third-party blocks should be preserved using filters.

The Events Calendar plugin solves this with `excerpt_remove_blocks()` as well: https://github.com/the-events-calendar/the-events-calendar/blob/d311fe783ad2992b0e213caf57aaf671eb39d998/src/functions/template-tags/general.php#L1731-L1736

They also use a filter to allow this to be set dynamically: https://github.com/the-events-calendar/the-events-calendar/blob/d311fe783ad2992b0e213caf57aaf671eb39d998/src/functions/template-tags/general.php#L1717.
