### ISSUE TITLE
WooCommerce & Email templates: load php files

### ISSUE THREAD

**Issue by vyskoczilova** [timber/timber#2055]
## Is your feature request related to a problem? Please describe.

Load *.php file when the *.twig is not found for WooCommerce. In some cases, there is better to work with the default WooCommerce files than creating cumbersome twig templates - email templates or checkout/cart page.  There are two reasons for that:

### 1. No access to the WooCommerce variables ###

For example for emails (imagine, I just want to change the email text above order table) I haven't found a way how to do it in Timber. I need to either recreate the whole template in twig (and I haven't found ho to access following variables to call the `do_action `hooks correctly().

`do_action('woocommerce_email_order_details', $order, $sent_to_admin, $plain_text, $email )`

### 2. The ease of updates & maintenance ###

Since you don't have the access to the WC variables sometimes you have to rewrite a couple of variables, turn all the template into the twig and watch if something has updated or not. In many cases is better to copy the PHP file, modify it a tiny a little bit and then check what has changed.

---

I hope that I have not missed something important on how to get WC template variables, but it makes me kind of crazy - whole website is done and I simply can't change the text of emails.

**Comment by jarednova** [comment]
@vyskoczilova thanks for this issue. I have to confess, I've never worked with WooCommerce so I'm not able to give detailed feedback or insight. But based on what you're describing it sounds like this could be related to adding or utilizing a hook within `Timber::render` or `Timber::compile` to send things to a PHP file instead of a TWIG file?

Is this something you'd be interested in taking on? I'd love to make our integration with WC more robust

**Comment by vyskoczilova** [comment]
Hi, sorry for the late reply, I was out for long break. I'd love to help and have a look on it with you, if you wish - just get on touch at WC slack (vyskoczilova) or karolina@kybernaut.cz.

I'll test twig/php file usage more carefully and get back to you.

1) However, the problem is with the case that WC custom templates structure could be pretty awful to redo it in twig because of their's complexity: https://github.com/woocommerce/woocommerce/blob/master/templates/checkout/review-order.php

2) the second problem (the bigger one) is that they do pass variables to the templates, the very simple one is here: https://github.com/woocommerce/woocommerce/blob/master/templates/emails/admin-new-order.php having `$email_heading`,`$email `, `$order`, `$sent_to_admin`, `$plain_text` and `$additional_content ` and I haven't found a way how to access them in twig file, I think the problem is that the variables are prepared "too late".

**Comment by gchtr** [comment]
@vyskoczilova Did you already have a look at the [Timber Integration for WooCommerce](https://github.com/mindkomm/timber-integration-woocommerce)? We have [Automatic Twig Partial Selection](https://github.com/MINDKomm/timber-integration-woocommerce/blob/master/docs/usage.md#automatic-twig-partial-selection), where you can replace single WooCommerce templates with Twig templates. Most of the WooCommerce variables are then available under the `wc` variable in Twig.

I also wanted to change the default email text for a couple of projects. And I ended up writing a small plugin for it, because I didn’t want to rebuild all the email templates in Twig: https://github.com/mindkomm/woocommerce-email-text-edit. Maybe that helps.

**Comment by vyskoczilova** [comment]
@gchtr thanks, it looks good, I will dig more deeply into, at least it solves the problem with PHP files over timber ones. However, if there would be a way how to get into context the rest of the variables assigned by WC it would be perfect.
