### ISSUE TITLE
Fatal error: Uncaught Twig_Error_Syntax: Unknown "switch" tag

### ISSUE THREAD

**Issue by muuvmuuv** [timber/timber#2063]
## Expected behavior

Should make use of Twig switch tag. I guess there is one, because my Twig VSCode plugin suggested it to me when I typed `switch`.

If not this is a feature request for it. Here is something I found from someone: https://gist.github.com/maxgalbu/9409182

## Actual behavior

Breaks page.

## Steps to reproduce behavior

```twig
{% switch value %}

  {% case "one" %}
    HI

  {% default %}
    DEFAULT

{% endswitch %}
```

## What version of WordPress, PHP and Timber are you using?

WordPress: 5.2.2
PHP: 7.4.x
Timber: 1.9.2

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

from WordPress plugin installer

**Comment by muuvmuuv** [comment]
The flat file CMS __Grav__ get one too: https://learn.getgrav.org/16/themes/twig-tags
maybe it's just copy & paste.

**Comment by palmiak** [comment]
I see that craft CMS has it out of the box, but Twig itself doesn't.

I don't think we should add this as part of core.

czw., 29 sie 2019, 15:57 użytkownik Marvin Heilemann <
notifications@github.com> napisał:

**Comment by muuvmuuv** [comment]
Why not @palmiak ? I think it would lead to more readable code. In my case it would look way better than a lot of `elseif` cases.

**Comment by gchtr** [comment]
By adding it to Timber core, we would also have to maintain it in Timber core. I guess it would be better to have this as a separate extension that comes as a Composer package. In the future, we will probably have more separate packages for extensions and integrations rather than everything in core.

Timber can already be extended with features like a switch statement. Using your [linked example](https://gist.github.com/maxgalbu/9409182), you could add it like this:

```php
add_filter( 'timber/twig', function( \Twig\Environment $twig ) {
    // Add the Switch token parser.
	$twig->addTokenParser( new Twig_TokenParser_Switch() );

    return $twig;
} );
```

Of course you would have to require the `Twig_TokenParser_Switch` and `Twig_Node_Switch`  classes separately first.

**Comment by muuvmuuv** [comment]
Sounds reasonable @gchtr. Thank you for the fiddle. I'll close this and add it like you suggested.
