### ISSUE TITLE
Timber 2.0 : time frame for release & contributing

### ISSUE THREAD

**Issue by romainmenke** [timber/timber#2079]
Hi,

Was looking through the 2.0 project and issues and couldn't find a time frame for the 2.0 release. Is there a target for when to release a 2.0 version?

I fully understand if you do not want to commit to any given point in time for a 2.0 release.

Related : is there any low hanging fruit to help a 2.0 release along?

**Comment by jarednova** [comment]
@romainmenke thanks for your interest and the flurry of PRs you've been sending our way. A few of us are actively trying to wrap up some loose ends to get things set (unfortunately, there are the day jobs we have to fight against). I did a quick sweep of our [board](https://github.com/timber/timber/projects/4) and saw this issue hanging out as a todo for 2.x:

[#1837: Deprecate timber/loader/paths in favor of timber/locations](https://github.com/timber/timber/issues/1837)

Is that something you'd be up for tackling? @gchtr any ideas after that?

**Comment by gchtr** [comment]
We just released a first beta for Timber 2.0: https://github.com/timber/timber/releases/tag/2.0.0-beta.1.

Unfortunately, we have no final release date yet and we don’t want to commit to one, because we all work on it in our free time. Thank you so much for understanding.

We’re happy if you can test out the beta and report any bugs. Or if you feel like tackling known bugs for 2.0, [here’s a list of issues](https://github.com/timber/timber/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A2.0).
