### ISSUE TITLE
Update ::get_post() and ::get_posts() signature

### ISSUE THREAD

**Issue by acobster** [timber/timber#2090]
## Is your feature request related to a problem? Please describe.

Per #2073 we are disabling direct instantiation of Posts and forcing all 

### Update `Timber::get_post()`

Update the method signature to:

```php
public static function get_post( $query = false );
```

This gets rid of the second argument, `$PostClass`, whose functionality will be subsumed (much more nicely!) by [Class Maps](https://github.com/timber/timber/blob/2.x-docs-api/docs/guides/class-maps.md).

### Update `Timber::get_posts()`

Update the method signature to:

```php
public static function get_posts( array $query = [], array $options = [] );
```

This also eliminates the `$PostClass` param as above, and consolidates Timber-specific options into a single array. Note that both are optional. This method will behave more or less the same as it has within archive templates.

## Alternatives and context

* [Upgrade guide proposal](https://github.com/timber/timber/blob/2.x-docs-api/docs/upgrade-guides/2.0.md)
* [Timber 2.0 Context Guide proposal](https://github.com/timber/timber/blob/2.x-docs-api/docs/guides/context.md)
* [Class Maps](https://github.com/timber/timber/blob/2.x-docs-api/docs/guides/class-maps.md)
* [Posts API in Timber 2.0 proposal](https://github.com/timber/timber/blob/2.x-docs-api/docs/guides/posts.md)
* More discussion: #2073 #1793

**Comment by gchtr** [comment]
Looking good 👍.

What we have to consider for `Timber::get_posts()` is #1957. In #1813 we added logic to mimick the default behavior for `get_posts()` in WordPress. This produced errors, so we made it optional with a filter in #1989. For 2.0, I guess we could **deprecate that filter** and add a proper description with a [link to the documentation](https://github.com/timber/timber/blob/2.x-docs-api/docs/guides/posts.md#the-difference-to-get_post) that lists the differences and the arguments that need to be passed to `Timber::get_posts()` to mimick the default behavior.

I’m pinging @palmiak here, because he started the discussion about `Timber::get_posts()`.

**Comment by acobster** [comment]
Done!
