### ISSUE TITLE
Factories reboot

### ISSUE THREAD

**Issue by acobster** [timber/timber#2093]
## Is your feature request related to a problem? Please describe.

The requirements for Factories has changed a lot since the long discussion on #1793 and #1219 :

* Factories will no longer be exposed publicly. They will constitute a completely internall API to be used by the `Timber\Timber` class.
* Instead of exposing Factories externally, we're exposing a small set of filters that will be used _inside_ Factories to instantiate the correct class for a given post type, taxonomy, etc.
* The requirements for Factories is now being driven by the new [API proposal](https://github.com/timber/timber/pull/2073) for `Timber::get_posts()` and friends.

## Goals

The goals for implementing Factories are:

* To provide a centralized layer for instantiating `Timber\Core` instances (`Post`, `Term`, etc.) and their corresponding collection classes (e.g. `PostCollection`).
* To eventually replace `PostGetter` etc., to be called directly from `Timber::get_*` methods (e.g. `::get_posts`).
* To provide a centralized place to implement filters like `timber/post/classmap` as described in the [Class Map proposal](https://github.com/timber/timber/blob/2.x-docs-api/docs/guides/class-maps.md).
* To incorporate the best ideas from #1793 and #1219 in a way that matches up with the new API proposal

**Comment by FlyingDR** [comment]
As promised - here are some minor things that I've noticed into factories code:

[This](https://github.com/timber/timber/blob/891f3132a7951a673c163aa3cde22a06fb8324aa/lib/Factory/PostFactory.php#L99-L101) is not completely correct because you have different type checking rules [here](https://github.com/timber/timber/blob/891f3132a7951a673c163aa3cde22a06fb8324aa/lib/Factory/PostFactory.php#L16-L18). 

Actually it looks like whole purpose of `PostFactory::is_numeric_array()` is to distinguish it from `WP_Query` arguments passed as array. If I'm correct - then it may be better to check if given array is associative or not, because `WP_Query` arguments array can be only associative and, for example `['post_id'=>123]` will pass your current check.

It may look something like this:
```php
private function is_numeric_array($arr): bool
{
    return is_array($arr) && empty(array_filter($arr, '\is_string', ARRAY_FILTER_USE_KEY));
}
```

**Comment by FlyingDR** [comment]
Isn't [this](https://github.com/timber/timber/blob/891f3132a7951a673c163aa3cde22a06fb8324aa/lib/Factory/PostFactory.php#L70-L75) needs to be cached? If there is many `Post` instances will be created - it will result into (probably minor, but still) performance impact.

Besides this `get_post_class()` contains potential source of `TypeError` fatal errors: Return type of `build()` method is [explicitly defined](https://github.com/timber/timber/blob/891f3132a7951a673c163aa3cde22a06fb8324aa/lib/Factory/PostFactory.php#L88) as `CoreInterface`, but [there](https://github.com/timber/timber/blob/891f3132a7951a673c163aa3cde22a06fb8324aa/lib/Factory/PostFactory.php#L85) is no check for a fact that `$class` is actually instance of `CoreInterface`. It can be because information came from untrusted source. It needs to be decided what to do in this case. Normally code should throw exception in such case.

**Comment by FlyingDR** [comment]
Timber 2.x [currently targets](https://github.com/timber/timber/blob/03bf4bf20dc763895b776b7f51ef856050821da8/composer.json#L31) to PHP 7.0 and @jarednova gives his concerns on this topic [here](https://github.com/timber/timber/issues/1863#issuecomment-578565944). 

However current version of `PostFactory` is not compatible with PHP 7.0 due to [use](https://github.com/timber/timber/blob/891f3132a7951a673c163aa3cde22a06fb8324aa/lib/Factory/PostFactory.php#L64) of `iterable` type which was [introduced](https://www.php.net/manual/en/language.types.iterable.php) into PHP 7.1

**Comment by FlyingDR** [comment]
Additionally `object` type definition, used [here](https://github.com/timber/timber/blob/891f3132a7951a673c163aa3cde22a06fb8324aa/lib/Factory/PostFactory.php#L49), is only supported [since](https://www.php.net/manual/en/migration72.new-features.php#migration72.new-features.object-type) PHP 7.2

**Comment by acobster** [comment]
@FlyingDR thanks so much for your notes! Lots of good stuff here.

> it may be better to check if given array is associative or not

That is exactly what `::is_numeric_array()` is doing. I think what you're missing is the fact that it's looping over the _keys_ and not the values in the array. It's essentially the same as your implementation, except that `array_filter` will always look at every key instead of bailing early when it finds one non-int key.

> for example `['post_id'=>123]` will pass your current check.

No, it won't, for the same reason as above. :)

> Isn't [this](https://github.com/timber/timber/blob/891f3132a7951a673c163aa3cde22a06fb8324aa/lib/Factory/PostFactory.php#L70-L75) needs to be cached? If there is many Post instances will be created - it will result into (probably minor, but still) performance impact.

I don't know that there's a strong case for caching this in particular. As you say it's probably a minor performance impact. And it would preclude certain use-cases of adding `timber/post/classmap` in different parts of the lifecycle. Consider:

```php
$context = Timber::context(); // this will call the post/classmap filter, and thus cache the result

add_filter('timber/post/classmap', function($map) {
  // this will not run if we cache the first result
  return array_merge($map, ['my_post_type' => MyPostClass::class]);
});

$myPost = Timber::get_post(123);
get_class($myPost); // expect MyPostClass; get \Timber\Post
```

Finally, I think all your points about type declarations are good ones we need to consider. I'm leaning toward requiring >= 7.1 so we can get nullable types on the public API methods, and `iterable`. I already dropped the `object` declarations in one factory; just haven't gotten around to the rest. We'll continue this discussion on #1836 once we've made more headway on the 2.x API implementation.

Thanks again!

**Comment by acobster** [comment]
Factories have been into 2.x!
