### ISSUE TITLE
twig date filter features not working as expected

### ISSUE THREAD

**Issue by columbian-chris** [timber/timber#2177]
When using date filter in Timber 1.14, `{{ "now"|date }}` returns the time in UTC, which appears to be my default set timezone (checked with `date_default_timezone_get()`), although my PHP default timezone is set to `America/Los_Angeles` (checked with `php --ri date` from command line).  It does not utilize the timezone set in my Wordpress settings in the admin backend.

When I use `date_default_timezone_set()`, that doesn't change (not expecting it to, just stating for reference).  When I specify the timezone (e.g. `{{ "now"|date('g:ia', 'America/Los_Angeles') }}`), it still returns the time in UTC.

This method as suggested in the [Twig docs](https://twig.symfony.com/doc/3.x/filters/date.html) didn't have any affect:
```php
$twig->getExtension( \Twig\Extension\CoreExtension::class )->setTimezone('America/Los_Angeles');
```

**Comment by gchtr** [comment]
Based on your issue in https://github.com/timber/timber/issues/2104, I created a pull request for fixing these Twig compatibility issues you’re seeing in https://github.com/timber/timber/pull/2135.

Turns out that in WordPress you should never use `date_default_timezone_set()`! Working with dates and times doesn’t work like you’re maybe used to in normal PHP. A good resource with the most up to date information is the [Date/Time component improvements in WordPress 5.3](https://make.wordpress.org/core/2019/09/23/date-time-improvements-wp-5-3/) post. I’ve set up a new [Date/Time Guide](https://github.com/timber/timber/blob/2.x/docs/guides/date-time.md) that should help to understand the differences as well as what this means for working with Dates in Timber.

This will all come with Timber version 2. Until that version is released, working with Twig date functionality will probably not work as expected.

**Comment by Levdbas** [comment]
Closing this as stale and since it's already tackled in 2.x
