### ISSUE TITLE
[filter:time_ago] isn't translated correctly

### ISSUE THREAD

**Issue by muuvmuuv** [timber/timber#2214]
The twig filter `time_ago` isn't properly translated. Both past and future variables are hardcoded in english.

> /wp-content/plugins/timber-library/lib/Twig.php:367

Change this:

```php
		if ( $from < $to ) {
			return sprintf($format_past, human_time_diff($from, $to));
		} else {
			return sprintf($format_future, human_time_diff($to, $from));
		}
```

to this:

```php
		if ( $from < $to ) {
			return sprintf(__($format_past), human_time_diff($from, $to));
		} else {
			return sprintf(__($format_future), human_time_diff($to, $from));
		}
```

## Expected behavior

Should print:

English: 2 days ago
German: Vor 2 Tagen

## Actual behavior

English: 2 days ago
German: 2 Tage ago

## Steps to reproduce behavior

```twig
{{ <date> | time_ago }}
```

## What version of WordPress, PHP and Timber are you using?

Latest

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

Wordpress plugin

**Comment by gchtr** [comment]
Thanks @muuvmuuv to take the time to create an issue for this! While working on the documentation for dates and times in Timber, I stumbled over the same problem with the `time_ago()` function. And I think there’s actually a bigger problem.

But first, a quick solution for you. You can pass the translated string that should be used to `time_ago()`.

```twig
{{ date|time_ago(null, 'Vor %s') }}
```

## The problem

Here’s the function that is being called by the `|time_ago` filter:

https://github.com/timber/timber/blob/3eaddbc87a56aea44a37cb3ffda24e4b1bd0041b/lib/Twig.php#L353-L370

That function accepts two parameters with English strings: `%s ago` and `%s from now`.

If I want to translate these strings, I have to pass the translations in every instance where I want to use `time_ago()`. Also, if I only want to change the strings, I’d have to pass in the first two arguments `$from` and `$to` as well.

Timber uses very few instances of translatable strings. Mostly translatable strings are used in helper functions like `time_ago()` mentioned above or [`Timber\Twig::add_list_separators()`](https://github.com/timber/timber/blob/3eaddbc87a56aea44a37cb3ffda24e4b1bd0041b/lib/Twig.php#L378) as well as in debug output.

I wondered whether we could improve this. I see a couple of ways to approach this.

### Rely on Core Translations

As proposed by @muuvmuuv here, we could rely on Core Translations.

```php
sprintf( __( $format_past ), human_time_diff( $from, $to ) )
```

But WordPress advises plugins and themes to never rely on core translations, but always provide translations separately. So we shouldn’t do that.

### Introduce translation files

We could create a .pot file for all translatable strings appearing in Timber. For this, we would have to introduce a text domain for Timber:

```php
public static function time_ago(
    $from,
    $to = null,
    $format_past = __( '%s ago', 'timber' ),
    $format_future = __( '%s from now', 'timber' )
) {
    // Function body.
}
```

And then we would ask developers to create .po and .mo files with translations for the languages they need. However, because Timber won’t live in the WordPress plugin directory, we **couldn’t make use of** [translate.wordpress.org](https://translate.wordpress.org/).

It’s not so hard to load a translation from a directory loaded through Composer, though. I’ve done this quite a few times. But I couldn’t say yet whether this would work with a plugin like [Loco Translate](https://wordpress.org/plugins/loco-translate/).

### A couple of other ideas

Introducing translation files wouldn’t solve the question for how we could make `time_ago()` easier to use. If you need a different string than the default one, you would still have to provide your own translation somehow. And if we only have a couple of translations, it might not be worth it.

Here are some quick ideas:

#### Make translations filterable

Use a PHP filter that contains all default translations for Timber. When you hook into that filter, you could change the defaults.

```php
add_filter( 'timber/translations' function( $translations ) ) {
    $translations['time_ago_past'] = __( '%s ago', 'my-custom-text-domain' );
    $translations['time_ago_future'] = __( '%s from now', 'timber' );

    return $translations;
}
```

#### Try to remove transatable strings completely

If we only have a couple of translations, we could maybe rework how functions that rely on translations work.

For `time_ago()`, this could mean that you have an `is_past()` or an `is_future()` function that you could use to display different strings.

```twig
{% if date|is_past %}
    {{ __('%s ago', 'my-custom-text-domain')|format(date|time_ago) }}
{% else %}
    {{ __('%s from now', 'my-custom-text-domain')|format(date|time_ago) }}
{% endif %}
```

**Comment by muuvmuuv** [comment]
IMO, the translations Timber is using are sooo simple that using the build in would be fine. Filtering and creating if clauses isn't very user-friendly, it requires too much custom logic for an "add and forget about it" function.

**Comment by gchtr** [comment]
> IMO, the translations Timber is using are sooo simple that using the build in would be fine.

Turns out, I maybe didn’t look close enough. There are really only a few translations.

> Filtering and creating if clauses isn't very user-friendly, it requires too much custom logic for an "add and forget about it" function.

You’re right! This is mostly just me exploring solutions, so that we can weigh the pros and cons.

I still think that it’s not the best idea to rely on WordPress Core Translations, but for now, it should work. In case there will be more strings to translate in the future, this is definitely not the best approach.

I added a patch in #2215. And I also added tests, to make sure this is going to work in the future or create a flag if it doesn’t.
