### ISSUE TITLE
Post view count

### ISSUE THREAD

**Issue by flip111** [timber/timber#2226]
Could the amount of views/reads of a post be including in the `Timber\Post` class?

**Comment by palmiak** [comment]
Hi @flip111 

Please post your question to [StackOverflow](http://stackoverflow.com/questions/tagged/timber) using the Timber tag. To help us keep (or start to keep) the Issues section a bit cleaner, we're going to close support question-ish issues. StackOverflow is the best place for these — thanks!

**Comment by flip111** [comment]
Hi @palmiak this is not a support question but a feature request. Please re-open the issue.

**Comment by jarednova** [comment]
Hi @flip111, thanks for this and some of the other items you posted about. Post counts are something that is beyond the scope of what Timber is meant to do. Our project is really just about the management and display of WordPress data to templates. 

Counting post views is a particular area of trouble because there are so many ways to do it (using PHP, using JS, caching, etc.). I'd recommend looking at these to see which will integrate most easily with Timber. If there's a particularly popular post views plugin out there (not an area I've looked at recently), I'd be up for thinking of how to formalize that (with official docs or integration code)

**Comment by flip111** [comment]
Hi @jarednova i was expecting that wordpress keeps track of this. And possible expose it through this function

https://developer.wordpress.org/reference/functions/get_post_meta/

However i can't find this information in the database, so i guess it doesn't come with wordpress out of the box.

Issue can stay closed.
