### ISSUE TITLE
code style fixing ?

### ISSUE THREAD

**Issue by flip111** [timber/timber#2229]
Would it be a good idea to apply https://github.com/FriendsOfPHP/PHP-CS-Fixer ??

Maybe to setup a custom profile in case it needs some different syntax in some cases.

**Comment by gchtr** [comment]
Hey @flip111, thanks for the suggestion. We’re aware that we can improve our coding style. This is something that we keep track of in #2166. We didn’t decide yet which tools we’re going to use, but PHP-CS-Fixer is surely one of those we’re going to look at.

I’m going to close this issue, because it’s already on our todo list ;).

**Comment by flip111** [comment]
Thank you @gchtr
