### ISSUE TITLE
Adding pre filter to detect get content for preview(excerpt)

### ISSUE THREAD

**Issue by tscontenna** [timber/timber#2252]
## Is your feature request related to a problem? Please describe.

Some plugin have the feature to replace content automatically using filter `the_content` .
 `ez-toc`, `add-to-any` etc.

To output `{{post.preview}}` , the Timber\Post class uses `$this->content()` method, it calls `the_content` filter.

https://github.com/timber/timber/blob/f1fdbeb73eb897d227fda01b65da685abaeba830/lib/Post.php#L954

This causes the problem that post.preview becomes empty.
Because very long html code is generated for content in `the_content` filter, and it is to be removed by strip_tags().

## Describe the solution you’d like

Please provide filter called before getting post content for preview, to disable plugin temporarily.

```php

   add_filter('timber/post/before_get_content_for_preview", function($post) {
     $this->removed = remove_filter('the_content', 'my_plugin_content_filter');
  });

   add_filter('timber/post/after_get_content_for_preview", function() {
     if ($this->removed) add_filter('the_content', 'my_plugin_content_filter');
    });

```

It may be  better to use `before_get_content` instead of the name `before_get_content_for_preview`.
Then providing `for_preview`  as an extra argument named like `$context`, and call it in `content()` method.

This fix needs adding 3rd argument to `Timber\Post::content($page,$len)`.
But this enables subclass to override `content() ` method to return different result by the context.

```php
  public function content( $page = 0, $len = -1 , $context) 
``` 

## Describe alternatives you’ve considered

I have considered overriding `preview()` method and returning subclass of PostPreview object.
But the `PostPreview->run()` method is too long to change.
If I change it in subclass, it may be incompatible in future update.
I only want to disable the_content filter for some plugin easily.

Thanks .

**Comment by jarednova** [comment]
@tscontenna thanks for the overview and helpful thinking. I wonder if it'd be most helpful to allow users to override/filter the call to `$this->post->content();` regardless of how they intend to use it. This would work both for your situation and others that are based on different dependencies. Something like ...

```php
$text = $this->post->content();
$text = apply_filters('timber/post_preview/content', $text);
```

You could the use this hook to substitute whatever output a user desired, completely configurable both for ez-toc, add-to-any, etc. You could also imagine that on something like a WooCommerce page, a user could designate a certain item description field as the "content" they want to preview (instead of the general page content). Would this approach address the situation you described?

**Comment by Levdbas** [comment]
Closing this as a stale issue. @jarednova , if you think we still need to address this, please reopen.
