### ISSUE TITLE
Multisites get all posts

### ISSUE THREAD

**Issue by Drfloo** [timber/timber#2269]
Hi there !

For a website i need to get all the post ( even some postype later ) from the other sites into the main site.

So i try something like this in my search.php

```
$context = Timber::context();
$context['title'] = 'Search results for ' . get_search_query();

$sites = Timber::get_sites();

foreach ($sites as $site) {
    switch_to_blog($site->blog_id);
    // fetch all the posts 
    $query = Timber::get_posts();
    foreach ($query as $post) {
        $blog_posts[] = $post;
    }
    restore_current_blog();
    // display all posts
}

$context['posts'] = $blog_posts;
Timber::render( $templates, $context );
```

I first use the PostQuery but it didn't work, then i tried this and this doesn't work to. He gets me the posts from the main site. 

But i use the get_posts from wordpress it's working.

Can you help me with that ?

Did you do some global post search on your side ? 

Thanks a lot :D

**Comment by jarednova** [comment]
I'm gonna see about chasing this one down — stay tuned!

**Comment by jarednova** [comment]
@Drfloo thanks for the issue! In my investigations thus far, there does seem to be an issue where if you send NO arguments to `Timber::get_posts()` within multisite, you don't receive results. 

Try re-stating what you want in there rather than relying on the defaults. For example:

```php
$query = Timber::get_posts(['post_type' => 'post']);
```

... I still want to supply a true "fix" — but hopefully that can at least get you the functionality you need for now.

**Comment by gchtr** [comment]
Isn’t this the same issue as in https://github.com/timber/timber/issues/1434#issuecomment-593082423? When using `get_post()`, WordPress will prepare the whole post object and already fill in data like the permalink. In Timber, we do this only when the data is first requested, which is probably not in PHP, but in the Twig template. In this case, that’s too late and Timber will call `get_permalink()` from the current blog.

You would have to prepare that data you need for each post in your array. So if you need the permalink, you would add a `link` entry and use `$post->link()` as a value.

```php
foreach ($sites as $site) {
    switch_to_blog($site->blog_id);

    // fetch all the posts
    $query = Timber::get_posts();

    foreach ($query as $post) {
        $blog_posts[] = [
			'title' => $post->title(),
			'link'  => $post->link(),
			// Add more data here …
		];
    }

    restore_current_blog();
    // display all posts
}
```

Or am I missing something here?

I opened an issue to tackle this with better documentation in #2207. Preparing all the data you need would probably be the easiest solution. The same pattern has to be used when you prepare data that will be used in JavaScript.

Otherwise I’m imagining we would have to use a function like `ms_is_switched()` (checks if `switch_to_blog()` is in effect) and prefill the data when we’re in that context. But that would be a huge performance hit, and it would probably create a whole chain of other problems.

**Comment by jarednova** [comment]
@gchtr I don't know how you have a memory for these things! Yes #1434 nicely summarizes the situation and limits. A lot of this is just inherit in the WP architecture that silos the sites in multisite and makes it difficult to interact across them. A worthy project would be to make this smoother/easier, but I believe that's beyond the scope of Timber. Here's a link I found of a paid plugin that does exactly this: https://rudrastyh.com/plugins/get-posts-from-all-blogs-in-multisite-network

@Drfloo I'm going to close this for now along with #2279. My recommendation is to gather whatever posts you need via explicit queries ...

```php
$query = Timber::get_posts(['post_type' => 'post']);
```

Unfortunately WP's "loop" is not reliable, but all the more so when switching across sites in Multisite.
