### ISSUE TITLE
post.content function strips inconsistently out iframe if exposed to javascript in $twig->addFunction

### ISSUE THREAD

**Issue by kuworking** [timber/timber#2272]
Likely it is not a bug, but it could be

__The aim__: to expose `{{ post.content }}` to JavaScript

__The problem__: when done in functions.php, tags as `iframe` are striped out, where the filter `wp_kses_allowed_html` doesn't seem to work

__What I would expect__: that calling the function `post.content` in `php` would produce the same result as when called from `twig`

```js
// this code works, in a page.twig
// the lack of ";" in these 2 lines is necessary
  <script>
    var content = {{post.content|json_encode}}
    var content2 = {{post|json_encode}}
    console.log(content); // iframe is there
    console.log(content2); // iframe is there
  </script>
```

this code does not work, and cannot find out why
```php
// in page.twig
  <script>
    var content = {{ expose_post(post)|json_encode}}
    console.log(content); // iframe is NOT there
  </script>
```

```php
// in functions.php
$twig->addFunction(new Timber\Twig_Function('expose_post', function ($post) {
	return [
		'content' => $post->post_content, 
	];
}));
```

Maybe it is in this filter https://github.com/timber/timber/blob/d160d7a88144969dd196abeb513816a905eea690/lib/Post.php#L1227 but this is happening in both places (?)

My workaround is to expose the content part of the post in `twig` and not in `php`, but what is that I am not understanding?

**Comment by kuworking** [comment]
Found here https://stackoverflow.com/questions/26750626/how-to-post-post-content-as-html

So I do have to apply the filter

```php
$twig->addFunction(new Timber\Twig_Function('expose_post', function ($post) {
	$content = apply_filters('the_content', $post->post_content);
	return [
		'content' => $content, 
		];
	}));
```

But I don't understand why do I need to apply the filter here and not if done through twig (through the same method supposedly)

**Comment by gchtr** [comment]
The `$post->post_content` property is the raw post content. By calling the `$post->content()` method, the raw content is passed through the `the_content` filter.

So what I assume you should probably do is to use `$post->content()` instead of `$post->post_content`:

```php
$twig->addFunction(new Timber\Twig_Function('expose_post', function ($post) {
	return [
		'content' => $post->content(), 
	];
}));
```

> So I do have to apply the filter
> 
> ```
> $twig->addFunction(new Timber\Twig_Function('expose_post', function ($post) {
> 	$content = apply_filters('the_content', $post->post_content);
> 	return [
> 		'content' => $content, 
> 		];
> 	}));
> ```
> 
> But I don't understand why do I need to apply the filter here and not if done through twig (through the same method supposedly)

This solution works because you’re mimicking what `$post->content()` does. It’s totally okay to do it like that.

In Twig, when you write `{{ post.content }}`, it will also call the `$post->content()` method, even if you don’t use the parenthesis `()` that you normally use to call that method in PHP.

So

- When you use `{{ post.content|json_encode }}`, it will encode the content after the `the_content` filter is applied.
- Using `{{ post|json_encode }}` to convert a PHP object to JSON is not a good idea, because a post object contains methods that will not be called automatically when you convert it to JSON. It’s not like an array that already has all the data. You can read more about this problem in the [Serialization section](https://timber.github.io/docs/v2/guides/posts/#serialization) of the new documentation for Timber v2, the upcoming version. Of course that functionality doesn’t work yet, but it illustrates the problem.

Does this help? :)

**Comment by kuworking** [comment]
Yes, absolutely! thanks a lot for the lengthy explanation, it is now 100% clear :D

**Comment by gchtr** [comment]
You’re welcome 👍
