### ISSUE TITLE
Template inheritance in child theme 

### ISSUE THREAD

**Issue by ghost** [timber/timber#2372]
I am facing an issue extending the parent theme template in child theme. 
I have the following **parent theme** structure 

```sh
other files...
parent-theme/templates/navigation.twig
parent-theme/templates/menu.twig
parent-theme/templates/footer.twig
```

In my child theme, if I do this: 
```
child-theme/templates/navigation.twig
```

I can replace the entire content of navigation.twig from the parent theme. But if I do this in this file in the child theme: 

```twig
{% extends "navigation.twig" %}

{% block main %} my child modifications {% endblock %}
```

I get this error: 
``` 
Fatal error: uncaught error: maximum function nesting level of '256' reached ... plugins/timber-library/vendor/twig/...
```

what is the proper way to extend twig files from parent theme in the child theme?

**Comment by landwire** [comment]
I don’t know a Solution, but:
Interesting use case! I guess twig/timber cannot differentiate which template you are calling. It first looks in the child theme.

Would that be possible with a custom twig extension? Something like: 
{% extendsParent "navigation.twig" %}

**Comment by devquestionz** [comment]
so what would be a good solution to make changes to those parent theme templates? 
I am wondering if anyone has done something similar to this and what is their approach

**Comment by landwire** [comment]
At the moment I copy the whole file to the child theme and then I make any modifications there, directly in that file.

**Comment by landwire** [comment]
Is it ok to keep this open to see what any of the Timber experts say?

**Comment by zepich** [comment]
I know, this issue was opened a half a year ago, but i tried to find a better solution today when i found this issue without a solution, so i would like to post a solution for this issue, in case someone else will find this issue in the future.

A solution is to register a namespace in Timber/Twig. With the namespace, you can target the template file from the parent theme you want to extend.

Example (IMPORTANT: this is untested code here but i use namespaces in my own project exactly for this use case):

`parent-theme/functions.php`
```php
function timberAddNamespace(Twig_Loader_Filesystem $loader)
{
    $loader->addPath(get_template_directory() . '/templates', 'parent');
        
    return $loader;
}
add_filter('timber/loader/loader', 'timberAddNamespace');
```

Add the path with the template files from the base theme to the loader. The first parameter is the path, the second is the name of the namespace. You can also choose a different namespace name like 'base' or something else if you want.

After registering the namespace, you can use it in your timber files in the child theme:

`child-theme/templates/navigation.twig`
```twig
{% extends "@parent/navigation.twig" %}

{% block main %}Child main block{% endblock %}
```

The `@parent` is the namespace name, so if you use something else than 'parent' you have to update the part after the @.

**Comment by Levdbas** [comment]
Little late to the party but I am doing the same thing but if just works out of the box.

In my parent theme i got a card-wrap.twig that I extend from within my child themes. This way I can create a card-person.twig for example and have the same wrapper. I haven't done any modifications as you mentioned @zepich . Wondering If I misunderstand the issue here or there is something else at play.

**Comment by zepich** [comment]
I think you have a different situation @Levdbas 

I haven't tested, what you've wrote, but in general it makes sense for me. Both of your files have a different name. This means, TWIG is searching the file "card-wrap.twig" in the child theme but can't find a file with this name, so the search continues in the parent theme where it finds the file.

In my case and the case of the creator of the issue we have the same file in both themes. If you extend 'navigation.twig' in the child theme, TWIG will load the 'navigation.twig' from the **child** theme which results in the error message in this issue (nesting level issue).

That's the reason why you have to define a namespace for the parent theme and then extend exactly the twig file you want, in example the one from the parent theme.

You can test that by creating a file card-wrap.twig in your child theme in which you extend the card-wrap.twig. You should see the same error message...
