### ISSUE TITLE
Menu/Item API: 1-based depth vs. 0-based level

### ISSUE THREAD

**Issue by acobster** [timber/timber#2401]
`Menu::$depth` is 1-based but `MenuItem::$level` is 0-based. This should probably be made consistent; now would be a good time to make such a breaking API change.

MenuItem level is (I think) an older part of the API so there may be more code relying on it; on the other hand, 1-based is more intuitive IMHO. But I don't really have a strong opinion either way (beyond thinking we should change one or the other).

**Comment by gchtr** [comment]
Yes, but I really don’t have a strong opinion about whether 0-based or 1-based makes more sense, either. WordPress seems to use `0` as a default for `$depth` in the menu walkers. Maybe that‘s a standard to work with?

**Comment by acobster** [comment]
Good call. Let's go with 0-based then!

**Comment by gchtr** [comment]
I looked closer what this means. The `depth` parameter in `wp_nav_menu()` has the following description:

```
@type int    $depth    How many levels of the hierarchy are to be included. 0 means all. Default 0.
```

So `0` is the default and means that the depth is ignored. If I use `1` as a depth, then only the first level will be included. I think we shouldn’t change this, because that’s the standard for WordPress. Otherwise, the WordPress filters that we apply inside `Menu` would break compatibility with WordPress.

I think I wouldn’t actually change anything here. To me, it makes sense as it is. The level is actually an index and indices are mostly 0-based in programming. The depth however is more like a count («How many levels do you want to include?»), for which we should use the 1-based approach.

@jarednova @nlemoine What do you think?

**Comment by gchtr** [comment]
> Just to make sure we're 💯 : It seems the origin of the issue is based on the idea of a 1 vs. 0 based indexing?

Yes, I think you got that right.

If we can look at `$depth` as a count, I also think it makes sense that WordPress chose `0` to return all items. Using `0` to make the menu return the first level (remember the question «How many levels do you want to include?») wouldn’t make sense, either.

If we looked at `$depth` as an index, we could also ask the question «What’s the deepest level you want to include?». Then a 0-based approach would make sense.

So to me, it depends on the naming of the variable and the description/question. WordPress chose the count-approach.

> In other words I think rather than closing this we should make `$level` 1-based for consistency.

Thanks for chiming in, @acobster!

- `$depth` – How many levels do you want to include? → That’s a count or a length
- `$length` – What level are we at? → That’s an index

Counts or lengths are usually 1-based and indices are 0-based, right? To me, a count and an index is not the same and so IMO they ***don’t have to be consistent***. That’s why I came to the conclusion that it’s fine like it is.

I think we can look at `$depth` and `$length` in isolation. Then, it’s more a question of: Do we want the level to a 1-based or 0-based index? And do we want to add a breaking change for something that kinda already is okay?

If an index is 1-based, I usually see that mentioned in the documentation, because it seems like it’s not the standard.

For example, if I use `class="nav-item--level-{{ item.level }}"`, do I want the levels to start at 0 or 1? If we changed this, this would probably affect a lot of CSS in different projects, which would make it so much more tedious to update. And I assume developers would fix it by using `class="nav-item--level-{{ item.level - 1 }}"`.

Maybe I’m missing something and I’m happy to update level to 1-based. Just trying to weigh the factors involved. Happy to get inputs or clarifications.

**Comment by acobster** [comment]
Makes sense to me. I haven't used `$level` in that way so wasn't aware it would be that big of a breaking change. Probably unwarranted just a for API consistency. :)

**Comment by gchtr** [comment]
Okay, thank you for your answer. I’m closing this, then :).
