### ISSUE TITLE
Backport #2395 to 1.x

### ISSUE THREAD

**Issue by dodomorandi** [timber/timber#2450]
## Expected behavior
No warnings on PHP >= 8.0 when using last stable release.

## Actual behavior
The issue (#2385) has been already solved, however last stable release (1.18.2) is before the fix (#2395).

## Steps to reproduce behavior
It is sufficient to initialize Timber and render a trivial template.

## What version of WordPress, PHP and Timber are you using?
WordPress 5.7.1, PHP 8.0.3, Timber 1.18.2

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
From composer

**Comment by joelambert** [comment]
Just wondering if there were any further thoughts on this?

We're in the process of getting [Lumberjack](https://lumberjack.rareloop.com) ready for PHP 8 but have a few failing tests due to this deprecation.

This appears to have been tagged as `1.x` but as it would require a breaking change to the API to resolve I'm wondering if we should be anticipating a major version bump instead?

**Comment by mahagr** [comment]
I think it is crucial to have this update.

**Comment by gchtr** [comment]
Great news 🎉! The fix is included in the [1.19.0 release](https://github.com/timber/timber/releases/tag/1.19.0).
