### ISSUE TITLE
Documentation colors contrast

### ISSUE THREAD

**Issue by EmilCataranciuc** [timber/timber#2464]
## Is your feature request related to a problem? Please describe.
Reading white text on black background is extremely difficult and hard on the eye.

## Describe the solution you’d like
Could you please change the colors or provide a colors switch? I think the documentation was presented black on white in the past.

**Comment by gchtr** [comment]
> I think the documentation was presented black on white in the past.

Yep, it was. Personally, I preferred the light color scheme, too, because I thought it was easier to read.

> Could you please change the colors or provide a colors switch?

We could provide a color switcher with a solution for Eleventy like this one: [Color Theme Switcher](https://mxb.dev/blog/color-theme-switcher/).

I think that’s an issue for @jarednova and his team to take over.

**Comment by Levdbas** [comment]
This is more of a docs repo issue then the Timber lib. @gchtr, shall we move it over there to clean it up over here?

Don't mind the accidental pin.. 👯
