### ISSUE TITLE
TimberImage::aspect() generates Fatal Error if image doesn't exist

### ISSUE THREAD

**Issue by slimndap** [timber/timber#2537]
## Expected behavior
Maybe `false` or `-1`?

## Actual behavior

A PHP warning: 
```
Fatal error: Uncaught DivisionByZeroError: Division by zero in /path/to/website/wp-content/plugins/timber-library/lib/Image.php on line 410
```
## Steps to reproduce behavior

1. Create a post.
2. Add an featured image.
3. Save post.
3. Add this in Twig template of single post: `{{ post.thumbnail.aspect }}`.
5. View the post on the front end. You should see a number.
4. Remove the thumbnail from disk (not from  media library).
5. View the post on the front end.
6. The PHP warning is triggered.

## What version of WordPress, PHP and Timber are you using?
WordPress 5.9, PHP 8.0, Timber 1.19.1

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

Using 'add new plugin' inside the WordPress admin.

**Comment by slimndap** [comment]
Additional information: the problem also occurs in PHP 7.3.5, but only trigger a _PHP warning_:

```
Warning: Division by zero in /path/to/website/wp-content/plugins/timber-library/lib/Image.php on line 410
```

**Comment by czernika** [comment]
It happens because of step 6 - while you physically removed image from disk its metadata and attachment post type object itself still presents in database. You may check it if you call `wp_get_attachment_metadata()` function (if you know image id) - it will return array of data even if image doesn't exists anymore. When you're deleting image from Media uploader - post object will be deleted

So what causes the issue? The thing is while image is not present, its metadata is still "alive" and will return some value. At some point, when you are calling `aspect` method, Timber will call `get_dimensions()` method which will set image data **ONLY** if image is present. And if image is not present... Well Timber doesn't handle this so the method will return `null`

```
// lib/Image.php

protected function get_dimensions( $dim ) {
    if ( isset($this->_dimensions) ) {
        return $this->get_dimensions_loaded($dim);
    }

    if ( file_exists($this->file_loc) && filesize($this->file_loc) ) {
        if ( ImageHelper::is_svg( $this->file_loc ) ) {
            $svg_size             = $this->svgs_get_dimensions( $this->file_loc );
            $this->_dimensions    = array();
            $this->_dimensions[0] = $svg_size->width;
            $this->_dimensions[1] = $svg_size->height;
        } else {
            list($width, $height) = getimagesize($this->file_loc);
            $this->_dimensions = array();
            $this->_dimensions[0] = $width;
            $this->_dimensions[1] = $height;
        }
        return $this->get_dimensions_loaded($dim);
    }
}
```

This mean your width and height will be equal to 0 which causes PHP error division by zero

```
// lib/Image.php

public function aspect() {
    $w = intval($this->width());
    $h = intval($this->height());
    return $w / $h; // zero divided by zero
}
```

To fix this you may check width before returning division result something like

```
public function aspect() {
    $w = intval($this->width());
    if ( 0 === $w ) {
        return false; // or whatever
    }
    $h = intval($this->height());

    return $w / $h;
}
```

But I would prefer to throw some kind of exception at the end - like things are actually going wrong - despite you've been able to get `post.thumbnail.src` path, the image will not be shown on front as it is not present

```
protected function get_dimensions( $dim ) {
    // ...

    throw new \Exception( "Image file doesn't exists" ); // or something like this
}
```

Or maybe it's a good idea to check it earlier on `init` moment

To fix issue outside of library itself you may check within twig template does image file exists or not

```
{% if fn('file_exists', post.thumbnail.file_loc) %}
	// everything ok, file presents 
{% endif %}
```

**Comment by jarednova** [comment]
@czernika thanks for the analysis! Would love to check out a PR based on your explanation. As you note: there's a fair question here about the right place to throw an error. I can imagine that while a dev would want to know, you wouldn't necessarily want the failure of an image load to 500 the entire page generation

**Comment by ghost** [comment]
Shouldn't we just close this issue? It has already been resolved in https://github.com/timber/timber/pull/2695, as I understand it. The method now is:

```php
public function aspect(): ?float
{
    $w = \intval($this->width());
    $h = \intval($this->height());

    if ($w and $h > 0) {
        return $w / $h;
    }

    return null;
}
```

**Comment by Levdbas** [comment]
You are right @expedition-robin-martijn . Closing this issue as well!
