### ISSUE TITLE
Any roadmap for 2.* release?

### ISSUE THREAD

**Issue by therealgilles** [timber/timber#2542]
Wondering if it's possible to get some visibility on the 2.* roadmap and release schedule. If it's still in the works.
If not anytime soon, it would be great to have a Timber update for Twig 3.* and other dependency updates.

**Comment by Levdbas** [comment]
I second that. I am also willing to spent some time as well to drive development forward but I don't know where to start at this moment. I would love to see a day organized where we rally some Timber users and contributors and iron out the release. We would need some guidance from the devs though. @jarednova , would you mind to give your thoughts on this?

And are there people interested in that?

**Comment by thdebay** [comment]
I'd also be interested in having some visibility on the 2.* roadmap and I could also consider contributing to this project, if the development is still active

**Comment by szepeviktor** [comment]
@jarednova Should I start a super-simple (6 page types) theme today with Timber v2?

**Comment by xsynaptic** [comment]
@szepeviktor I've been using Timber v2 in production on several blogs for months now, everything seems good. If you're starting something new I would totally use v2 to avoid upgrade hassles, keeping in mind that some things might still change before the official release.

**Comment by gchtr** [comment]
We just released a first beta for Timber 2.0: [2.0.0-beta.1 (release)](https://github.com/timber/timber/releases/tag/2.0.0-beta.1).

Unfortunately, we have no final release date yet and we don’t want to commit to one, because we all work on it in our free time. Thank you so much for understanding.

We made good progress in the last couple of weeks. If we can keep that momentum, I think you can expect a stable release soon.

For now, it would help us the most if you can test out the beta and report any bugs. Or if you feel like tackling known bugs for 2.0, there’s a [`2.0` label in the issues](https://github.com/timber/timber/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A2.0). Feel free to work on any issues that have no assignees yet. I tagged some of the with the "Help wanted" and "Good first issue" labels, because I think they would be easy to tackle.

I’ll leave this issue open for now in case you have additional questions.

**Comment by szepeviktor** [comment]
> test out the beta and report any bugs

You can use PHPStan for that. It tells you a few dozen problems right away.

**Comment by gchtr** [comment]
@szepeviktor Yep, working through the issues that PHPStan reports up to a certain level is also on our list. 👍

**Comment by szepeviktor** [comment]
Start on Level 0, it is less frightening.

**Comment by Levdbas** [comment]
Hi everyone, the team is hard at work to make Timber 2.0 happen. We've just created an updated roadmap with open tickets, pull requests, etc. If you would like to help out on Timber, now is the perfect timing. See #2741

Closing this ticket in favor of the mentioned ticket above.
