### ISSUE TITLE
Fatal Twig\Extension\DebugExtension Timber 1.21.0

### ISSUE THREAD

**Issue by adriencorb** [timber/timber#2661]
## Expected behavior

Enable "DebugExtension" in a Wordpres  theme.

## Actual behavior

A fatal “Fatal error: Uncaught LogicException: Unable to register extension “Twig\Extension\DebugExtension” as it is already registered.” is triggered

## Steps to reproduce behavior
Add this hook in function.php theme :

```
add_filter('get_twig', function($twig)
{
    $twig->addExtension(new \Twig_Extension_Debug());
    return $twig;
});
```
## What version of WordPress, PHP and Timber are you using?
WordPress 6.0.3, PHP 8.0, Timber 1.21.0

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Upgraded to auto updade WordPress

**Comment by gchtr** [comment]
@adriencorb Thanks for filling out this issue. We already know why this happens and it will be fixed with #2658.

This error happens, because we accidentally included Twig v2 instead of v1 in the plugin. And as of Twig 2, it’s not possible to register an extension twice. A `LogicException` will be thrown.

Because Timber already registers the DebugExtension when you set `WP_DEBUG` to `true`, you can **remove the line of code that registers the DebugExtension**. So in the next release, you will not see this error. But for future compatibility, it’s better to remove it now.

```php
add_filter('get_twig', function($twig)
{
	// 👇 Remove this line, because Timber already registers the DebugExtension.
    $twig->addExtension(new \Twig_Extension_Debug());
 
   return $twig;
});
```
