### ISSUE TITLE
[BUG] symfony/cache-extra and timber 2, cache method unclear

### ISSUE THREAD

**Issue by Levdbas** [timber/timber#2762]
### Expected Behavior

Setting up the cache extention on v2 and cache mode to default (transient) will save cache to database.

### Actual behavior

I have no clue where the cache is coming from and how to flush it. :D

### Steps to reproduce behavior

1. Setup Timber cache via https://timber.github.io/docs/v2/guides/performance/#cache-parts-of-the-twig-file-and-data
2. Create cache in a template via 
```
{% cache "what_is_love" %}
Baby don't hurt me
{% endcache %}
```
3. see that cache is loaded on pageload
4. change contents between the cache tags and refresh page, see that old content is still loaded.
5. Check database for transients, none found.
6. Run wp timber clear-cache, no luck as well
...

### Notes

I tried debugging  #2483 to see if it still persists on v2, but got stuck here. So the results are obviously cached _somewhere_. But I have no clue where...

### What version of Timber are you using?

2.x-dev

### What version of WordPress are you using?

6.2

### What version of PHP are you using?

8.0.27

### How did you install Timber?

Installed or updated Timber through Composer

**Comment by gchtr** [comment]
Cache files for Twig cache should be placed in `vendor/timber/timber/cache` by default. The can’t be saved in a transient, because Twig handles the whole caching for us. Probably it’s not clear from the documentation that the cache mode only applies to Timber’s caching function, but not to Twig cache.

You can update the cache location using the [`timber/twig/environment/options`](https://timber.github.io/docs/v2/hooks/filters/#timber/twig/environment/options) filter and set an absolute path for `cache`.

> `cache` *string* or false
>
> An absolute path where to store the compiled templates, or `false` to disable caching (which is the default).
>
> – via https://twig.symfony.com/doc/2.x/api.html#environment-options

But I’m not sure whether this works here. I’d be glad if you could quickly check that out.

In theory, the following functions should clear the Twig cache:

```php
Timber\Cache\Cleaner::clear_cache( 'twig' );
Timber\Cache\Cleaner::clear_cache_twig();
```

Or with the CLI:

```bash
wp timber clear-cache
wp timber clear-cache twig
```

The official way to clear Twig caches is to remove the files from the cache location. For this, you will have to know the location of the cache. `$twig->get_cache()` should return the location of the cache to remove it.

https://github.com/timber/timber/blob/a23d78178a3b043b888930186b7b384501d21855/src/Loader.php#L591

But as you can see, there’s still a todo because we didn’t test this yet with custom locations.

**Comment by Levdbas** [comment]
Alright, did some more digging to find the cache location:

Found it at:
`\tmp\symfony-cache\@` in the FS root.

Although cached, `$cache_location = $twig->getCache();` returned false... 

The way I added the cache extention following the [2.x guide](https://timber.github.io/docs/v2/guides/performance/#cache-parts-of-the-twig-file-and-data)

```php
public function add_to_twig($twig)
	{
		$twig->addExtension(new CacheExtension());
		$twig->addRuntimeLoader(new class implements RuntimeLoaderInterface
		{
			public function load($class)
			{
				if (CacheRuntime::class === $class) {
					return new CacheRuntime(new TagAwareAdapter(new FilesystemAdapter()));
				}
			}
		});
		return $twig;
	}`

I will keep digging to find how to set that actual location so we can update the guide.

**Comment by gchtr** [comment]
Great, thanks for looking into this!

**Comment by Levdbas** [comment]
Alright, finally got it working but it was a wild ride.

By setting the third parameter on the `FilesystemAdapter` class we can set the directory for the `{% cache %}` tags compiled files to the same _default_ directory as Timber when cache is _true_ using `timber/twig/environment/options`. Default location is the /tmp/ folder of the filesystem, which we obviously want to override.

```php
function update_twig_environment_options($options)
{

	$options['cache']       = true;
	$options['auto_reload'] = true;

	return $options;
}
add_filter('timber/twig/environment/options', 'update_twig_environment_options');

function add_to_twig($twig)
	{

		$twig->addRuntimeLoader(new class implements RuntimeLoaderInterface
		{
			public function load($class)
			{
				if (CacheRuntime::class === $class) {
                                         //  see third parameter
					return new CacheRuntime(new TagAwareAdapter(new FilesystemAdapter('', 0, TIMBER_LOC . '/cache/twig')));
				}
			}
		});
		$twig->addExtension(new CacheExtension());
		return $twig;
	}
add_filter('timber/twig', 'add_to_twig');
```
But how to get the location when you've changed the default location? 

We could advise to use `apply_filters('timber/twig/environment/options')` but that feels a bit dirty.

**Some things to consider in the docs**

- Make it clear that the  `{% cache %}` tags are always compiled to php files whatever the cache mode in Timber will be.
- that you have to set the correct default cache location in `FilesystemAdapter` based on your `timber/twig/environment/options`. or else Timber will not be aware of the cache location and will not be able to clear it.
- That caching always works using the  `{% cache %}` tags, even when `cache` is set to  `false` but that clearing the cache via `wp timber clear-cache twig` does _only_ work when `cache` is set to  `true`

All and all this is quite a big hassle now I think about it. With all the caching strategies in place, is this even something that we want to advise @gchtr ?

**Comment by gchtr** [comment]
Thanks for the deep dive into this, @Levdbas! It’s great that you found out how to set the cache location for the `{% cache %}` tags.

I think we definitely need to update the documentation for this.

> * Make it clear that the  `{% cache %}` tags are always compiled to php files whatever the cache mode in Timber will be.

Yes. We should definitely make it clear which caching mechanisms are using the cache mode.

I think we’re fine to add the cache location in the `FilesystemAdapter` to the example in the documentation. If somebody updates the cache location through `timber/twig/environment/options`, they would know the location and could pass it here as well.

But, if we want to make it work correctly with the CLI, then Timber would have to know the location, too. And Timber will get the location from `timber/twig/environment/options`. The question to me is: do we expose a function to access that value other than using `apply_filters('timber/twig/environment/options')`? Should we add `Timber::twig_cache_location()` or `Timber\Loader::twig_cache_location()` so that people could use it for `FilesystemAdapter` or in other places?

> * That caching always works using the  `{% cache %}` tags, even when `cache` is set to  `false` but that clearing the cache via `wp timber clear-cache twig` does _only_ work when `cache` is set to  `true`

Yes, it’s a bit of a hassle. But if we do nothing, there will only be confusion.

Our solution should be something along the lines of: We’ll show you how you can integrate different caching mechanisms, but we won’t do it for you completely out of the box.

I’m flagging this as not essential for the 2.0 release, but as something we can work on in a minor release.
