### ISSUE TITLE
Workaround for PHP 8.2 dynamic property deprecation warnings in Timber 1.x

### ISSUE THREAD

**Issue by anugupta** [timber/timber#2793]
## Is your feature request related to a problem? Please describe.

Timber 1.x seems to work under PHP 8.2 but the use of dynamic properties results in thousands of deprecation warnings per page load - eg `Creation of dynamic property Timber\User::$user_login is deprecated`

WP Engine are moving all PHP 8.0 sites to PHP 8.2 sites at the end of October and this means those sites will incur the above issue.

It's not a breaking change, but outputting thousands of deprecation warnings isn't great, will probably slow down sites (and make finding other errors more difficult as they'll be buried in the deprecation warnings chaff).

This problem can be mitigated by adding `#[\AllowDynamicProperties]` to `lib/Core.php`, but if you're using a deployment workflow where composer is run as part of the deployment process on a build server, this becomes difficult to do manually.

## Describe the solution you’d like

The simplest workaround for this would be to add the following to `lib/Core.php`

`#[\AllowDynamicProperties]`

This stops 99.9% of the deprecation warnings

## Describe alternatives you’ve considered
The alternatives are to manually add `#[\AllowDynamicProperties]` post deployment, or to use the composer-patches package to try and do this as part of the deployment flow.

## Additional context
As mentioned above, the main reason for wanting this is that WP Engine are compulsorily upgrading all PHP 8.0 sites to PHP 8.2 - there's no way of opting out.

**Comment by Levdbas** [comment]
Hi @anugupta , thank you for your detailed issue report. Since we are hard at work to release Timber 2.0 with support for PHP8.2 we currently do not have the time to add support for PHP8.2 in the 1.x version of Timber. I would like to invite you to test out Timber 2.0 if that works for you.

**Comment by okadots** [comment]
What about support for the Timber plugin? Will the plugin be updated with the release of Timber 2.0?

I have some older sites that are using the plugin and we are not able to switch to installing Timber in our theme instead.

**Comment by Levdbas** [comment]
Hi @okadots , in#2005 you can read the reasoning behind why we are not releasing  the plugin version of Timber as of Timber 2. 

As what I can see from the amount of emoji your post got, it seems that quite a lot of people  don't like this, which i understand. 

I would like to invite all of you to let us know what is holding you back in using the composer version of Timber. Maybe we can create some extra documentation to help you in the transition. I will open a new issue for that and refer to it here.

**Comment by rmens** [comment]
Should there be a big fat warning on the plug-in page on Wordpress.org that it’s essentially sunset? You don’t want people starting with it with 2.0 around the corner.

**Comment by Levdbas** [comment]
I totally agree @rmens . I opened a new issue in #2794 to tackle this. 

I invite all of you to this issue to let us know why you haven't made the switch yet to the composer version of Timber. 

This issue stays open for the starting posts.

**Comment by cbirdsong** [comment]
The release today says:

> This release coincides with the final version to the WordPress.org site.

So there is no chance of an update incorporating the `#[\AllowDynamicProperties]` fix suggested by the OP?

For context:

> I invite all of you to this issue to let us know why you haven't made the switch yet to the composer version of Timber.

I have updated to the composer version for new projects, but many older themes I developed are using the plugin version and are not actively maintained. We have been pitching some of those clients on updates that would also include switching to Timber 2.0, but that just isn't going to happen for all of them or even most of them. Keeping up basic PHP compatibility through low-effort tweaks like this would help tremendously for sites in that scenario.

**Comment by gchtr** [comment]
The plugin version of Timber is [still using Twig v1](https://github.com/timber/timber/blob/b988e51e5bc9e9743745b4d3c6eba6e106fae83f/bin/deploy-to-wp-org.sh#L16-L17).  When we look at the [changelog for Twig v1](https://github.com/twigphp/Twig/blob/1.x/CHANGELOG), we can see that support for PHP 8.1 was added. But it’s not officially compatible with PHP 8.2. And Twig v1 is not maintained anymore, so there won’t be any official PHP 8.2 support. I’d rather not release a plugin version where can’t garantuee support for PHP 8.2.

Updating to Twig 2 in the Timber plugin would be a breaking change in the plugin itself, so that is no option either.

What we could do is to release a Composer version with support for PHP 8.2 in Timber 1.x. When you use the Composer version, then Twig v2 will be installed when all conditions are met because of the version constraint used in composer.json. If anybody wants to do a PR for that, then you’re welcome.

Even if we add PHP 8.2 compatibility, the way forward is to update to Timber 2. If you currently have no plan to update these older projects, then you’re postponing the problem to a year later or so. With the recent PHP versions, PHP has been moving faster to end support for older versions. I know it’s not easy to burden clients with problems like these, when basically a website still works. We’re in the same situation with some of our clients. The reality is however that WordPress needs constant maintenance. If you want a site that runs for several years without touching it, WordPress isn’t the right tool.

You could also take the plugin code and create your own plugin version that fixes these problems with PHP 8.2. But we don’t invest any of our resources in that. Instead, we want to get Timber v2 released as soon as possible.

**Comment by adamtomat** [comment]
@gchtr A composer-only version with support for PHP 8.2 in Timber 1.x would help us out a lot in the interim while we schedule a bigger migration piece with clients to Timber v2!

Is there a ballpark release schedule for Timber v2 yet (this year, early next year)?

**Comment by gchtr** [comment]
> @gchtr A composer-only version with support for PHP 8.2 in Timber 1.x would help us out a lot in the interim while we schedule a bigger migration piece with clients to Timber v2!

Let’s do that, then. Does someone want to create a pull request for that?

> Is there a ballpark release schedule for Timber v2 yet (this year, early next year)?

If all goes well this week, we should have a 2.0 release out by the end of this week! 😉

**Comment by Levdbas** [comment]
PR is merged in 1.x.  Only waiting for https://github.com/timber/timber/pull/2890 to tag this release

**Comment by gchtr** [comment]
This is now released in https://github.com/timber/timber/releases/tag/1.24.0.
