### ISSUE TITLE
[BUG] Your titleTypeError: call_user_func_array(): 

### ISSUE THREAD

**Issue by verma-s3** [timber/timber#2803]
### Expected Behavior

Should shows the frontend and backend of website. 

### Actual behavior

![image](https://github.com/timber/timber/assets/91693041/9eef8ebd-bbb4-48a3-a039-dee235307b15)

### Steps to reproduce behavior

1. 
2.
3.
...

### What version of Timber are you using?

Timber 2.0.0-rc.1

### What version of WordPress are you using?

WordPress 6.3.1

### What version of PHP are you using?

PHP 8.0

### How did you install Timber?

Installed or updated Timber through Composer

**Comment by jrathert** [comment]
From what you write it is not even clear that Timber is causing the error at all (if you search for the problem, you can find many many references to it, with many different solutions). Can you provide a bit more context about your site (e.g., other plugins etc.)? Have you still activated the Timber v1 plugin (if yes: deactivate it)?  I would suggest to create a minimal example that causes the error and then provide additional information.

**Comment by Levdbas** [comment]
Hi @verma-s3,

The **notice** sounds like the same issue @jrathert  had in [this reply](https://github.com/timber/timber/issues/2741#issuecomment-1712588118). You are probably calling a site option directly. Most obvious should be `{{ site.home }}` instead of  `{{ site.link }}`. Can you check your **Twig** files for calls to `site`.

The **fatal error** is  _highly likely_  caused by `add_filter()` call in your theme files with the wrong amount of parameters. You can check if you theme has any an try to pinpoint the issue.

**Comment by verma-s3** [comment]
@jrathert Answering your questions: I do not Timber V1. I have installed timber through composer and then updated it to timber2.0.0-rc.1 version for testing. Besides that I had advanced custom fields plugin but I have deactivated that too. Everything is working fine on PHP version 7.4 when I upgrade PHP version to 8.0 it start giving error. 
![image](https://github.com/timber/timber/assets/91693041/edb09d1e-33e9-4497-966d-be85c9316bb5)
I have this code in my function.php file. @Levdbas I do not have {{site.home}} in my code. But I do have {{site.url}}. is that also depreciated? If have any starter theme for timber 2.0. please do let us know.

**Comment by jrathert** [comment]
Hi @verma-s3 -

re: the **Notice**: It should be `{{ site.link }}` instead of `{{ site.home }}` or `{{ site.url }}`- I am pretty sure it will work, why not just give it a try?

re the **Fatal Error**: Looking at your stack trace it seems it is `do_action('init')` that fires the error. From the code you sent, everything looks ok, but this one:
```
add_action('init', array( $this, 'remove_comment_support', 100) );
```
Assuming the 100 is the priority, shouldn't that be
 ```
add_action('init', array( $this, 'remove_comment_support'), 100 );
```
It is not perfectly clear to me, why this may work with PHP7.4 and not 8.0, but I would give it a try. Other than that, I have no idea what might be wrong here?!

BTW: Why do you use PHP 8.0? It is [almost end of life](https://www.php.net/supported-versions.php)? I'd recommend to switch to 8.1 at least.

**Comment by Levdbas** [comment]
Thanks @jrathert for helping @verma-s3 out with this. @verma-s3 , keep in mind that is more of a support question and not a question about Timber itself. Since the hook `remove_comment_support` is from your own codebase I would highly recommend you to try to fix this yourself so you fully understand the code you are working with.

**Comment by verma-s3** [comment]
It is working. Thanks for your support and time. I am looking into https://timber.github.io/docs/v2/upgrade-guides/2.0/ for all potential changes and depreciations. I have upgrade timber first and try to solve all errors then comes in my way. Then I upgrade to Php 8.0 and then Php 8.1 for other changes, warnings and errors. I will definitely end up with latest version of PHP. Thanks for helping out @jrathert and @Levdbas. Couldn't wait for Timber 2.0 official release.

**Comment by Levdbas** [comment]
Great to here you managed to fix this @verma-s3!
