### ISSUE TITLE
"Timber::get_post() was called incorrectly," thinking it was passing a post by post slug or name

### ISSUE THREAD

**Issue by columbian-chris** [timber/timber#2845]
Trying to migrate to 2.0.0.  I've got `Timber\Helper::doing_it_wrong()` throwing this warning at me:

> Function Timber::get_post() was called incorrectly. Getting a post by post slug or post name was removed from Timber::get_post() in Timber 2.0. Use Timber::get_post_by() instead. (This message was added in version 2.0.0.)

...but my query is not trying to get a post by a slug or name.  Query args:

```php
$my_post = Timber::get_post(
   array(
      'post_type' => 'custom_content_type',
      'tax_query' => array(
         array(
            'taxonomy' => 'sponsored_category',
            'field' => 'slug',
            'terms' => 'carousel',
         )
      ),
      'orderby' => 'date',
      'order' => 'DESC',
      'ignore_sticky_posts' => true,
   )
);
```

### What version of Timber are you using?

2.0.0

### What version of WordPress are you using?

6.4.1

### What version of PHP are you using?

8.1.25

### How did you install Timber?

Composer

**Comment by Levdbas** [comment]
~~I think you need to use get_posts instead of get_post and then limit it to one.~~

Edit: I just tested your exact query @columbian-chris , and I do not get such warning. Are you sure this is not caused by another query?

**Comment by columbian-chris** [comment]
> I just tested your exact query @columbian-chris , and I do not get such warning. Are you sure this is not caused by another query?

Did you change your `post_type` and `tax_query` with parameters that actually exist in your environment?  I'm querying from a custom post type with its own defined taxonomy.

**Comment by Levdbas** [comment]
Yes, and this causes no issue. Btw, the error is only thrown when first argument that is passed to get_post is a is a string and not a number. See: https://github.com/timber/timber/blob/ee467c650e51d042a04d9107f35239cbc566d4d7/src/Timber.php#L254

Since in your example you are clearly passing an array, I am not pretty sure that that query is not causing that deprecation notice. It seems that you are somewhere calling `Timber::get_post()` with a string as an argument.
 If I were you I would try to exclude as much code from the equation as possible, try to isolate your issue.

**Comment by columbian-chris** [comment]
I discovered this was from an entirely different culprit.  I was passing a string into `Timber::get_image()` and it must have passed that string to `Timber::get_post()`, causing this issue.  Closing.

**Comment by Levdbas** [comment]
Glad you figured out what went wrong!

**Comment by columbian-chris** [comment]
Thank you so much for your assistance, @Levdbas!
