### ISSUE TITLE
[BUG] Timber::get_pages_menu() throws warnings when using Polylang

### ISSUE THREAD

**Issue by lnorby** [timber/timber#2922]
### Expected Behavior

Expected to not get any warning messages.

### Actual behavior

Warning:
Undefined array key "menu" in
wp-content\mu-plugins\polylang\frontend\frontend-nav-menu.php
on line 280

Warning:
Undefined array key "theme_location" in
wp-content\mu-plugins\polylang\frontend\frontend-nav-menu.php
on line 294

### What version of Timber are you using?

2.0

### What version of WordPress are you using?

6.4.3

### What version of PHP are you using?

8.1

### How did you install Timber?

Installed or updated Timber through Composer

**Comment by Levdbas** [comment]
Hi @lnorby , This might have something to do with how you are setting up your menus.

if you are using the Timber::get_menu function you could try this:

```php
// use 
$menu = Timber::get_menu( 'my-menu', [
    'menu' => YOUR_MENU_ID,
    'theme_location' => 'YOUR_REGISTERED_MENU_LOCATION'
  ]
 );

```
If that does not help, please post the code how you set up the menu that causes this issue.

Edit: @timber/rangers 

This might be a bug?

[Here ](https://github.com/timber/timber/blob/e6a8957afeed29aebf8fecc3fb2fecddbd8ea89c/src/Factory/MenuFactory.php#L100C9-L100C26)we set `$args['location']` . Shouldn't that be mimicking [wp_nav_menu_args ](https://developer.wordpress.org/reference/hooks/wp_nav_menu_args/#parameters) so`$args['location']` becomes `$args['theme_location']`

**Comment by lnorby** [comment]
I am using `Timber::get_pages_menu()`. I tried the following, and it worked. No warnings now.

```
Timber::get_pages_menu( [
    'menu' => '',
    'theme_location' => '',
] )
```

Maybe you could set these as default arguments for the method.

Edit: `Timber::get_menu()` has no warnings with Polylang, only `Timber::get_pages_menu()`.

**Comment by Levdbas** [comment]
Hmm, looking at the default arguments for wp_page_menu()'s which Timber is using, there are no menu and theme_location arguments. https://developer.wordpress.org/reference/functions/wp_page_menu/

So adding these two parameters to get_pages_menu is not something that is standard in WordPress as well. Polylang might be checking for the wrong parameters when handling a pages menu?

**Comment by lnorby** [comment]
The `wp_page_menu()` function itself is working fine with Polylang, no warnings.

**Comment by Levdbas** [comment]
Hi @lnorby ,

I took another look at this and I think what leads to your error is the following:

1. [the pages menu by wordpress takes a wp_page_menu and transforms it to an actual menu
2. to be compatible with both the wordpress pages function and the wordpress menu we apply both the  `wp_page_menu_args`  and `wp_nav_menu_args` filters in [Timber::get_page_menu()](https://github.com/timber/timber/blob/e6a8957afeed29aebf8fecc3fb2fecddbd8ea89c/src/PagesMenu.php#L156)
3. Since Polylang is adding a [filter here to wp_nav_menu_args](https://github.com/polylang/polylang/blob/6bc83b27d491fb3b371ba1ed7ffb9b155daac241/frontend/frontend-nav-menu.php#L38) that assumes `menu` and 'theme_location' are always set, this fails. I think it is right for them to assume those properties are always set since they are by default set by WordPress. and thus the error occurs.

@timber/rangers , is this something the encourage to fix by the user themself or do we want to improve the compatibility since we are actively calling the `wp_nav_menu_args` without providing all the arguments?

**Comment by gchtr** [comment]
> @timber/rangers , is this something the encourage to fix by the user themself or do we want to improve the compatibility since we are actively calling the `wp_nav_menu_args` without providing all the arguments?

@timber/rangers We’ve already done a lot of work to make Timber more compatible with native menu filters. If we can improve compatibility here, I think we should.

**Comment by cafesk8** [comment]
@gchtr @Levdbas - Would really appreciate if you took a second look at this. Thank you.

**Comment by cafesk8** [comment]
@Levdbas - can you publish 2.3 tag since you mention it in code? So I can update it via composer?

**Comment by Levdbas** [comment]
@cafesk8 , I think we are almost ready to release 2.3.0. Hopefully somewhere still in this week.
