### ISSUE TITLE
[BUG] Timber::get_terms() not finding custom taxonomies

### ISSUE THREAD

**Issue by mmarol** [timber/timber#2953]
### Expected Behavior

I was hoping to use `$context['terms'] = Timber::get_terms('deliverable-type');` or `$context['terms'] = Timber::get_terms();` to get a list of terms from my custom taxonomy `deliverable-type`.

### Actual behavior

`$context['terms'] = Timber::get_terms('deliverable-type');` returns an empty array.
`$context['terms'] = Timber::get_terms();` returns the default `Primary menu` and the `Uncategorized` category.

### Steps to reproduce behavior

1. Using the Starter Site files as an example, I added `require_once __DIR__ . '/src/StarterSite.php';` to my functions.php
2. In StarterSite.php I've added `add_action( 'init', array( $this, 'register_taxonomies' ) );` and required a `taxonomies.php` file which provides the arguments for `register_taxonomy('deliverable-type', 'project', $deliverableArgs);`
3. I've checked the backend and added a few terms to the new taxonomy.
4. In the page-home.php file that I'm using for my homepage, I've added `$context['terms'] = Timber::get_terms('deliverable-types');`
5. In my page-home.twig file, I tried to debug the list using {{ dump(terms) }}
6. I get the behavior described above

### Notes

- The custom taxonomy is registered to a custom post type called `Projects`
- I have triple-checked the spelling in my functions.php file
- It is working as a custom taxonomy on the WP backend. 
- In fact, I can find the individual terms using `get_term(ID)`.

### What version of Timber are you using?

2.0.0

### What version of WordPress are you using?

6.4.3

### What version of PHP are you using?

8.1.23

### How did you install Timber?

Installed or updated Timber through Composer

**Comment by mmarol** [comment]
Looks like I'm able to get the terms if I do
`$context['terms'] = get_terms(array('taxonomy' => 'deliverable-type','hide_empty' => false));`
instead. 

I guess I don't really understand the difference between `get_terms()` and `Timber::get_terms()`.

**Comment by Levdbas** [comment]
Hi @mmarol ,

`hide_emtpy` is true [by default](https://developer.wordpress.org/reference/classes/wp_term_query/__construct/#parameters), so that is why you are not getting results in your first attempts. If you have posts attached to one of the terms `Timber::get_terms('deliverable-type');` will get you a result.

So get_terms and Timber::get_terms() actually behave in a same way.

@timber/rangers , we do not have a test to get a taxonomy by name/string. Pretty obvious that it would work, but might be worth to add a test for this? 

```php
public function testGetTermsByName()
    {
        register_taxonomy('animals', 'post');
        $term_id = $this->factory->term->create([
            'name' => 'Cat',
            'taxonomy' => 'animals',
        ]);

        $post_id = $this->factory->post->create();
        wp_set_object_terms($post_id, [$term_id], 'animals');

        $terms_from = Timber::get_terms('animals');
        $this->assertEquals('Cat', $terms_from[0]->title());
    }
```

And it might be a good idea to add a note about the default behaviour that empty terms are not shown by default in the [docblock](https://github.com/timber/timber/blob/5785128c1fbb817e146bbf5fdecc270c1856bae8/src/Timber.php#L698)? In this fluent interface you sometimes forget the default arguments that are still being set by default in WordPress.

**Comment by Levdbas** [comment]
Hi @mmarol , can you please let us know of this solves your issue?

**Comment by mmarol** [comment]
@Levdbas thank you for that clarification, specifying `'hide_empty' => 'false'` worked! Will close the issue.
