### ISSUE TITLE
[DOCS] Timber\Term documentation is lacks get_terms()

### ISSUE THREAD

**Issue by jasalt** [timber/timber#3020]
### Expected Behavior

Following example "Get a term with a slug" at https://timber.github.io/docs/v2/reference/timber-term/ with WooCommerce Brands plugin (uses taxonomy with slug "product_brand"), I expected following to return brands but the template keeps getting empty brands:
```
$context['brands'] = Timber::get_term('product_brand');
```

### Actual behavior

Correct command seems to be:
```
$context['brands'] = Timber::get_terms('product_brand');
```
After this the brands can be printed in template.

### Steps to reproduce behavior

Have taxonomy with slug 'product_brand' that is added to some posts, or WooCommerce Brands -plugin.

### Notes

Didn't test if other code examples on the page are working..

Digging documentation further, I find information on `get_terms()` here: https://timber.github.io/docs/v2/guides/terms/#querying-terms. I think it's just missing from the API reference..

### What version of Timber are you using?

2.2.0

### How did you install Timber?

None

**Comment by Levdbas** [comment]
Hi @jasalt,

`Timber::get_term('product_brand');` will not work to get all terms of an item since you are using the taxonomy name instead of of a term identifier. As you found out, you will need to use Timber::get_terms for that.

`Timber::get_terms()` is an API function of the `Timber` class which uses the underlying TimberFactory private class under the hood. So that's why you wont find the docs on the https://timber.github.io/docs/v2/reference/timber-term/ page.

Hope that helps!
