### ISSUE TITLE
Add protocol s3 to ImageHelper::ALLOWED_PROTOCOLS

### ISSUE THREAD

**Issue by marc-lpg** [timber/timber#3065]
# Issue Description
Our website uses an S3 bucket for media, but the s3 protocol is not included in ImageHelper::ALLOWED_PROTOCOLS. As a result, the ImageHelper::is_protocol_allowed method returns false, causing an exception to be thrown:
``
InvalidArgumentException: 'The output file scheme is not supported.'
``
# Proposed Solution
It appears that simply adding s3 to the list of allowed protocols resolves the issue. Perhaps we could add a filter to make ALLOWED_PROTOCOLS configurable, particularly where it is used in the ImageHelper::is_protocol_allowed method (as of Timber v2.1.0).

## Versions
Timber : v2.3.0
WP : v6.7.1
PHP : 8.3

**Comment by Levdbas** [comment]
Hi @marc-lpg , I think this issue does not exist anymore in Timber 2.x. Since we are no longer actively maintaining Timber 1.x, are you able to do an upgrade?

And please, do not skip our bug report template. We want to know what exact versions you are running to help you the best we can.

**Comment by marc-lpg** [comment]
Sorry i forgot to give the versions i'm using in my original post : 
Timber :  v2.3.0
WP : v6.7.1
PHP : 8.3

**Comment by Levdbas** [comment]
Hi @marc-lpg , `ImageHelper::ALLOWED_PROTOCOLS` or `is_protocol_allowed` are only present in Timber version 2.1.0 due to a security issue with PHP8.0. We bumped the minimal version to 8.1 in 2.2.0 and removed these methods. Please double check your installed version since I have a feeling you are still running an older version.

PR where we removed this code: https://github.com/timber/timber/pull/2983/files

**Comment by marc-lpg** [comment]
Thank you @Levdbas for your help. I was indeed using version 2.1.0 and it works now in 2.3. Sorry for this !
