### ISSUE TITLE
Filtering for ACF post object content

### ISSUE THREAD

**Issue by plweil** [timber/timber#366]
I have a custom field that returns a post object whose content is some text with some simple html formatting. I want to display the content of this field using standard wordpress content filtering. I tried using the post.content() method, but {{ post.get_field('my_post_object_field).content() }} does not return anything. Manually applying the WordPress filtering function does work; e.g., 

{{ fn('apply_filters', 'the_content', (post.get_field('my_post_object_field').post_content)) }}

But is there an easier way to do this using Timber methods?

**Comment by turansadri** [comment]
> You could also add _the_content_ as a Twig filter. Put the following in your _functions.php_ file:
> 
> ```
> function theme_add_twig_filters( $twig ){
>     $twig->addFilter( 'the_content', new Twig_Filter_Function( function( $content ) {
>         return apply_filters( 'the_content', $content );
>     } ) );
>     return $twig;
> }
> add_action( 'twig_apply_filters', 'theme_add_twig_filters' );
> ```

If someone ends up here using using newer version of Timber you want to use Twig_SimpleFilter instead of depracated Twig_Filter_Function. 

```
$twig->addFilter( new Twig_SimpleFilter('the_content', function( $content ) {
    return apply_filters( 'the_content', $content );
}));
```

Using Twig_Filter_Function was causing a very annoying mostly harmless error in admin when ACF Gutenberg blocks were used. It was adding a "php-error" class to body element thus causing white space to the top of the admin.
