### ISSUE TITLE
Insert wp_nav_menu instead of TimberMenu

### ISSUE THREAD

**Issue by paul-straetmans** [timber/timber#367]
Since I'm having problems with the TimberMenu ( see Issue #341 ) I would like to use the original Wordpress Menu (because that would fix my problems) instead of the TimberMenu. Unfortunately I'm having trouble getting this easy sounding task done.

When I place this inside of functions.php

```
$data['menu_2'] = wp_nav_menu( array( 'theme_location' => 'top navigation' ) );
```

And then in base.twig use the data

```
{% for item in menu_2.get_items %}
       <li id="menu-item-{{item.ID}}" class="{% if 'current-page-ancestor' in item.classes or 'current-menu-item' in item.classes %}active{% endif %} {{item.classes | join(' ')}} menu-item-{{item.ID}}">
             <a class="menu-item__link" href="{{item.link}}">{{item.title}}</a>
       </li>
{% endfor %}
```

The Navigation elements are shown. But somehow the complete HTML document is messed up. The for loop for menu_2 is ignored inside the twig file. All the items that normally are inside HEAD are after the Menu in BODY tag.

I understand this is probably not possible, because it has nothing to with timber anymore but how can I then just insert the wp_nav_menu?

This didn’t work as well: https://github.com/jarednova/timber/wiki/Sidebar#method-2-twig-file
And I couldn’t get this to work as well: https://github.com/jarednova/timber/wiki/WP-Integration#functions

**Comment by Gaffen** [comment]
I'm still researching solutions to this problem, as it is affecting me too, however in the meantime your solution is a great workaround.

Please refer to the default arguments for wp_nav_menu here:
https://codex.wordpress.org/Function_Reference/wp_nav_menu

If you set 'echo' => true in your args array, the context receive the raw html for the menu, because you didn't set this argument it tried to echo out the menu in functions.php - making it appear before your html <head> element

**Comment by palmiak** [comment]
@paul-straetmans can we mark this issue as solved? Please respond in two weeks or we'll close this thread.
