### ISSUE TITLE
Post Object Advanced Custom Field

### ISSUE THREAD

**Issue by anugupta** [timber/timber#418]
I have an ACF custom field that is a Post Object (allows the user to choose a blog post to display on a page).

In the $context array, this field is a `WP_Post` object. I'd like to make it a `TimberPost` object so that I can use the Timber / Twig functions on it. What's the best way of doing this? Does it make a difference that this field is inside an ACF Flexible Content layout?

**Comment by elliottmangham** [comment]
Hi @jarednova,

I realise this is closed, but because it's quite an old one - I wondered if the above is now possible?

On my Posts page, I have an ACF 'Post Object' field that allows the client to select a "Featured Blog Article". 

Functionally, this works fine. Though the data is a `WP_Post` object, so I can't use `{{ featured_article.title }}` but rather, `{{ featured_article.post_title }}` for example. Even more annoyingly, I cannot target ACF data from that post.

This is leading me to do the following (on `index.php`):

```php
// Get ID of Journal page
$journal_ID = get_option( 'page_for_posts' );

// Featured article
$featured_article = get_field('featured_article', $journal_ID);
if($featured_article) {
	$featured_article_ID = $featured_article->ID;
}
$get_featured_article = get_field_objects($featured_article_ID);

$context['featured_article_wp'] = get_field('featured_article', $journal_ID);
$context['featured_article_acf'] = $get_featured_article;
```

Then on the Posts page, in my  corresponding Twig file, I have to use a combination of `{{ featured_article_wp.example }}` and `{{ featured_article_acf.example }}` in order to display it properly.

Hope this is clear and that there is a better solution.

Thank you!

**Comment by connorjburton** [comment]
It's been a very long time since I touched wordpress (or PHP for that matter) but the `get_field` method I modified is the one belonging to `Timber\Post` . You are just using `get_field` which we don't touch.

So to achieve what you want, maybe try

```php
$journal = Timber::get_post(get_option('page_for_posts'));

$featured_article = $journal->get_field('featured_article');
```

Maybe... it's been a while but essentially you are using the wrong `get_field` method, you need to use the one on the `Timber\Post` object itself rather than the global one.

**Comment by elliottmangham** [comment]
Hi @connorjburton,

Thanks a bunch for the speedy response!

I tried your solution but unusually it throws an error:
`Fatal error: Uncaught Error: Call to a member function get_field() on string in...`

I have managed to achieve what I need with the following:
```php
$journal = get_option('page_for_posts');
$featured_article = get_field('featured_article', $journal);
if($featured_article) {
	$featured_article_ID = $featured_article->ID;
	$featured_article = new TimberPost($featured_article);
}
$context['featured_article'] = $featured_article;
```

This isn't too messy, and simple enough to implement quickly.

Thanks again!
