### ISSUE TITLE
[Suggestion] Create different packages for library and WordPress plugin

### ISSUE THREAD

**Issue by mrgrain** [timber/timber#835]
Timber is a library.
> It's a Library, not a Framework
[upstatement.com/timber](http://upstatement.com/timber/)

Just by itself it does not do anything. Timber needs a theme (or something else) to make use of the features it provides.
> Once Timber is installed and activated in your plugin directory, it gives any WordPress theme the ability to take advantage of the power of Twig and other Timber features.
Most 

Being a plugin is allright given how WordPress currently works. Themes can be shipped without Timber. Multiple installed themes can use the same library files. However, as it is a Plugin Timber can be deactivated by an unexperienced user thus breaking the themes. From a user's point of you Timber is something unknown. It should therefore be hidden from users.

Using a modern WordPress stack like Bedrock, Timber can be required from a composer file. However it can still be deactivated. Creating a separate library  package allow themes to rely on Timber without the plugin management part. This is especially useful with Bedrock (and others).

Any thoughts on this?

**Comment by connorjburton** [comment]
+1 to this, we have a base theme that we roll out to all our clients, would be nice to not have Timber as a required plugin rather baked in.

**Comment by mamarilmanson** [comment]
+1

**Comment by jarednova** [comment]
Hey guys, thanks for the nudges here. I have some questions to @mrgrain and @connorjburton:

It seems what you guys are recommending is to make the version on GitHub (and thus, distributed by Packagist) a "composer optimized" version of Timber where it would live in the `/vendor` directory in a theme. Then we'd adjust the build script for WP.org to stay as-is. 

**What code changes would this require?**
It would seem to me that just adjusting some of the declarations in Composer and the loading logic, this could be accomplished in very short-order

**What are the backwards-compatibility risks?**
Very interested in thoughts here. I can think of only edge-cases (where someone has a script that feeds the GH Timber directly into the Plugins directory of a WP site)

**When should this be done**
Since this has the potential to break some backwards compatibilities, this feels like it could tie into the 1.0 milestone.

**Comment by connorjburton** [comment]
I'm not sure on the code changes required.

**Backward compatibility risks**

If someone has GH Timber cloned into the plugins dir, I would assume they aren't doing it for stability sakes, rather development purposes - and moreover, doubt it'd be on a production server. I've never submitted a package to Packagist, does it just feed from GH, can it pick up releases? If so we can package up releases in specific ways if we really want to keep the GH version agnostic - however i'm not sure that'll be necessary and personally wouldn't be worried about those edge-cases.

**When it should be done**

As long as it doesn't disturb the plugin variant, then _soon_, if it's going to effect current users then it may need more thought.

**Comment by loganyott** [comment]
I agree with this. I've just started using this recently and hacked it a bit to accomplish this. Here's how I edited my project's composer.json to accomplish this:
```
"extra": {
  "installer-paths": {
    "vendor/{$vendor}/{$name}/": ["jarednova/timber"]
  }
},
"autoload": {
  "classmap": ["vendor/jarednova/timber/timber.php"]
}
```

`extra` is overriding the installer path. Since this is declared a `wordpress-plugin`, I was conveniently able to override with composer installers. (If this was just a package, it would be going to that directory)
`autoload` is using `classmap`, which tells composer to parse any files in the given path for classes. This is how Timber actually declares autoloading to Composer (and hence why _most_ classes are picked up automatically). Since the base `Timber` class is in the plugin file, this `autoload` declaration tells it to pick it up.
I've just recently started using this, so YMMV on the above fix.

**Possible short term path**
Move `Timber` to `lib` and make `timber/timber.php` just a dummy plugin file that requires the class. People could then override the `installer-paths` on their own like I did.
**Possible long term path**
Move `Timber` to `lib` and get rid of the plugin file. You could then host a `jarednova/timber-plugin` that has the actual plugin file added.
**Even better long term path**
Move `Timber` to `lib` and get rid of the plugin file. Then, change your build process to add a plugin file for the plugin repo. I highly doubt there's much backwards compatibility issues with changing how the GH repo is hosted. I agree that anyone bringing this in with Github or Composer is likely going to figure this out very quickly or is not even using it as a plugin.

PS @connorjburton: Packagist will indeed automatically pick up releases/tags/branches.

**Comment by mrgrain** [comment]
Hey @jarednova Sorry for the delay ;)

**What code changes would this require?**
- Remove [timber.php](https://github.com/jarednova/timber/blob/master/timber.php) and make sure that all its functionality is moved to the library files or documented. (Currently the only thing is the default dirname `Timber::$dirname = 'views';`)
- Change the plugin type in the composer.json file.

I don't think anything else is need immediately, however there are many possible improvements when going into this directions (e.g. namespaces). Also I am not sure about how the current testing scripts work. They might need some changes to make it work.

**What are the backwards-compatibility risks?**
Well, it depends. I would actually suggest to create a new package `jarednova/timber-library` (or timber-lib or timber-core) and keep maintaining the current one as the official plugin package. It would require the new timber-library package and itself only contain the timber.php plugin file plus the wordpress build scripts. There's no need to include them into the library package.

Doing it this way, there won't be any surprises for people using this repo. Anyone (or script) cloning this repo directly should be fine as well, as the library code is now delivered via composer.

**When should this be done**
Now. There is no better timing than doing this before the 1.0 milestone.

**Comment by mrgrain** [comment]
**Sidenote on the repository thing**
You might want to _rename_ this repo and package, thus keeping all the issues and the wiki where they belong to. Then create a new repo and package with the old name. But I am not sure about this. Depends on where you want to keep the main information flow.

**Comment by connorjburton** [comment]
I like the idea of timber-core being the central place for issues/PR's. A bit like how

https://github.com/laravel

Is split into Framework and Laravel

**Comment by connorjburton** [comment]
Sorry for multiple comments, if we have a Timber organisation, we can then add the Starter theme in there too and start developing a collection of add-ons if needed.

**Comment by mamarilmanson** [comment]
:+1:

**Comment by jarednova** [comment]
Thanks to everyone for weighing in! First off, some great news. [Timothy H](http://planethsolutions.com/contact/), who owns [Planet H Solutions](https://github.com/timber) (oh, and the github.com/timber username) was kind enough to give it to us to organize the project. This (to @connorjburton's suggestion) makes it much easier to organize the project into respective repos.

My plan is to move things over from jarednova/ and Upstatement/ into timber this weekend. By the end we should have a set of official subprojects organized into one convenient place. My thinking is...

**timber/timber**
The project's canonical home. This is where we would migrate this repo to with the full issue log, code history etc. With the 1.0 release, the file organization would make it so it runs from a `vendor/` subdirectory to be included with themes. It would also contain the build scripts to push to wp.org

**timber/starter-theme**
This is where I'll move the [starter theme repo](https://github.com/upstatement/timber-starter-theme)

**timber/plugin**
(name feedback?) This would contain the WP plugin should someone want to install directly from GH for dev purposes

**timber/????**
The future is wide open

**Comment by mrgrain** [comment]
(y)

**Comment by connorjburton** [comment]
Sounds good @jarednova - it'd be good to have namespaces alongside separating the packages, I'm open to working on that if you like?

**Comment by jarednova** [comment]
Sounds good @connorjburton — please take it from here. With namespacing, is there a particular strategy that will make that backwards compatible?

**Comment by connorjburton** [comment]
In terms of < PHP 5.3? I'm not sure there is a suitable workaround unfortunately, may be worth collecting some user data before making the jump?

**Comment by mrgrain** [comment]
There is no way to make namespaces work in < PHP 5.3. It's just about dropping support for it. Also, composer requires PHP 5.3.x. and I doubt that the generated autload.php works with PHP 5.2, as it uses namespaces itself .

**Comment by connorjburton** [comment]
Oh I think I got what you meant, with `TimberPost` -> `Timber\Post`? I'm not sure if `class_alias` works on namespaces classes, though I'd assume it would.

If so there are a couple of options, use a trait (would bump our required PHP version to 5.4) or utilise `TimberCore`

**Comment by jarednova** [comment]
Assigning this to @connorjburton for final resolution. As we discussed in email the acceptance criteria for this ticket is to allow Timber to be included in a theme's `vendor` directory from Composer with no additional loading required (such as activating a plugin or doing a `require_once` or something)

**Comment by jarednova** [comment]
Also, as a note @connorjburton: I split the namespacing task/discussion into #869. If it's _necessary_ to do so as a part of this ticket (for example, to solve for composer autoloading), go for it — otherwise it's my preference that it happens later so that we can get this one taken care of sooner

**Comment by connorjburton** [comment]
Started this on https://github.com/connorjburton/timber/tree/dev-composer
