### ISSUE TITLE
Cannot access property started with '\0'

### ISSUE THREAD

**Issue by parisholley** [timber/timber#924]
### What version of WordPress, PHP and Timber are you using?

php (7.0.4) - heroku
### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

wordpress plugin

timber-core.php:import(), if it attempts to set $this->$key = foobar and $key is private/protected, it throws an error. I don't have this issue on my local php 7 env

**Comment by jarednova** [comment]
@parisholley I think I need a little more info. From what I follow you're talking about if a variable is declared as private/protected you get an error? for example...

```php

private $zebra;

class TimberWhatever extends TimberPost {


}
```

... and then if you have a meta_key of 'zebra' you get an error? Do I have that right? The title of the issue seems to suggest something else

**Comment by parisholley** [comment]
@jarednova Yep!

**Comment by palmiak** [comment]
@parisholley Is this still something you're actively working on or need addressed? Please respond in two weeks or we'll close this thread
