### ISSUE TITLE
Idea: Store twigs in CPT post content

### ISSUE THREAD

**Issue by lgedeon** [timber/timber#940]
Have you considered storing twigs in the post content of a custom post type?

I have a project that requires a unique layout for every page and for posts in each term of a taxonomy. The pages and posts would share many common elements, but in vastly different arrangements. The number of checkboxes and gadgets on the edit screen to get the flexibility I need would be prohibitive. Plus more options = more slow.

I really like the flexibility that a twig template gives you, and the compiling is essential for speed. Honestly Timber is almost exactly what I need, except that uploading new twigs every time we create a page or a new term could lead to many problems.

I know that storing twigs in the database instead of the file system can be a security risk and a performance drain, but I am planning to require a compile before any new page or edit goes live so that should help with speed. As for security, we may have to restrict certain functionality for db based twigs. I still have to look into that more.

Anyway, I wanted to get your thoughts on this in general before jumping deep into the code. It would be great to share as much code as possible, but I don't want to get in your way either.

**Comment by connorjburton** [comment]
Hm, my personal opinion is saving templates in the DB is generally never a good solution, it just falls down in so many areas, including version control.

Obviously I don't know your exact setup/needs however wouldn't a build process work? Define a `.json` file or similar with the different combinations of taxonomies and what elements match said taxonomies? Then write a little script that builds up layouts based on that JSON file? 

That would solve the issue of writing a template for new iteration (you'd just update the config with new combinations), and is should fit right into your workflow.

**Comment by lgedeon** [comment]
Anytime you have to touch the file system you add friction. Twigs in the database, means edits on mobile and shared computers without having to set up ftp or open a text editor. For us, as developers, that's no big deal, but for everyone else, that's the difference between making a page or not. ...I feel like I am arguing for WP over plain html all over again. :)

Revisions on WP posts are nothing like as powerful as git, but they will do and sometimes you have to give up a little to get something better.

I should clarify, that I am not purposing switching to storing twigs only in the db. I am just suggesting adding that as an optional storage location.

**Comment by connorjburton** [comment]
Well that is already a possibility with file editing via the WP Admin, we wouldn't need to save the templates in the DB to achieve modifications via the admin.

Are you proposing a way to edit/visualise templates per post/page in the admin?

It's certainly possible, however I don't think it would part of the core - at least not for the foreseeable future - we would more than welcome an extension though, i'd be really interested in seeing a working example as it's not something i've felt I have needed before and not sure how big of a need this is for people ( obviously there is a need, otherwise we wouldn't be discussing it! 😄  )

I'm happy to be proven wrong and apologises if I am misunderstanding.

**Comment by lgedeon** [comment]
I have been thinking about just writing to the file system either from theme-editor.php or a hook on save-post, but that seems to carry with it all the concerns we might have had with using the database without the file system. Either way we have to deal with twigs being untrusted content.

And we don't really get a speed boost either, because after compiling, the database would only be accessed when edits are made. Only complied content would be used to serve visitors.

Plus writing to the file system is not an option in many environments. If this can be made bullet-proof using the db only, we may never need ftp again.

I might have just shot myself in the foot there. If you can't write to the file system, you can't compile, huh?

**Comment by connorjburton** [comment]
The biggest roadblock in my mind on this is being able to share this with other developers. Just having all the templates in git works perfectly because I know that the templates are going to be the same for every developer and every environment/server I deploy it on.

I guess if that isn't a priority then DB may be an option, but in my situation it wouldn't be feasible.

Just giving you my use case :)

And yes there certainly has to be something that writes to the FS, otherwise will have a template and no view!

**Comment by lgedeon** [comment]
Yeah, ok, I think I will just write to the file system. If that isn't an option for some installs they will have to use the shortcodes. I can just suggest Timber an optional additional feature.
